/*
  Warnings:
  - The primary key for the `categories` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to alter the column `category_id` on the `categories` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - The primary key for the `cities` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to alter the column `city_id` on the `cities` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - You are about to alter the column `country_id` on the `cities` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - The primary key for the `countries` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to alter the column `country_id` on the `countries` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - You are about to alter the column `city_id` on the `locations` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - You are about to alter the column `country_id` on the `locations` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - You are about to alter the column `tag_id` on the `post_tags` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - You are about to alter the column `category_id` on the `posts` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - The primary key for the `roles` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to alter the column `role_id` on the `roles` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - The primary key for the `tags` table will be changed. If it partially fails, the table could be left without primary key constraint.
  - You are about to alter the column `tag_id` on the `tags` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
  - You are about to alter the column `role_id` on the `users` table. The data in that column could be lost. The data in that column will be cast from `BigInt` to `Integer`.
*/
-- DropForeignKey
ALTER TABLE "cities" DROP CONSTRAINT "cities_country_id_fkey";

-- DropForeignKey
ALTER TABLE "locations" DROP CONSTRAINT "locations_city_id_fkey";

-- DropForeignKey
ALTER TABLE "locations" DROP CONSTRAINT "locations_country_id_fkey";

-- DropForeignKey
ALTER TABLE "post_tags" DROP CONSTRAINT "post_tags_tag_id_fkey";

-- DropForeignKey
ALTER TABLE "posts" DROP CONSTRAINT "posts_category_id_fkey";

-- DropForeignKey
ALTER TABLE "users" DROP CONSTRAINT "users_role_id_fkey";

-- AlterTable: categories
ALTER TABLE "categories" DROP CONSTRAINT "categories_pkey";
ALTER TABLE "categories" ALTER COLUMN "category_id" DROP IDENTITY IF EXISTS;
ALTER TABLE "categories" ALTER COLUMN "category_id" DROP DEFAULT;
ALTER TABLE "categories" ALTER COLUMN "category_id" TYPE INTEGER;
ALTER TABLE "categories" ALTER COLUMN "category_id" ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "categories" ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("category_id");

-- AlterTable: countries
ALTER TABLE "countries" DROP CONSTRAINT "countries_pkey";
ALTER TABLE "countries" ALTER COLUMN "country_id" DROP IDENTITY IF EXISTS;
ALTER TABLE "countries" ALTER COLUMN "country_id" DROP DEFAULT;
ALTER TABLE "countries" ALTER COLUMN "country_id" TYPE INTEGER;
ALTER TABLE "countries" ALTER COLUMN "country_id" ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "countries" ADD CONSTRAINT "countries_pkey" PRIMARY KEY ("country_id");

-- AlterTable: cities
ALTER TABLE "cities" DROP CONSTRAINT "cities_pkey";
ALTER TABLE "cities" ALTER COLUMN "city_id" DROP IDENTITY IF EXISTS;
ALTER TABLE "cities" ALTER COLUMN "city_id" DROP DEFAULT;
ALTER TABLE "cities" ALTER COLUMN "city_id" TYPE INTEGER;
ALTER TABLE "cities" ALTER COLUMN "country_id" TYPE INTEGER;
ALTER TABLE "cities" ALTER COLUMN "city_id" ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "cities" ADD CONSTRAINT "cities_pkey" PRIMARY KEY ("city_id");

-- AlterTable: roles
ALTER TABLE "roles" DROP CONSTRAINT "roles_pkey";
ALTER TABLE "roles" ALTER COLUMN "role_id" DROP IDENTITY IF EXISTS;
ALTER TABLE "roles" ALTER COLUMN "role_id" DROP DEFAULT;
ALTER TABLE "roles" ALTER COLUMN "role_id" TYPE INTEGER;
ALTER TABLE "roles" ALTER COLUMN "role_id" ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "roles" ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("role_id");

-- AlterTable: tags
ALTER TABLE "tags" DROP CONSTRAINT "tags_pkey";
ALTER TABLE "tags" ALTER COLUMN "tag_id" DROP IDENTITY IF EXISTS;
ALTER TABLE "tags" ALTER COLUMN "tag_id" DROP DEFAULT;
ALTER TABLE "tags" ALTER COLUMN "tag_id" TYPE INTEGER;
ALTER TABLE "tags" ALTER COLUMN "tag_id" ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "tags" ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("tag_id");

-- AlterTable: locations (no identity, just type changes)
ALTER TABLE "locations" 
  ALTER COLUMN "city_id" TYPE INTEGER,
  ALTER COLUMN "country_id" TYPE INTEGER;

-- AlterTable: post_tags
ALTER TABLE "post_tags" ALTER COLUMN "tag_id" TYPE INTEGER;

-- AlterTable: posts
ALTER TABLE "posts" ALTER COLUMN "category_id" TYPE INTEGER;

-- AlterTable: users
ALTER TABLE "users" ALTER COLUMN "role_id" TYPE INTEGER;

-- DropEnum
DROP TYPE "BlockType";

-- AddForeignKey
ALTER TABLE "cities" ADD CONSTRAINT "cities_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "countries"("country_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "locations" ADD CONSTRAINT "locations_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "countries"("country_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "locations" ADD CONSTRAINT "locations_city_id_fkey" FOREIGN KEY ("city_id") REFERENCES "cities"("city_id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "tags"("tag_id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "posts" ADD CONSTRAINT "posts_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("role_id") ON DELETE SET NULL ON UPDATE CASCADE;