
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `comment_likes` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model comment_likes
 * 
 */
export type comment_likesModel = runtime.Types.Result.DefaultSelection<Prisma.$comment_likesPayload>

export type AggregateComment_likes = {
  _count: Comment_likesCountAggregateOutputType | null
  _min: Comment_likesMinAggregateOutputType | null
  _max: Comment_likesMaxAggregateOutputType | null
}

export type Comment_likesMinAggregateOutputType = {
  user_id: string | null
  comment_id: string | null
  created_at: Date | null
}

export type Comment_likesMaxAggregateOutputType = {
  user_id: string | null
  comment_id: string | null
  created_at: Date | null
}

export type Comment_likesCountAggregateOutputType = {
  user_id: number
  comment_id: number
  created_at: number
  _all: number
}


export type Comment_likesMinAggregateInputType = {
  user_id?: true
  comment_id?: true
  created_at?: true
}

export type Comment_likesMaxAggregateInputType = {
  user_id?: true
  comment_id?: true
  created_at?: true
}

export type Comment_likesCountAggregateInputType = {
  user_id?: true
  comment_id?: true
  created_at?: true
  _all?: true
}

export type Comment_likesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which comment_likes to aggregate.
   */
  where?: Prisma.comment_likesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of comment_likes to fetch.
   */
  orderBy?: Prisma.comment_likesOrderByWithRelationInput | Prisma.comment_likesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.comment_likesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` comment_likes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` comment_likes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned comment_likes
  **/
  _count?: true | Comment_likesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Comment_likesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Comment_likesMaxAggregateInputType
}

export type GetComment_likesAggregateType<T extends Comment_likesAggregateArgs> = {
      [P in keyof T & keyof AggregateComment_likes]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateComment_likes[P]>
    : Prisma.GetScalarType<T[P], AggregateComment_likes[P]>
}




export type comment_likesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.comment_likesWhereInput
  orderBy?: Prisma.comment_likesOrderByWithAggregationInput | Prisma.comment_likesOrderByWithAggregationInput[]
  by: Prisma.Comment_likesScalarFieldEnum[] | Prisma.Comment_likesScalarFieldEnum
  having?: Prisma.comment_likesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Comment_likesCountAggregateInputType | true
  _min?: Comment_likesMinAggregateInputType
  _max?: Comment_likesMaxAggregateInputType
}

export type Comment_likesGroupByOutputType = {
  user_id: string
  comment_id: string
  created_at: Date | null
  _count: Comment_likesCountAggregateOutputType | null
  _min: Comment_likesMinAggregateOutputType | null
  _max: Comment_likesMaxAggregateOutputType | null
}

export type GetComment_likesGroupByPayload<T extends comment_likesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Comment_likesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Comment_likesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Comment_likesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Comment_likesGroupByOutputType[P]>
      }
    >
  >



export type comment_likesWhereInput = {
  AND?: Prisma.comment_likesWhereInput | Prisma.comment_likesWhereInput[]
  OR?: Prisma.comment_likesWhereInput[]
  NOT?: Prisma.comment_likesWhereInput | Prisma.comment_likesWhereInput[]
  user_id?: Prisma.UuidFilter<"comment_likes"> | string
  comment_id?: Prisma.UuidFilter<"comment_likes"> | string
  created_at?: Prisma.DateTimeNullableFilter<"comment_likes"> | Date | string | null
  comments?: Prisma.XOR<Prisma.CommentsScalarRelationFilter, Prisma.commentsWhereInput>
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}

export type comment_likesOrderByWithRelationInput = {
  user_id?: Prisma.SortOrder
  comment_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  comments?: Prisma.commentsOrderByWithRelationInput
  users?: Prisma.usersOrderByWithRelationInput
}

export type comment_likesWhereUniqueInput = Prisma.AtLeast<{
  user_id_comment_id?: Prisma.comment_likesUser_idComment_idCompoundUniqueInput
  AND?: Prisma.comment_likesWhereInput | Prisma.comment_likesWhereInput[]
  OR?: Prisma.comment_likesWhereInput[]
  NOT?: Prisma.comment_likesWhereInput | Prisma.comment_likesWhereInput[]
  user_id?: Prisma.UuidFilter<"comment_likes"> | string
  comment_id?: Prisma.UuidFilter<"comment_likes"> | string
  created_at?: Prisma.DateTimeNullableFilter<"comment_likes"> | Date | string | null
  comments?: Prisma.XOR<Prisma.CommentsScalarRelationFilter, Prisma.commentsWhereInput>
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}, "user_id_comment_id">

export type comment_likesOrderByWithAggregationInput = {
  user_id?: Prisma.SortOrder
  comment_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.comment_likesCountOrderByAggregateInput
  _max?: Prisma.comment_likesMaxOrderByAggregateInput
  _min?: Prisma.comment_likesMinOrderByAggregateInput
}

export type comment_likesScalarWhereWithAggregatesInput = {
  AND?: Prisma.comment_likesScalarWhereWithAggregatesInput | Prisma.comment_likesScalarWhereWithAggregatesInput[]
  OR?: Prisma.comment_likesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.comment_likesScalarWhereWithAggregatesInput | Prisma.comment_likesScalarWhereWithAggregatesInput[]
  user_id?: Prisma.UuidWithAggregatesFilter<"comment_likes"> | string
  comment_id?: Prisma.UuidWithAggregatesFilter<"comment_likes"> | string
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"comment_likes"> | Date | string | null
}

export type comment_likesCreateInput = {
  created_at?: Date | string | null
  comments: Prisma.commentsCreateNestedOneWithoutComment_likesInput
  users: Prisma.usersCreateNestedOneWithoutComment_likesInput
}

export type comment_likesUncheckedCreateInput = {
  user_id: string
  comment_id: string
  created_at?: Date | string | null
}

export type comment_likesUpdateInput = {
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  comments?: Prisma.commentsUpdateOneRequiredWithoutComment_likesNestedInput
  users?: Prisma.usersUpdateOneRequiredWithoutComment_likesNestedInput
}

export type comment_likesUncheckedUpdateInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  comment_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type comment_likesCreateManyInput = {
  user_id: string
  comment_id: string
  created_at?: Date | string | null
}

export type comment_likesUpdateManyMutationInput = {
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type comment_likesUncheckedUpdateManyInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  comment_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type comment_likesUser_idComment_idCompoundUniqueInput = {
  user_id: string
  comment_id: string
}

export type comment_likesCountOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  comment_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type comment_likesMaxOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  comment_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type comment_likesMinOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  comment_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type Comment_likesListRelationFilter = {
  every?: Prisma.comment_likesWhereInput
  some?: Prisma.comment_likesWhereInput
  none?: Prisma.comment_likesWhereInput
}

export type comment_likesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type comment_likesCreateNestedManyWithoutCommentsInput = {
  create?: Prisma.XOR<Prisma.comment_likesCreateWithoutCommentsInput, Prisma.comment_likesUncheckedCreateWithoutCommentsInput> | Prisma.comment_likesCreateWithoutCommentsInput[] | Prisma.comment_likesUncheckedCreateWithoutCommentsInput[]
  connectOrCreate?: Prisma.comment_likesCreateOrConnectWithoutCommentsInput | Prisma.comment_likesCreateOrConnectWithoutCommentsInput[]
  createMany?: Prisma.comment_likesCreateManyCommentsInputEnvelope
  connect?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
}

export type comment_likesUncheckedCreateNestedManyWithoutCommentsInput = {
  create?: Prisma.XOR<Prisma.comment_likesCreateWithoutCommentsInput, Prisma.comment_likesUncheckedCreateWithoutCommentsInput> | Prisma.comment_likesCreateWithoutCommentsInput[] | Prisma.comment_likesUncheckedCreateWithoutCommentsInput[]
  connectOrCreate?: Prisma.comment_likesCreateOrConnectWithoutCommentsInput | Prisma.comment_likesCreateOrConnectWithoutCommentsInput[]
  createMany?: Prisma.comment_likesCreateManyCommentsInputEnvelope
  connect?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
}

export type comment_likesUpdateManyWithoutCommentsNestedInput = {
  create?: Prisma.XOR<Prisma.comment_likesCreateWithoutCommentsInput, Prisma.comment_likesUncheckedCreateWithoutCommentsInput> | Prisma.comment_likesCreateWithoutCommentsInput[] | Prisma.comment_likesUncheckedCreateWithoutCommentsInput[]
  connectOrCreate?: Prisma.comment_likesCreateOrConnectWithoutCommentsInput | Prisma.comment_likesCreateOrConnectWithoutCommentsInput[]
  upsert?: Prisma.comment_likesUpsertWithWhereUniqueWithoutCommentsInput | Prisma.comment_likesUpsertWithWhereUniqueWithoutCommentsInput[]
  createMany?: Prisma.comment_likesCreateManyCommentsInputEnvelope
  set?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  disconnect?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  delete?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  connect?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  update?: Prisma.comment_likesUpdateWithWhereUniqueWithoutCommentsInput | Prisma.comment_likesUpdateWithWhereUniqueWithoutCommentsInput[]
  updateMany?: Prisma.comment_likesUpdateManyWithWhereWithoutCommentsInput | Prisma.comment_likesUpdateManyWithWhereWithoutCommentsInput[]
  deleteMany?: Prisma.comment_likesScalarWhereInput | Prisma.comment_likesScalarWhereInput[]
}

export type comment_likesUncheckedUpdateManyWithoutCommentsNestedInput = {
  create?: Prisma.XOR<Prisma.comment_likesCreateWithoutCommentsInput, Prisma.comment_likesUncheckedCreateWithoutCommentsInput> | Prisma.comment_likesCreateWithoutCommentsInput[] | Prisma.comment_likesUncheckedCreateWithoutCommentsInput[]
  connectOrCreate?: Prisma.comment_likesCreateOrConnectWithoutCommentsInput | Prisma.comment_likesCreateOrConnectWithoutCommentsInput[]
  upsert?: Prisma.comment_likesUpsertWithWhereUniqueWithoutCommentsInput | Prisma.comment_likesUpsertWithWhereUniqueWithoutCommentsInput[]
  createMany?: Prisma.comment_likesCreateManyCommentsInputEnvelope
  set?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  disconnect?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  delete?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  connect?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  update?: Prisma.comment_likesUpdateWithWhereUniqueWithoutCommentsInput | Prisma.comment_likesUpdateWithWhereUniqueWithoutCommentsInput[]
  updateMany?: Prisma.comment_likesUpdateManyWithWhereWithoutCommentsInput | Prisma.comment_likesUpdateManyWithWhereWithoutCommentsInput[]
  deleteMany?: Prisma.comment_likesScalarWhereInput | Prisma.comment_likesScalarWhereInput[]
}

export type comment_likesCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.comment_likesCreateWithoutUsersInput, Prisma.comment_likesUncheckedCreateWithoutUsersInput> | Prisma.comment_likesCreateWithoutUsersInput[] | Prisma.comment_likesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.comment_likesCreateOrConnectWithoutUsersInput | Prisma.comment_likesCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.comment_likesCreateManyUsersInputEnvelope
  connect?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
}

export type comment_likesUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.comment_likesCreateWithoutUsersInput, Prisma.comment_likesUncheckedCreateWithoutUsersInput> | Prisma.comment_likesCreateWithoutUsersInput[] | Prisma.comment_likesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.comment_likesCreateOrConnectWithoutUsersInput | Prisma.comment_likesCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.comment_likesCreateManyUsersInputEnvelope
  connect?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
}

export type comment_likesUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.comment_likesCreateWithoutUsersInput, Prisma.comment_likesUncheckedCreateWithoutUsersInput> | Prisma.comment_likesCreateWithoutUsersInput[] | Prisma.comment_likesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.comment_likesCreateOrConnectWithoutUsersInput | Prisma.comment_likesCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.comment_likesUpsertWithWhereUniqueWithoutUsersInput | Prisma.comment_likesUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.comment_likesCreateManyUsersInputEnvelope
  set?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  disconnect?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  delete?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  connect?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  update?: Prisma.comment_likesUpdateWithWhereUniqueWithoutUsersInput | Prisma.comment_likesUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.comment_likesUpdateManyWithWhereWithoutUsersInput | Prisma.comment_likesUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.comment_likesScalarWhereInput | Prisma.comment_likesScalarWhereInput[]
}

export type comment_likesUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.comment_likesCreateWithoutUsersInput, Prisma.comment_likesUncheckedCreateWithoutUsersInput> | Prisma.comment_likesCreateWithoutUsersInput[] | Prisma.comment_likesUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.comment_likesCreateOrConnectWithoutUsersInput | Prisma.comment_likesCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.comment_likesUpsertWithWhereUniqueWithoutUsersInput | Prisma.comment_likesUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.comment_likesCreateManyUsersInputEnvelope
  set?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  disconnect?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  delete?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  connect?: Prisma.comment_likesWhereUniqueInput | Prisma.comment_likesWhereUniqueInput[]
  update?: Prisma.comment_likesUpdateWithWhereUniqueWithoutUsersInput | Prisma.comment_likesUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.comment_likesUpdateManyWithWhereWithoutUsersInput | Prisma.comment_likesUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.comment_likesScalarWhereInput | Prisma.comment_likesScalarWhereInput[]
}

export type comment_likesCreateWithoutCommentsInput = {
  created_at?: Date | string | null
  users: Prisma.usersCreateNestedOneWithoutComment_likesInput
}

export type comment_likesUncheckedCreateWithoutCommentsInput = {
  user_id: string
  created_at?: Date | string | null
}

export type comment_likesCreateOrConnectWithoutCommentsInput = {
  where: Prisma.comment_likesWhereUniqueInput
  create: Prisma.XOR<Prisma.comment_likesCreateWithoutCommentsInput, Prisma.comment_likesUncheckedCreateWithoutCommentsInput>
}

export type comment_likesCreateManyCommentsInputEnvelope = {
  data: Prisma.comment_likesCreateManyCommentsInput | Prisma.comment_likesCreateManyCommentsInput[]
  skipDuplicates?: boolean
}

export type comment_likesUpsertWithWhereUniqueWithoutCommentsInput = {
  where: Prisma.comment_likesWhereUniqueInput
  update: Prisma.XOR<Prisma.comment_likesUpdateWithoutCommentsInput, Prisma.comment_likesUncheckedUpdateWithoutCommentsInput>
  create: Prisma.XOR<Prisma.comment_likesCreateWithoutCommentsInput, Prisma.comment_likesUncheckedCreateWithoutCommentsInput>
}

export type comment_likesUpdateWithWhereUniqueWithoutCommentsInput = {
  where: Prisma.comment_likesWhereUniqueInput
  data: Prisma.XOR<Prisma.comment_likesUpdateWithoutCommentsInput, Prisma.comment_likesUncheckedUpdateWithoutCommentsInput>
}

export type comment_likesUpdateManyWithWhereWithoutCommentsInput = {
  where: Prisma.comment_likesScalarWhereInput
  data: Prisma.XOR<Prisma.comment_likesUpdateManyMutationInput, Prisma.comment_likesUncheckedUpdateManyWithoutCommentsInput>
}

export type comment_likesScalarWhereInput = {
  AND?: Prisma.comment_likesScalarWhereInput | Prisma.comment_likesScalarWhereInput[]
  OR?: Prisma.comment_likesScalarWhereInput[]
  NOT?: Prisma.comment_likesScalarWhereInput | Prisma.comment_likesScalarWhereInput[]
  user_id?: Prisma.UuidFilter<"comment_likes"> | string
  comment_id?: Prisma.UuidFilter<"comment_likes"> | string
  created_at?: Prisma.DateTimeNullableFilter<"comment_likes"> | Date | string | null
}

export type comment_likesCreateWithoutUsersInput = {
  created_at?: Date | string | null
  comments: Prisma.commentsCreateNestedOneWithoutComment_likesInput
}

export type comment_likesUncheckedCreateWithoutUsersInput = {
  comment_id: string
  created_at?: Date | string | null
}

export type comment_likesCreateOrConnectWithoutUsersInput = {
  where: Prisma.comment_likesWhereUniqueInput
  create: Prisma.XOR<Prisma.comment_likesCreateWithoutUsersInput, Prisma.comment_likesUncheckedCreateWithoutUsersInput>
}

export type comment_likesCreateManyUsersInputEnvelope = {
  data: Prisma.comment_likesCreateManyUsersInput | Prisma.comment_likesCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type comment_likesUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.comment_likesWhereUniqueInput
  update: Prisma.XOR<Prisma.comment_likesUpdateWithoutUsersInput, Prisma.comment_likesUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.comment_likesCreateWithoutUsersInput, Prisma.comment_likesUncheckedCreateWithoutUsersInput>
}

export type comment_likesUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.comment_likesWhereUniqueInput
  data: Prisma.XOR<Prisma.comment_likesUpdateWithoutUsersInput, Prisma.comment_likesUncheckedUpdateWithoutUsersInput>
}

export type comment_likesUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.comment_likesScalarWhereInput
  data: Prisma.XOR<Prisma.comment_likesUpdateManyMutationInput, Prisma.comment_likesUncheckedUpdateManyWithoutUsersInput>
}

export type comment_likesCreateManyCommentsInput = {
  user_id: string
  created_at?: Date | string | null
}

export type comment_likesUpdateWithoutCommentsInput = {
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneRequiredWithoutComment_likesNestedInput
}

export type comment_likesUncheckedUpdateWithoutCommentsInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type comment_likesUncheckedUpdateManyWithoutCommentsInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type comment_likesCreateManyUsersInput = {
  comment_id: string
  created_at?: Date | string | null
}

export type comment_likesUpdateWithoutUsersInput = {
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  comments?: Prisma.commentsUpdateOneRequiredWithoutComment_likesNestedInput
}

export type comment_likesUncheckedUpdateWithoutUsersInput = {
  comment_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type comment_likesUncheckedUpdateManyWithoutUsersInput = {
  comment_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type comment_likesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  comment_id?: boolean
  created_at?: boolean
  comments?: boolean | Prisma.commentsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["comment_likes"]>

export type comment_likesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  comment_id?: boolean
  created_at?: boolean
  comments?: boolean | Prisma.commentsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["comment_likes"]>

export type comment_likesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  comment_id?: boolean
  created_at?: boolean
  comments?: boolean | Prisma.commentsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["comment_likes"]>

export type comment_likesSelectScalar = {
  user_id?: boolean
  comment_id?: boolean
  created_at?: boolean
}

export type comment_likesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"user_id" | "comment_id" | "created_at", ExtArgs["result"]["comment_likes"]>
export type comment_likesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  comments?: boolean | Prisma.commentsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type comment_likesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  comments?: boolean | Prisma.commentsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type comment_likesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  comments?: boolean | Prisma.commentsDefaultArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}

export type $comment_likesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "comment_likes"
  objects: {
    comments: Prisma.$commentsPayload<ExtArgs>
    users: Prisma.$usersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    user_id: string
    comment_id: string
    created_at: Date | null
  }, ExtArgs["result"]["comment_likes"]>
  composites: {}
}

export type comment_likesGetPayload<S extends boolean | null | undefined | comment_likesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$comment_likesPayload, S>

export type comment_likesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<comment_likesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Comment_likesCountAggregateInputType | true
  }

export interface comment_likesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['comment_likes'], meta: { name: 'comment_likes' } }
  /**
   * Find zero or one Comment_likes that matches the filter.
   * @param {comment_likesFindUniqueArgs} args - Arguments to find a Comment_likes
   * @example
   * // Get one Comment_likes
   * const comment_likes = await prisma.comment_likes.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends comment_likesFindUniqueArgs>(args: Prisma.SelectSubset<T, comment_likesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__comment_likesClient<runtime.Types.Result.GetResult<Prisma.$comment_likesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Comment_likes that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {comment_likesFindUniqueOrThrowArgs} args - Arguments to find a Comment_likes
   * @example
   * // Get one Comment_likes
   * const comment_likes = await prisma.comment_likes.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends comment_likesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, comment_likesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__comment_likesClient<runtime.Types.Result.GetResult<Prisma.$comment_likesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Comment_likes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {comment_likesFindFirstArgs} args - Arguments to find a Comment_likes
   * @example
   * // Get one Comment_likes
   * const comment_likes = await prisma.comment_likes.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends comment_likesFindFirstArgs>(args?: Prisma.SelectSubset<T, comment_likesFindFirstArgs<ExtArgs>>): Prisma.Prisma__comment_likesClient<runtime.Types.Result.GetResult<Prisma.$comment_likesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Comment_likes that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {comment_likesFindFirstOrThrowArgs} args - Arguments to find a Comment_likes
   * @example
   * // Get one Comment_likes
   * const comment_likes = await prisma.comment_likes.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends comment_likesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, comment_likesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__comment_likesClient<runtime.Types.Result.GetResult<Prisma.$comment_likesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Comment_likes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {comment_likesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Comment_likes
   * const comment_likes = await prisma.comment_likes.findMany()
   * 
   * // Get first 10 Comment_likes
   * const comment_likes = await prisma.comment_likes.findMany({ take: 10 })
   * 
   * // Only select the `user_id`
   * const comment_likesWithUser_idOnly = await prisma.comment_likes.findMany({ select: { user_id: true } })
   * 
   */
  findMany<T extends comment_likesFindManyArgs>(args?: Prisma.SelectSubset<T, comment_likesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$comment_likesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Comment_likes.
   * @param {comment_likesCreateArgs} args - Arguments to create a Comment_likes.
   * @example
   * // Create one Comment_likes
   * const Comment_likes = await prisma.comment_likes.create({
   *   data: {
   *     // ... data to create a Comment_likes
   *   }
   * })
   * 
   */
  create<T extends comment_likesCreateArgs>(args: Prisma.SelectSubset<T, comment_likesCreateArgs<ExtArgs>>): Prisma.Prisma__comment_likesClient<runtime.Types.Result.GetResult<Prisma.$comment_likesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Comment_likes.
   * @param {comment_likesCreateManyArgs} args - Arguments to create many Comment_likes.
   * @example
   * // Create many Comment_likes
   * const comment_likes = await prisma.comment_likes.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends comment_likesCreateManyArgs>(args?: Prisma.SelectSubset<T, comment_likesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Comment_likes and returns the data saved in the database.
   * @param {comment_likesCreateManyAndReturnArgs} args - Arguments to create many Comment_likes.
   * @example
   * // Create many Comment_likes
   * const comment_likes = await prisma.comment_likes.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Comment_likes and only return the `user_id`
   * const comment_likesWithUser_idOnly = await prisma.comment_likes.createManyAndReturn({
   *   select: { user_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends comment_likesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, comment_likesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$comment_likesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Comment_likes.
   * @param {comment_likesDeleteArgs} args - Arguments to delete one Comment_likes.
   * @example
   * // Delete one Comment_likes
   * const Comment_likes = await prisma.comment_likes.delete({
   *   where: {
   *     // ... filter to delete one Comment_likes
   *   }
   * })
   * 
   */
  delete<T extends comment_likesDeleteArgs>(args: Prisma.SelectSubset<T, comment_likesDeleteArgs<ExtArgs>>): Prisma.Prisma__comment_likesClient<runtime.Types.Result.GetResult<Prisma.$comment_likesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Comment_likes.
   * @param {comment_likesUpdateArgs} args - Arguments to update one Comment_likes.
   * @example
   * // Update one Comment_likes
   * const comment_likes = await prisma.comment_likes.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends comment_likesUpdateArgs>(args: Prisma.SelectSubset<T, comment_likesUpdateArgs<ExtArgs>>): Prisma.Prisma__comment_likesClient<runtime.Types.Result.GetResult<Prisma.$comment_likesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Comment_likes.
   * @param {comment_likesDeleteManyArgs} args - Arguments to filter Comment_likes to delete.
   * @example
   * // Delete a few Comment_likes
   * const { count } = await prisma.comment_likes.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends comment_likesDeleteManyArgs>(args?: Prisma.SelectSubset<T, comment_likesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Comment_likes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {comment_likesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Comment_likes
   * const comment_likes = await prisma.comment_likes.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends comment_likesUpdateManyArgs>(args: Prisma.SelectSubset<T, comment_likesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Comment_likes and returns the data updated in the database.
   * @param {comment_likesUpdateManyAndReturnArgs} args - Arguments to update many Comment_likes.
   * @example
   * // Update many Comment_likes
   * const comment_likes = await prisma.comment_likes.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Comment_likes and only return the `user_id`
   * const comment_likesWithUser_idOnly = await prisma.comment_likes.updateManyAndReturn({
   *   select: { user_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends comment_likesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, comment_likesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$comment_likesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Comment_likes.
   * @param {comment_likesUpsertArgs} args - Arguments to update or create a Comment_likes.
   * @example
   * // Update or create a Comment_likes
   * const comment_likes = await prisma.comment_likes.upsert({
   *   create: {
   *     // ... data to create a Comment_likes
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Comment_likes we want to update
   *   }
   * })
   */
  upsert<T extends comment_likesUpsertArgs>(args: Prisma.SelectSubset<T, comment_likesUpsertArgs<ExtArgs>>): Prisma.Prisma__comment_likesClient<runtime.Types.Result.GetResult<Prisma.$comment_likesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Comment_likes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {comment_likesCountArgs} args - Arguments to filter Comment_likes to count.
   * @example
   * // Count the number of Comment_likes
   * const count = await prisma.comment_likes.count({
   *   where: {
   *     // ... the filter for the Comment_likes we want to count
   *   }
   * })
  **/
  count<T extends comment_likesCountArgs>(
    args?: Prisma.Subset<T, comment_likesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Comment_likesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Comment_likes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Comment_likesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Comment_likesAggregateArgs>(args: Prisma.Subset<T, Comment_likesAggregateArgs>): Prisma.PrismaPromise<GetComment_likesAggregateType<T>>

  /**
   * Group by Comment_likes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {comment_likesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends comment_likesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: comment_likesGroupByArgs['orderBy'] }
      : { orderBy?: comment_likesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, comment_likesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetComment_likesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the comment_likes model
 */
readonly fields: comment_likesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for comment_likes.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__comment_likesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  comments<T extends Prisma.commentsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.commentsDefaultArgs<ExtArgs>>): Prisma.Prisma__commentsClient<runtime.Types.Result.GetResult<Prisma.$commentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.usersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.usersDefaultArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the comment_likes model
 */
export interface comment_likesFieldRefs {
  readonly user_id: Prisma.FieldRef<"comment_likes", 'String'>
  readonly comment_id: Prisma.FieldRef<"comment_likes", 'String'>
  readonly created_at: Prisma.FieldRef<"comment_likes", 'DateTime'>
}
    

// Custom InputTypes
/**
 * comment_likes findUnique
 */
export type comment_likesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the comment_likes
   */
  select?: Prisma.comment_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the comment_likes
   */
  omit?: Prisma.comment_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.comment_likesInclude<ExtArgs> | null
  /**
   * Filter, which comment_likes to fetch.
   */
  where: Prisma.comment_likesWhereUniqueInput
}

/**
 * comment_likes findUniqueOrThrow
 */
export type comment_likesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the comment_likes
   */
  select?: Prisma.comment_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the comment_likes
   */
  omit?: Prisma.comment_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.comment_likesInclude<ExtArgs> | null
  /**
   * Filter, which comment_likes to fetch.
   */
  where: Prisma.comment_likesWhereUniqueInput
}

/**
 * comment_likes findFirst
 */
export type comment_likesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the comment_likes
   */
  select?: Prisma.comment_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the comment_likes
   */
  omit?: Prisma.comment_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.comment_likesInclude<ExtArgs> | null
  /**
   * Filter, which comment_likes to fetch.
   */
  where?: Prisma.comment_likesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of comment_likes to fetch.
   */
  orderBy?: Prisma.comment_likesOrderByWithRelationInput | Prisma.comment_likesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for comment_likes.
   */
  cursor?: Prisma.comment_likesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` comment_likes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` comment_likes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of comment_likes.
   */
  distinct?: Prisma.Comment_likesScalarFieldEnum | Prisma.Comment_likesScalarFieldEnum[]
}

/**
 * comment_likes findFirstOrThrow
 */
export type comment_likesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the comment_likes
   */
  select?: Prisma.comment_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the comment_likes
   */
  omit?: Prisma.comment_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.comment_likesInclude<ExtArgs> | null
  /**
   * Filter, which comment_likes to fetch.
   */
  where?: Prisma.comment_likesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of comment_likes to fetch.
   */
  orderBy?: Prisma.comment_likesOrderByWithRelationInput | Prisma.comment_likesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for comment_likes.
   */
  cursor?: Prisma.comment_likesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` comment_likes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` comment_likes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of comment_likes.
   */
  distinct?: Prisma.Comment_likesScalarFieldEnum | Prisma.Comment_likesScalarFieldEnum[]
}

/**
 * comment_likes findMany
 */
export type comment_likesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the comment_likes
   */
  select?: Prisma.comment_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the comment_likes
   */
  omit?: Prisma.comment_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.comment_likesInclude<ExtArgs> | null
  /**
   * Filter, which comment_likes to fetch.
   */
  where?: Prisma.comment_likesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of comment_likes to fetch.
   */
  orderBy?: Prisma.comment_likesOrderByWithRelationInput | Prisma.comment_likesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing comment_likes.
   */
  cursor?: Prisma.comment_likesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` comment_likes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` comment_likes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of comment_likes.
   */
  distinct?: Prisma.Comment_likesScalarFieldEnum | Prisma.Comment_likesScalarFieldEnum[]
}

/**
 * comment_likes create
 */
export type comment_likesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the comment_likes
   */
  select?: Prisma.comment_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the comment_likes
   */
  omit?: Prisma.comment_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.comment_likesInclude<ExtArgs> | null
  /**
   * The data needed to create a comment_likes.
   */
  data: Prisma.XOR<Prisma.comment_likesCreateInput, Prisma.comment_likesUncheckedCreateInput>
}

/**
 * comment_likes createMany
 */
export type comment_likesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many comment_likes.
   */
  data: Prisma.comment_likesCreateManyInput | Prisma.comment_likesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * comment_likes createManyAndReturn
 */
export type comment_likesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the comment_likes
   */
  select?: Prisma.comment_likesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the comment_likes
   */
  omit?: Prisma.comment_likesOmit<ExtArgs> | null
  /**
   * The data used to create many comment_likes.
   */
  data: Prisma.comment_likesCreateManyInput | Prisma.comment_likesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.comment_likesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * comment_likes update
 */
export type comment_likesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the comment_likes
   */
  select?: Prisma.comment_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the comment_likes
   */
  omit?: Prisma.comment_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.comment_likesInclude<ExtArgs> | null
  /**
   * The data needed to update a comment_likes.
   */
  data: Prisma.XOR<Prisma.comment_likesUpdateInput, Prisma.comment_likesUncheckedUpdateInput>
  /**
   * Choose, which comment_likes to update.
   */
  where: Prisma.comment_likesWhereUniqueInput
}

/**
 * comment_likes updateMany
 */
export type comment_likesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update comment_likes.
   */
  data: Prisma.XOR<Prisma.comment_likesUpdateManyMutationInput, Prisma.comment_likesUncheckedUpdateManyInput>
  /**
   * Filter which comment_likes to update
   */
  where?: Prisma.comment_likesWhereInput
  /**
   * Limit how many comment_likes to update.
   */
  limit?: number
}

/**
 * comment_likes updateManyAndReturn
 */
export type comment_likesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the comment_likes
   */
  select?: Prisma.comment_likesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the comment_likes
   */
  omit?: Prisma.comment_likesOmit<ExtArgs> | null
  /**
   * The data used to update comment_likes.
   */
  data: Prisma.XOR<Prisma.comment_likesUpdateManyMutationInput, Prisma.comment_likesUncheckedUpdateManyInput>
  /**
   * Filter which comment_likes to update
   */
  where?: Prisma.comment_likesWhereInput
  /**
   * Limit how many comment_likes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.comment_likesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * comment_likes upsert
 */
export type comment_likesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the comment_likes
   */
  select?: Prisma.comment_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the comment_likes
   */
  omit?: Prisma.comment_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.comment_likesInclude<ExtArgs> | null
  /**
   * The filter to search for the comment_likes to update in case it exists.
   */
  where: Prisma.comment_likesWhereUniqueInput
  /**
   * In case the comment_likes found by the `where` argument doesn't exist, create a new comment_likes with this data.
   */
  create: Prisma.XOR<Prisma.comment_likesCreateInput, Prisma.comment_likesUncheckedCreateInput>
  /**
   * In case the comment_likes was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.comment_likesUpdateInput, Prisma.comment_likesUncheckedUpdateInput>
}

/**
 * comment_likes delete
 */
export type comment_likesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the comment_likes
   */
  select?: Prisma.comment_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the comment_likes
   */
  omit?: Prisma.comment_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.comment_likesInclude<ExtArgs> | null
  /**
   * Filter which comment_likes to delete.
   */
  where: Prisma.comment_likesWhereUniqueInput
}

/**
 * comment_likes deleteMany
 */
export type comment_likesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which comment_likes to delete
   */
  where?: Prisma.comment_likesWhereInput
  /**
   * Limit how many comment_likes to delete.
   */
  limit?: number
}

/**
 * comment_likes without action
 */
export type comment_likesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the comment_likes
   */
  select?: Prisma.comment_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the comment_likes
   */
  omit?: Prisma.comment_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.comment_likesInclude<ExtArgs> | null
}
