
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `device_tokens` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model device_tokens
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type device_tokensModel = runtime.Types.Result.DefaultSelection<Prisma.$device_tokensPayload>

export type AggregateDevice_tokens = {
  _count: Device_tokensCountAggregateOutputType | null
  _min: Device_tokensMinAggregateOutputType | null
  _max: Device_tokensMaxAggregateOutputType | null
}

export type Device_tokensMinAggregateOutputType = {
  token_id: string | null
  user_id: string | null
  token: string | null
  device_type: string | null
  app_version: string | null
  last_used: Date | null
  created_at: Date | null
}

export type Device_tokensMaxAggregateOutputType = {
  token_id: string | null
  user_id: string | null
  token: string | null
  device_type: string | null
  app_version: string | null
  last_used: Date | null
  created_at: Date | null
}

export type Device_tokensCountAggregateOutputType = {
  token_id: number
  user_id: number
  token: number
  device_type: number
  app_version: number
  last_used: number
  created_at: number
  _all: number
}


export type Device_tokensMinAggregateInputType = {
  token_id?: true
  user_id?: true
  token?: true
  device_type?: true
  app_version?: true
  last_used?: true
  created_at?: true
}

export type Device_tokensMaxAggregateInputType = {
  token_id?: true
  user_id?: true
  token?: true
  device_type?: true
  app_version?: true
  last_used?: true
  created_at?: true
}

export type Device_tokensCountAggregateInputType = {
  token_id?: true
  user_id?: true
  token?: true
  device_type?: true
  app_version?: true
  last_used?: true
  created_at?: true
  _all?: true
}

export type Device_tokensAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which device_tokens to aggregate.
   */
  where?: Prisma.device_tokensWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of device_tokens to fetch.
   */
  orderBy?: Prisma.device_tokensOrderByWithRelationInput | Prisma.device_tokensOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.device_tokensWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` device_tokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` device_tokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned device_tokens
  **/
  _count?: true | Device_tokensCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Device_tokensMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Device_tokensMaxAggregateInputType
}

export type GetDevice_tokensAggregateType<T extends Device_tokensAggregateArgs> = {
      [P in keyof T & keyof AggregateDevice_tokens]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDevice_tokens[P]>
    : Prisma.GetScalarType<T[P], AggregateDevice_tokens[P]>
}




export type device_tokensGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.device_tokensWhereInput
  orderBy?: Prisma.device_tokensOrderByWithAggregationInput | Prisma.device_tokensOrderByWithAggregationInput[]
  by: Prisma.Device_tokensScalarFieldEnum[] | Prisma.Device_tokensScalarFieldEnum
  having?: Prisma.device_tokensScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Device_tokensCountAggregateInputType | true
  _min?: Device_tokensMinAggregateInputType
  _max?: Device_tokensMaxAggregateInputType
}

export type Device_tokensGroupByOutputType = {
  token_id: string
  user_id: string
  token: string
  device_type: string
  app_version: string | null
  last_used: Date | null
  created_at: Date | null
  _count: Device_tokensCountAggregateOutputType | null
  _min: Device_tokensMinAggregateOutputType | null
  _max: Device_tokensMaxAggregateOutputType | null
}

export type GetDevice_tokensGroupByPayload<T extends device_tokensGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Device_tokensGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Device_tokensGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Device_tokensGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Device_tokensGroupByOutputType[P]>
      }
    >
  >



export type device_tokensWhereInput = {
  AND?: Prisma.device_tokensWhereInput | Prisma.device_tokensWhereInput[]
  OR?: Prisma.device_tokensWhereInput[]
  NOT?: Prisma.device_tokensWhereInput | Prisma.device_tokensWhereInput[]
  token_id?: Prisma.UuidFilter<"device_tokens"> | string
  user_id?: Prisma.UuidFilter<"device_tokens"> | string
  token?: Prisma.StringFilter<"device_tokens"> | string
  device_type?: Prisma.StringFilter<"device_tokens"> | string
  app_version?: Prisma.StringNullableFilter<"device_tokens"> | string | null
  last_used?: Prisma.DateTimeNullableFilter<"device_tokens"> | Date | string | null
  created_at?: Prisma.DateTimeNullableFilter<"device_tokens"> | Date | string | null
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}

export type device_tokensOrderByWithRelationInput = {
  token_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  device_type?: Prisma.SortOrder
  app_version?: Prisma.SortOrderInput | Prisma.SortOrder
  last_used?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  users?: Prisma.usersOrderByWithRelationInput
}

export type device_tokensWhereUniqueInput = Prisma.AtLeast<{
  token_id?: string
  user_id_token?: Prisma.device_tokensUser_idTokenCompoundUniqueInput
  AND?: Prisma.device_tokensWhereInput | Prisma.device_tokensWhereInput[]
  OR?: Prisma.device_tokensWhereInput[]
  NOT?: Prisma.device_tokensWhereInput | Prisma.device_tokensWhereInput[]
  user_id?: Prisma.UuidFilter<"device_tokens"> | string
  token?: Prisma.StringFilter<"device_tokens"> | string
  device_type?: Prisma.StringFilter<"device_tokens"> | string
  app_version?: Prisma.StringNullableFilter<"device_tokens"> | string | null
  last_used?: Prisma.DateTimeNullableFilter<"device_tokens"> | Date | string | null
  created_at?: Prisma.DateTimeNullableFilter<"device_tokens"> | Date | string | null
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}, "token_id" | "user_id_token">

export type device_tokensOrderByWithAggregationInput = {
  token_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  device_type?: Prisma.SortOrder
  app_version?: Prisma.SortOrderInput | Prisma.SortOrder
  last_used?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.device_tokensCountOrderByAggregateInput
  _max?: Prisma.device_tokensMaxOrderByAggregateInput
  _min?: Prisma.device_tokensMinOrderByAggregateInput
}

export type device_tokensScalarWhereWithAggregatesInput = {
  AND?: Prisma.device_tokensScalarWhereWithAggregatesInput | Prisma.device_tokensScalarWhereWithAggregatesInput[]
  OR?: Prisma.device_tokensScalarWhereWithAggregatesInput[]
  NOT?: Prisma.device_tokensScalarWhereWithAggregatesInput | Prisma.device_tokensScalarWhereWithAggregatesInput[]
  token_id?: Prisma.UuidWithAggregatesFilter<"device_tokens"> | string
  user_id?: Prisma.UuidWithAggregatesFilter<"device_tokens"> | string
  token?: Prisma.StringWithAggregatesFilter<"device_tokens"> | string
  device_type?: Prisma.StringWithAggregatesFilter<"device_tokens"> | string
  app_version?: Prisma.StringNullableWithAggregatesFilter<"device_tokens"> | string | null
  last_used?: Prisma.DateTimeNullableWithAggregatesFilter<"device_tokens"> | Date | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"device_tokens"> | Date | string | null
}

export type device_tokensCreateInput = {
  token_id?: string
  token: string
  device_type: string
  app_version?: string | null
  last_used?: Date | string | null
  created_at?: Date | string | null
  users: Prisma.usersCreateNestedOneWithoutDevice_tokensInput
}

export type device_tokensUncheckedCreateInput = {
  token_id?: string
  user_id: string
  token: string
  device_type: string
  app_version?: string | null
  last_used?: Date | string | null
  created_at?: Date | string | null
}

export type device_tokensUpdateInput = {
  token_id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  device_type?: Prisma.StringFieldUpdateOperationsInput | string
  app_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_used?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneRequiredWithoutDevice_tokensNestedInput
}

export type device_tokensUncheckedUpdateInput = {
  token_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  device_type?: Prisma.StringFieldUpdateOperationsInput | string
  app_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_used?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type device_tokensCreateManyInput = {
  token_id?: string
  user_id: string
  token: string
  device_type: string
  app_version?: string | null
  last_used?: Date | string | null
  created_at?: Date | string | null
}

export type device_tokensUpdateManyMutationInput = {
  token_id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  device_type?: Prisma.StringFieldUpdateOperationsInput | string
  app_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_used?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type device_tokensUncheckedUpdateManyInput = {
  token_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  device_type?: Prisma.StringFieldUpdateOperationsInput | string
  app_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_used?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type device_tokensUser_idTokenCompoundUniqueInput = {
  user_id: string
  token: string
}

export type device_tokensCountOrderByAggregateInput = {
  token_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  device_type?: Prisma.SortOrder
  app_version?: Prisma.SortOrder
  last_used?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type device_tokensMaxOrderByAggregateInput = {
  token_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  device_type?: Prisma.SortOrder
  app_version?: Prisma.SortOrder
  last_used?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type device_tokensMinOrderByAggregateInput = {
  token_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  device_type?: Prisma.SortOrder
  app_version?: Prisma.SortOrder
  last_used?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type Device_tokensListRelationFilter = {
  every?: Prisma.device_tokensWhereInput
  some?: Prisma.device_tokensWhereInput
  none?: Prisma.device_tokensWhereInput
}

export type device_tokensOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type device_tokensCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.device_tokensCreateWithoutUsersInput, Prisma.device_tokensUncheckedCreateWithoutUsersInput> | Prisma.device_tokensCreateWithoutUsersInput[] | Prisma.device_tokensUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.device_tokensCreateOrConnectWithoutUsersInput | Prisma.device_tokensCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.device_tokensCreateManyUsersInputEnvelope
  connect?: Prisma.device_tokensWhereUniqueInput | Prisma.device_tokensWhereUniqueInput[]
}

export type device_tokensUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.device_tokensCreateWithoutUsersInput, Prisma.device_tokensUncheckedCreateWithoutUsersInput> | Prisma.device_tokensCreateWithoutUsersInput[] | Prisma.device_tokensUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.device_tokensCreateOrConnectWithoutUsersInput | Prisma.device_tokensCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.device_tokensCreateManyUsersInputEnvelope
  connect?: Prisma.device_tokensWhereUniqueInput | Prisma.device_tokensWhereUniqueInput[]
}

export type device_tokensUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.device_tokensCreateWithoutUsersInput, Prisma.device_tokensUncheckedCreateWithoutUsersInput> | Prisma.device_tokensCreateWithoutUsersInput[] | Prisma.device_tokensUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.device_tokensCreateOrConnectWithoutUsersInput | Prisma.device_tokensCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.device_tokensUpsertWithWhereUniqueWithoutUsersInput | Prisma.device_tokensUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.device_tokensCreateManyUsersInputEnvelope
  set?: Prisma.device_tokensWhereUniqueInput | Prisma.device_tokensWhereUniqueInput[]
  disconnect?: Prisma.device_tokensWhereUniqueInput | Prisma.device_tokensWhereUniqueInput[]
  delete?: Prisma.device_tokensWhereUniqueInput | Prisma.device_tokensWhereUniqueInput[]
  connect?: Prisma.device_tokensWhereUniqueInput | Prisma.device_tokensWhereUniqueInput[]
  update?: Prisma.device_tokensUpdateWithWhereUniqueWithoutUsersInput | Prisma.device_tokensUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.device_tokensUpdateManyWithWhereWithoutUsersInput | Prisma.device_tokensUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.device_tokensScalarWhereInput | Prisma.device_tokensScalarWhereInput[]
}

export type device_tokensUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.device_tokensCreateWithoutUsersInput, Prisma.device_tokensUncheckedCreateWithoutUsersInput> | Prisma.device_tokensCreateWithoutUsersInput[] | Prisma.device_tokensUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.device_tokensCreateOrConnectWithoutUsersInput | Prisma.device_tokensCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.device_tokensUpsertWithWhereUniqueWithoutUsersInput | Prisma.device_tokensUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.device_tokensCreateManyUsersInputEnvelope
  set?: Prisma.device_tokensWhereUniqueInput | Prisma.device_tokensWhereUniqueInput[]
  disconnect?: Prisma.device_tokensWhereUniqueInput | Prisma.device_tokensWhereUniqueInput[]
  delete?: Prisma.device_tokensWhereUniqueInput | Prisma.device_tokensWhereUniqueInput[]
  connect?: Prisma.device_tokensWhereUniqueInput | Prisma.device_tokensWhereUniqueInput[]
  update?: Prisma.device_tokensUpdateWithWhereUniqueWithoutUsersInput | Prisma.device_tokensUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.device_tokensUpdateManyWithWhereWithoutUsersInput | Prisma.device_tokensUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.device_tokensScalarWhereInput | Prisma.device_tokensScalarWhereInput[]
}

export type device_tokensCreateWithoutUsersInput = {
  token_id?: string
  token: string
  device_type: string
  app_version?: string | null
  last_used?: Date | string | null
  created_at?: Date | string | null
}

export type device_tokensUncheckedCreateWithoutUsersInput = {
  token_id?: string
  token: string
  device_type: string
  app_version?: string | null
  last_used?: Date | string | null
  created_at?: Date | string | null
}

export type device_tokensCreateOrConnectWithoutUsersInput = {
  where: Prisma.device_tokensWhereUniqueInput
  create: Prisma.XOR<Prisma.device_tokensCreateWithoutUsersInput, Prisma.device_tokensUncheckedCreateWithoutUsersInput>
}

export type device_tokensCreateManyUsersInputEnvelope = {
  data: Prisma.device_tokensCreateManyUsersInput | Prisma.device_tokensCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type device_tokensUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.device_tokensWhereUniqueInput
  update: Prisma.XOR<Prisma.device_tokensUpdateWithoutUsersInput, Prisma.device_tokensUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.device_tokensCreateWithoutUsersInput, Prisma.device_tokensUncheckedCreateWithoutUsersInput>
}

export type device_tokensUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.device_tokensWhereUniqueInput
  data: Prisma.XOR<Prisma.device_tokensUpdateWithoutUsersInput, Prisma.device_tokensUncheckedUpdateWithoutUsersInput>
}

export type device_tokensUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.device_tokensScalarWhereInput
  data: Prisma.XOR<Prisma.device_tokensUpdateManyMutationInput, Prisma.device_tokensUncheckedUpdateManyWithoutUsersInput>
}

export type device_tokensScalarWhereInput = {
  AND?: Prisma.device_tokensScalarWhereInput | Prisma.device_tokensScalarWhereInput[]
  OR?: Prisma.device_tokensScalarWhereInput[]
  NOT?: Prisma.device_tokensScalarWhereInput | Prisma.device_tokensScalarWhereInput[]
  token_id?: Prisma.UuidFilter<"device_tokens"> | string
  user_id?: Prisma.UuidFilter<"device_tokens"> | string
  token?: Prisma.StringFilter<"device_tokens"> | string
  device_type?: Prisma.StringFilter<"device_tokens"> | string
  app_version?: Prisma.StringNullableFilter<"device_tokens"> | string | null
  last_used?: Prisma.DateTimeNullableFilter<"device_tokens"> | Date | string | null
  created_at?: Prisma.DateTimeNullableFilter<"device_tokens"> | Date | string | null
}

export type device_tokensCreateManyUsersInput = {
  token_id?: string
  token: string
  device_type: string
  app_version?: string | null
  last_used?: Date | string | null
  created_at?: Date | string | null
}

export type device_tokensUpdateWithoutUsersInput = {
  token_id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  device_type?: Prisma.StringFieldUpdateOperationsInput | string
  app_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_used?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type device_tokensUncheckedUpdateWithoutUsersInput = {
  token_id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  device_type?: Prisma.StringFieldUpdateOperationsInput | string
  app_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_used?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type device_tokensUncheckedUpdateManyWithoutUsersInput = {
  token_id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  device_type?: Prisma.StringFieldUpdateOperationsInput | string
  app_version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  last_used?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type device_tokensSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  token_id?: boolean
  user_id?: boolean
  token?: boolean
  device_type?: boolean
  app_version?: boolean
  last_used?: boolean
  created_at?: boolean
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["device_tokens"]>

export type device_tokensSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  token_id?: boolean
  user_id?: boolean
  token?: boolean
  device_type?: boolean
  app_version?: boolean
  last_used?: boolean
  created_at?: boolean
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["device_tokens"]>

export type device_tokensSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  token_id?: boolean
  user_id?: boolean
  token?: boolean
  device_type?: boolean
  app_version?: boolean
  last_used?: boolean
  created_at?: boolean
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["device_tokens"]>

export type device_tokensSelectScalar = {
  token_id?: boolean
  user_id?: boolean
  token?: boolean
  device_type?: boolean
  app_version?: boolean
  last_used?: boolean
  created_at?: boolean
}

export type device_tokensOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"token_id" | "user_id" | "token" | "device_type" | "app_version" | "last_used" | "created_at", ExtArgs["result"]["device_tokens"]>
export type device_tokensInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type device_tokensIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type device_tokensIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}

export type $device_tokensPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "device_tokens"
  objects: {
    users: Prisma.$usersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    token_id: string
    user_id: string
    token: string
    device_type: string
    app_version: string | null
    last_used: Date | null
    created_at: Date | null
  }, ExtArgs["result"]["device_tokens"]>
  composites: {}
}

export type device_tokensGetPayload<S extends boolean | null | undefined | device_tokensDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$device_tokensPayload, S>

export type device_tokensCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<device_tokensFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Device_tokensCountAggregateInputType | true
  }

export interface device_tokensDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['device_tokens'], meta: { name: 'device_tokens' } }
  /**
   * Find zero or one Device_tokens that matches the filter.
   * @param {device_tokensFindUniqueArgs} args - Arguments to find a Device_tokens
   * @example
   * // Get one Device_tokens
   * const device_tokens = await prisma.device_tokens.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends device_tokensFindUniqueArgs>(args: Prisma.SelectSubset<T, device_tokensFindUniqueArgs<ExtArgs>>): Prisma.Prisma__device_tokensClient<runtime.Types.Result.GetResult<Prisma.$device_tokensPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Device_tokens that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {device_tokensFindUniqueOrThrowArgs} args - Arguments to find a Device_tokens
   * @example
   * // Get one Device_tokens
   * const device_tokens = await prisma.device_tokens.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends device_tokensFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, device_tokensFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__device_tokensClient<runtime.Types.Result.GetResult<Prisma.$device_tokensPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Device_tokens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {device_tokensFindFirstArgs} args - Arguments to find a Device_tokens
   * @example
   * // Get one Device_tokens
   * const device_tokens = await prisma.device_tokens.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends device_tokensFindFirstArgs>(args?: Prisma.SelectSubset<T, device_tokensFindFirstArgs<ExtArgs>>): Prisma.Prisma__device_tokensClient<runtime.Types.Result.GetResult<Prisma.$device_tokensPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Device_tokens that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {device_tokensFindFirstOrThrowArgs} args - Arguments to find a Device_tokens
   * @example
   * // Get one Device_tokens
   * const device_tokens = await prisma.device_tokens.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends device_tokensFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, device_tokensFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__device_tokensClient<runtime.Types.Result.GetResult<Prisma.$device_tokensPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Device_tokens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {device_tokensFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Device_tokens
   * const device_tokens = await prisma.device_tokens.findMany()
   * 
   * // Get first 10 Device_tokens
   * const device_tokens = await prisma.device_tokens.findMany({ take: 10 })
   * 
   * // Only select the `token_id`
   * const device_tokensWithToken_idOnly = await prisma.device_tokens.findMany({ select: { token_id: true } })
   * 
   */
  findMany<T extends device_tokensFindManyArgs>(args?: Prisma.SelectSubset<T, device_tokensFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$device_tokensPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Device_tokens.
   * @param {device_tokensCreateArgs} args - Arguments to create a Device_tokens.
   * @example
   * // Create one Device_tokens
   * const Device_tokens = await prisma.device_tokens.create({
   *   data: {
   *     // ... data to create a Device_tokens
   *   }
   * })
   * 
   */
  create<T extends device_tokensCreateArgs>(args: Prisma.SelectSubset<T, device_tokensCreateArgs<ExtArgs>>): Prisma.Prisma__device_tokensClient<runtime.Types.Result.GetResult<Prisma.$device_tokensPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Device_tokens.
   * @param {device_tokensCreateManyArgs} args - Arguments to create many Device_tokens.
   * @example
   * // Create many Device_tokens
   * const device_tokens = await prisma.device_tokens.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends device_tokensCreateManyArgs>(args?: Prisma.SelectSubset<T, device_tokensCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Device_tokens and returns the data saved in the database.
   * @param {device_tokensCreateManyAndReturnArgs} args - Arguments to create many Device_tokens.
   * @example
   * // Create many Device_tokens
   * const device_tokens = await prisma.device_tokens.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Device_tokens and only return the `token_id`
   * const device_tokensWithToken_idOnly = await prisma.device_tokens.createManyAndReturn({
   *   select: { token_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends device_tokensCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, device_tokensCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$device_tokensPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Device_tokens.
   * @param {device_tokensDeleteArgs} args - Arguments to delete one Device_tokens.
   * @example
   * // Delete one Device_tokens
   * const Device_tokens = await prisma.device_tokens.delete({
   *   where: {
   *     // ... filter to delete one Device_tokens
   *   }
   * })
   * 
   */
  delete<T extends device_tokensDeleteArgs>(args: Prisma.SelectSubset<T, device_tokensDeleteArgs<ExtArgs>>): Prisma.Prisma__device_tokensClient<runtime.Types.Result.GetResult<Prisma.$device_tokensPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Device_tokens.
   * @param {device_tokensUpdateArgs} args - Arguments to update one Device_tokens.
   * @example
   * // Update one Device_tokens
   * const device_tokens = await prisma.device_tokens.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends device_tokensUpdateArgs>(args: Prisma.SelectSubset<T, device_tokensUpdateArgs<ExtArgs>>): Prisma.Prisma__device_tokensClient<runtime.Types.Result.GetResult<Prisma.$device_tokensPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Device_tokens.
   * @param {device_tokensDeleteManyArgs} args - Arguments to filter Device_tokens to delete.
   * @example
   * // Delete a few Device_tokens
   * const { count } = await prisma.device_tokens.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends device_tokensDeleteManyArgs>(args?: Prisma.SelectSubset<T, device_tokensDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Device_tokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {device_tokensUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Device_tokens
   * const device_tokens = await prisma.device_tokens.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends device_tokensUpdateManyArgs>(args: Prisma.SelectSubset<T, device_tokensUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Device_tokens and returns the data updated in the database.
   * @param {device_tokensUpdateManyAndReturnArgs} args - Arguments to update many Device_tokens.
   * @example
   * // Update many Device_tokens
   * const device_tokens = await prisma.device_tokens.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Device_tokens and only return the `token_id`
   * const device_tokensWithToken_idOnly = await prisma.device_tokens.updateManyAndReturn({
   *   select: { token_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends device_tokensUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, device_tokensUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$device_tokensPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Device_tokens.
   * @param {device_tokensUpsertArgs} args - Arguments to update or create a Device_tokens.
   * @example
   * // Update or create a Device_tokens
   * const device_tokens = await prisma.device_tokens.upsert({
   *   create: {
   *     // ... data to create a Device_tokens
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Device_tokens we want to update
   *   }
   * })
   */
  upsert<T extends device_tokensUpsertArgs>(args: Prisma.SelectSubset<T, device_tokensUpsertArgs<ExtArgs>>): Prisma.Prisma__device_tokensClient<runtime.Types.Result.GetResult<Prisma.$device_tokensPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Device_tokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {device_tokensCountArgs} args - Arguments to filter Device_tokens to count.
   * @example
   * // Count the number of Device_tokens
   * const count = await prisma.device_tokens.count({
   *   where: {
   *     // ... the filter for the Device_tokens we want to count
   *   }
   * })
  **/
  count<T extends device_tokensCountArgs>(
    args?: Prisma.Subset<T, device_tokensCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Device_tokensCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Device_tokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Device_tokensAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Device_tokensAggregateArgs>(args: Prisma.Subset<T, Device_tokensAggregateArgs>): Prisma.PrismaPromise<GetDevice_tokensAggregateType<T>>

  /**
   * Group by Device_tokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {device_tokensGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends device_tokensGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: device_tokensGroupByArgs['orderBy'] }
      : { orderBy?: device_tokensGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, device_tokensGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDevice_tokensGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the device_tokens model
 */
readonly fields: device_tokensFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for device_tokens.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__device_tokensClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.usersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.usersDefaultArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the device_tokens model
 */
export interface device_tokensFieldRefs {
  readonly token_id: Prisma.FieldRef<"device_tokens", 'String'>
  readonly user_id: Prisma.FieldRef<"device_tokens", 'String'>
  readonly token: Prisma.FieldRef<"device_tokens", 'String'>
  readonly device_type: Prisma.FieldRef<"device_tokens", 'String'>
  readonly app_version: Prisma.FieldRef<"device_tokens", 'String'>
  readonly last_used: Prisma.FieldRef<"device_tokens", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"device_tokens", 'DateTime'>
}
    

// Custom InputTypes
/**
 * device_tokens findUnique
 */
export type device_tokensFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the device_tokens
   */
  select?: Prisma.device_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the device_tokens
   */
  omit?: Prisma.device_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.device_tokensInclude<ExtArgs> | null
  /**
   * Filter, which device_tokens to fetch.
   */
  where: Prisma.device_tokensWhereUniqueInput
}

/**
 * device_tokens findUniqueOrThrow
 */
export type device_tokensFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the device_tokens
   */
  select?: Prisma.device_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the device_tokens
   */
  omit?: Prisma.device_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.device_tokensInclude<ExtArgs> | null
  /**
   * Filter, which device_tokens to fetch.
   */
  where: Prisma.device_tokensWhereUniqueInput
}

/**
 * device_tokens findFirst
 */
export type device_tokensFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the device_tokens
   */
  select?: Prisma.device_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the device_tokens
   */
  omit?: Prisma.device_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.device_tokensInclude<ExtArgs> | null
  /**
   * Filter, which device_tokens to fetch.
   */
  where?: Prisma.device_tokensWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of device_tokens to fetch.
   */
  orderBy?: Prisma.device_tokensOrderByWithRelationInput | Prisma.device_tokensOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for device_tokens.
   */
  cursor?: Prisma.device_tokensWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` device_tokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` device_tokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of device_tokens.
   */
  distinct?: Prisma.Device_tokensScalarFieldEnum | Prisma.Device_tokensScalarFieldEnum[]
}

/**
 * device_tokens findFirstOrThrow
 */
export type device_tokensFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the device_tokens
   */
  select?: Prisma.device_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the device_tokens
   */
  omit?: Prisma.device_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.device_tokensInclude<ExtArgs> | null
  /**
   * Filter, which device_tokens to fetch.
   */
  where?: Prisma.device_tokensWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of device_tokens to fetch.
   */
  orderBy?: Prisma.device_tokensOrderByWithRelationInput | Prisma.device_tokensOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for device_tokens.
   */
  cursor?: Prisma.device_tokensWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` device_tokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` device_tokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of device_tokens.
   */
  distinct?: Prisma.Device_tokensScalarFieldEnum | Prisma.Device_tokensScalarFieldEnum[]
}

/**
 * device_tokens findMany
 */
export type device_tokensFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the device_tokens
   */
  select?: Prisma.device_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the device_tokens
   */
  omit?: Prisma.device_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.device_tokensInclude<ExtArgs> | null
  /**
   * Filter, which device_tokens to fetch.
   */
  where?: Prisma.device_tokensWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of device_tokens to fetch.
   */
  orderBy?: Prisma.device_tokensOrderByWithRelationInput | Prisma.device_tokensOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing device_tokens.
   */
  cursor?: Prisma.device_tokensWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` device_tokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` device_tokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of device_tokens.
   */
  distinct?: Prisma.Device_tokensScalarFieldEnum | Prisma.Device_tokensScalarFieldEnum[]
}

/**
 * device_tokens create
 */
export type device_tokensCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the device_tokens
   */
  select?: Prisma.device_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the device_tokens
   */
  omit?: Prisma.device_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.device_tokensInclude<ExtArgs> | null
  /**
   * The data needed to create a device_tokens.
   */
  data: Prisma.XOR<Prisma.device_tokensCreateInput, Prisma.device_tokensUncheckedCreateInput>
}

/**
 * device_tokens createMany
 */
export type device_tokensCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many device_tokens.
   */
  data: Prisma.device_tokensCreateManyInput | Prisma.device_tokensCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * device_tokens createManyAndReturn
 */
export type device_tokensCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the device_tokens
   */
  select?: Prisma.device_tokensSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the device_tokens
   */
  omit?: Prisma.device_tokensOmit<ExtArgs> | null
  /**
   * The data used to create many device_tokens.
   */
  data: Prisma.device_tokensCreateManyInput | Prisma.device_tokensCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.device_tokensIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * device_tokens update
 */
export type device_tokensUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the device_tokens
   */
  select?: Prisma.device_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the device_tokens
   */
  omit?: Prisma.device_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.device_tokensInclude<ExtArgs> | null
  /**
   * The data needed to update a device_tokens.
   */
  data: Prisma.XOR<Prisma.device_tokensUpdateInput, Prisma.device_tokensUncheckedUpdateInput>
  /**
   * Choose, which device_tokens to update.
   */
  where: Prisma.device_tokensWhereUniqueInput
}

/**
 * device_tokens updateMany
 */
export type device_tokensUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update device_tokens.
   */
  data: Prisma.XOR<Prisma.device_tokensUpdateManyMutationInput, Prisma.device_tokensUncheckedUpdateManyInput>
  /**
   * Filter which device_tokens to update
   */
  where?: Prisma.device_tokensWhereInput
  /**
   * Limit how many device_tokens to update.
   */
  limit?: number
}

/**
 * device_tokens updateManyAndReturn
 */
export type device_tokensUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the device_tokens
   */
  select?: Prisma.device_tokensSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the device_tokens
   */
  omit?: Prisma.device_tokensOmit<ExtArgs> | null
  /**
   * The data used to update device_tokens.
   */
  data: Prisma.XOR<Prisma.device_tokensUpdateManyMutationInput, Prisma.device_tokensUncheckedUpdateManyInput>
  /**
   * Filter which device_tokens to update
   */
  where?: Prisma.device_tokensWhereInput
  /**
   * Limit how many device_tokens to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.device_tokensIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * device_tokens upsert
 */
export type device_tokensUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the device_tokens
   */
  select?: Prisma.device_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the device_tokens
   */
  omit?: Prisma.device_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.device_tokensInclude<ExtArgs> | null
  /**
   * The filter to search for the device_tokens to update in case it exists.
   */
  where: Prisma.device_tokensWhereUniqueInput
  /**
   * In case the device_tokens found by the `where` argument doesn't exist, create a new device_tokens with this data.
   */
  create: Prisma.XOR<Prisma.device_tokensCreateInput, Prisma.device_tokensUncheckedCreateInput>
  /**
   * In case the device_tokens was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.device_tokensUpdateInput, Prisma.device_tokensUncheckedUpdateInput>
}

/**
 * device_tokens delete
 */
export type device_tokensDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the device_tokens
   */
  select?: Prisma.device_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the device_tokens
   */
  omit?: Prisma.device_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.device_tokensInclude<ExtArgs> | null
  /**
   * Filter which device_tokens to delete.
   */
  where: Prisma.device_tokensWhereUniqueInput
}

/**
 * device_tokens deleteMany
 */
export type device_tokensDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which device_tokens to delete
   */
  where?: Prisma.device_tokensWhereInput
  /**
   * Limit how many device_tokens to delete.
   */
  limit?: number
}

/**
 * device_tokens without action
 */
export type device_tokensDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the device_tokens
   */
  select?: Prisma.device_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the device_tokens
   */
  omit?: Prisma.device_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.device_tokensInclude<ExtArgs> | null
}
