
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `mentions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model mentions
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type mentionsModel = runtime.Types.Result.DefaultSelection<Prisma.$mentionsPayload>

export type AggregateMentions = {
  _count: MentionsCountAggregateOutputType | null
  _min: MentionsMinAggregateOutputType | null
  _max: MentionsMaxAggregateOutputType | null
}

export type MentionsMinAggregateOutputType = {
  mention_id: string | null
  mentioned_user_id: string | null
  post_id: string | null
  comment_id: string | null
  created_at: Date | null
}

export type MentionsMaxAggregateOutputType = {
  mention_id: string | null
  mentioned_user_id: string | null
  post_id: string | null
  comment_id: string | null
  created_at: Date | null
}

export type MentionsCountAggregateOutputType = {
  mention_id: number
  mentioned_user_id: number
  post_id: number
  comment_id: number
  created_at: number
  _all: number
}


export type MentionsMinAggregateInputType = {
  mention_id?: true
  mentioned_user_id?: true
  post_id?: true
  comment_id?: true
  created_at?: true
}

export type MentionsMaxAggregateInputType = {
  mention_id?: true
  mentioned_user_id?: true
  post_id?: true
  comment_id?: true
  created_at?: true
}

export type MentionsCountAggregateInputType = {
  mention_id?: true
  mentioned_user_id?: true
  post_id?: true
  comment_id?: true
  created_at?: true
  _all?: true
}

export type MentionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which mentions to aggregate.
   */
  where?: Prisma.mentionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of mentions to fetch.
   */
  orderBy?: Prisma.mentionsOrderByWithRelationInput | Prisma.mentionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.mentionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` mentions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` mentions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned mentions
  **/
  _count?: true | MentionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MentionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MentionsMaxAggregateInputType
}

export type GetMentionsAggregateType<T extends MentionsAggregateArgs> = {
      [P in keyof T & keyof AggregateMentions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMentions[P]>
    : Prisma.GetScalarType<T[P], AggregateMentions[P]>
}




export type mentionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.mentionsWhereInput
  orderBy?: Prisma.mentionsOrderByWithAggregationInput | Prisma.mentionsOrderByWithAggregationInput[]
  by: Prisma.MentionsScalarFieldEnum[] | Prisma.MentionsScalarFieldEnum
  having?: Prisma.mentionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MentionsCountAggregateInputType | true
  _min?: MentionsMinAggregateInputType
  _max?: MentionsMaxAggregateInputType
}

export type MentionsGroupByOutputType = {
  mention_id: string
  mentioned_user_id: string
  post_id: string | null
  comment_id: string | null
  created_at: Date | null
  _count: MentionsCountAggregateOutputType | null
  _min: MentionsMinAggregateOutputType | null
  _max: MentionsMaxAggregateOutputType | null
}

export type GetMentionsGroupByPayload<T extends mentionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MentionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MentionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MentionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MentionsGroupByOutputType[P]>
      }
    >
  >



export type mentionsWhereInput = {
  AND?: Prisma.mentionsWhereInput | Prisma.mentionsWhereInput[]
  OR?: Prisma.mentionsWhereInput[]
  NOT?: Prisma.mentionsWhereInput | Prisma.mentionsWhereInput[]
  mention_id?: Prisma.UuidFilter<"mentions"> | string
  mentioned_user_id?: Prisma.UuidFilter<"mentions"> | string
  post_id?: Prisma.UuidNullableFilter<"mentions"> | string | null
  comment_id?: Prisma.UuidNullableFilter<"mentions"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"mentions"> | Date | string | null
  comments?: Prisma.XOR<Prisma.CommentsNullableScalarRelationFilter, Prisma.commentsWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
  posts?: Prisma.XOR<Prisma.PostsNullableScalarRelationFilter, Prisma.postsWhereInput> | null
}

export type mentionsOrderByWithRelationInput = {
  mention_id?: Prisma.SortOrder
  mentioned_user_id?: Prisma.SortOrder
  post_id?: Prisma.SortOrderInput | Prisma.SortOrder
  comment_id?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  comments?: Prisma.commentsOrderByWithRelationInput
  users?: Prisma.usersOrderByWithRelationInput
  posts?: Prisma.postsOrderByWithRelationInput
}

export type mentionsWhereUniqueInput = Prisma.AtLeast<{
  mention_id?: string
  AND?: Prisma.mentionsWhereInput | Prisma.mentionsWhereInput[]
  OR?: Prisma.mentionsWhereInput[]
  NOT?: Prisma.mentionsWhereInput | Prisma.mentionsWhereInput[]
  mentioned_user_id?: Prisma.UuidFilter<"mentions"> | string
  post_id?: Prisma.UuidNullableFilter<"mentions"> | string | null
  comment_id?: Prisma.UuidNullableFilter<"mentions"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"mentions"> | Date | string | null
  comments?: Prisma.XOR<Prisma.CommentsNullableScalarRelationFilter, Prisma.commentsWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
  posts?: Prisma.XOR<Prisma.PostsNullableScalarRelationFilter, Prisma.postsWhereInput> | null
}, "mention_id">

export type mentionsOrderByWithAggregationInput = {
  mention_id?: Prisma.SortOrder
  mentioned_user_id?: Prisma.SortOrder
  post_id?: Prisma.SortOrderInput | Prisma.SortOrder
  comment_id?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.mentionsCountOrderByAggregateInput
  _max?: Prisma.mentionsMaxOrderByAggregateInput
  _min?: Prisma.mentionsMinOrderByAggregateInput
}

export type mentionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.mentionsScalarWhereWithAggregatesInput | Prisma.mentionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.mentionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.mentionsScalarWhereWithAggregatesInput | Prisma.mentionsScalarWhereWithAggregatesInput[]
  mention_id?: Prisma.UuidWithAggregatesFilter<"mentions"> | string
  mentioned_user_id?: Prisma.UuidWithAggregatesFilter<"mentions"> | string
  post_id?: Prisma.UuidNullableWithAggregatesFilter<"mentions"> | string | null
  comment_id?: Prisma.UuidNullableWithAggregatesFilter<"mentions"> | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"mentions"> | Date | string | null
}

export type mentionsCreateInput = {
  mention_id?: string
  created_at?: Date | string | null
  comments?: Prisma.commentsCreateNestedOneWithoutMentionsInput
  users: Prisma.usersCreateNestedOneWithoutMentionsInput
  posts?: Prisma.postsCreateNestedOneWithoutMentionsInput
}

export type mentionsUncheckedCreateInput = {
  mention_id?: string
  mentioned_user_id: string
  post_id?: string | null
  comment_id?: string | null
  created_at?: Date | string | null
}

export type mentionsUpdateInput = {
  mention_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  comments?: Prisma.commentsUpdateOneWithoutMentionsNestedInput
  users?: Prisma.usersUpdateOneRequiredWithoutMentionsNestedInput
  posts?: Prisma.postsUpdateOneWithoutMentionsNestedInput
}

export type mentionsUncheckedUpdateInput = {
  mention_id?: Prisma.StringFieldUpdateOperationsInput | string
  mentioned_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  post_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  comment_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type mentionsCreateManyInput = {
  mention_id?: string
  mentioned_user_id: string
  post_id?: string | null
  comment_id?: string | null
  created_at?: Date | string | null
}

export type mentionsUpdateManyMutationInput = {
  mention_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type mentionsUncheckedUpdateManyInput = {
  mention_id?: Prisma.StringFieldUpdateOperationsInput | string
  mentioned_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  post_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  comment_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type MentionsListRelationFilter = {
  every?: Prisma.mentionsWhereInput
  some?: Prisma.mentionsWhereInput
  none?: Prisma.mentionsWhereInput
}

export type mentionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type mentionsCountOrderByAggregateInput = {
  mention_id?: Prisma.SortOrder
  mentioned_user_id?: Prisma.SortOrder
  post_id?: Prisma.SortOrder
  comment_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type mentionsMaxOrderByAggregateInput = {
  mention_id?: Prisma.SortOrder
  mentioned_user_id?: Prisma.SortOrder
  post_id?: Prisma.SortOrder
  comment_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type mentionsMinOrderByAggregateInput = {
  mention_id?: Prisma.SortOrder
  mentioned_user_id?: Prisma.SortOrder
  post_id?: Prisma.SortOrder
  comment_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type mentionsCreateNestedManyWithoutCommentsInput = {
  create?: Prisma.XOR<Prisma.mentionsCreateWithoutCommentsInput, Prisma.mentionsUncheckedCreateWithoutCommentsInput> | Prisma.mentionsCreateWithoutCommentsInput[] | Prisma.mentionsUncheckedCreateWithoutCommentsInput[]
  connectOrCreate?: Prisma.mentionsCreateOrConnectWithoutCommentsInput | Prisma.mentionsCreateOrConnectWithoutCommentsInput[]
  createMany?: Prisma.mentionsCreateManyCommentsInputEnvelope
  connect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
}

export type mentionsUncheckedCreateNestedManyWithoutCommentsInput = {
  create?: Prisma.XOR<Prisma.mentionsCreateWithoutCommentsInput, Prisma.mentionsUncheckedCreateWithoutCommentsInput> | Prisma.mentionsCreateWithoutCommentsInput[] | Prisma.mentionsUncheckedCreateWithoutCommentsInput[]
  connectOrCreate?: Prisma.mentionsCreateOrConnectWithoutCommentsInput | Prisma.mentionsCreateOrConnectWithoutCommentsInput[]
  createMany?: Prisma.mentionsCreateManyCommentsInputEnvelope
  connect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
}

export type mentionsUpdateManyWithoutCommentsNestedInput = {
  create?: Prisma.XOR<Prisma.mentionsCreateWithoutCommentsInput, Prisma.mentionsUncheckedCreateWithoutCommentsInput> | Prisma.mentionsCreateWithoutCommentsInput[] | Prisma.mentionsUncheckedCreateWithoutCommentsInput[]
  connectOrCreate?: Prisma.mentionsCreateOrConnectWithoutCommentsInput | Prisma.mentionsCreateOrConnectWithoutCommentsInput[]
  upsert?: Prisma.mentionsUpsertWithWhereUniqueWithoutCommentsInput | Prisma.mentionsUpsertWithWhereUniqueWithoutCommentsInput[]
  createMany?: Prisma.mentionsCreateManyCommentsInputEnvelope
  set?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  disconnect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  delete?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  connect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  update?: Prisma.mentionsUpdateWithWhereUniqueWithoutCommentsInput | Prisma.mentionsUpdateWithWhereUniqueWithoutCommentsInput[]
  updateMany?: Prisma.mentionsUpdateManyWithWhereWithoutCommentsInput | Prisma.mentionsUpdateManyWithWhereWithoutCommentsInput[]
  deleteMany?: Prisma.mentionsScalarWhereInput | Prisma.mentionsScalarWhereInput[]
}

export type mentionsUncheckedUpdateManyWithoutCommentsNestedInput = {
  create?: Prisma.XOR<Prisma.mentionsCreateWithoutCommentsInput, Prisma.mentionsUncheckedCreateWithoutCommentsInput> | Prisma.mentionsCreateWithoutCommentsInput[] | Prisma.mentionsUncheckedCreateWithoutCommentsInput[]
  connectOrCreate?: Prisma.mentionsCreateOrConnectWithoutCommentsInput | Prisma.mentionsCreateOrConnectWithoutCommentsInput[]
  upsert?: Prisma.mentionsUpsertWithWhereUniqueWithoutCommentsInput | Prisma.mentionsUpsertWithWhereUniqueWithoutCommentsInput[]
  createMany?: Prisma.mentionsCreateManyCommentsInputEnvelope
  set?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  disconnect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  delete?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  connect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  update?: Prisma.mentionsUpdateWithWhereUniqueWithoutCommentsInput | Prisma.mentionsUpdateWithWhereUniqueWithoutCommentsInput[]
  updateMany?: Prisma.mentionsUpdateManyWithWhereWithoutCommentsInput | Prisma.mentionsUpdateManyWithWhereWithoutCommentsInput[]
  deleteMany?: Prisma.mentionsScalarWhereInput | Prisma.mentionsScalarWhereInput[]
}

export type mentionsCreateNestedManyWithoutPostsInput = {
  create?: Prisma.XOR<Prisma.mentionsCreateWithoutPostsInput, Prisma.mentionsUncheckedCreateWithoutPostsInput> | Prisma.mentionsCreateWithoutPostsInput[] | Prisma.mentionsUncheckedCreateWithoutPostsInput[]
  connectOrCreate?: Prisma.mentionsCreateOrConnectWithoutPostsInput | Prisma.mentionsCreateOrConnectWithoutPostsInput[]
  createMany?: Prisma.mentionsCreateManyPostsInputEnvelope
  connect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
}

export type mentionsUncheckedCreateNestedManyWithoutPostsInput = {
  create?: Prisma.XOR<Prisma.mentionsCreateWithoutPostsInput, Prisma.mentionsUncheckedCreateWithoutPostsInput> | Prisma.mentionsCreateWithoutPostsInput[] | Prisma.mentionsUncheckedCreateWithoutPostsInput[]
  connectOrCreate?: Prisma.mentionsCreateOrConnectWithoutPostsInput | Prisma.mentionsCreateOrConnectWithoutPostsInput[]
  createMany?: Prisma.mentionsCreateManyPostsInputEnvelope
  connect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
}

export type mentionsUpdateManyWithoutPostsNestedInput = {
  create?: Prisma.XOR<Prisma.mentionsCreateWithoutPostsInput, Prisma.mentionsUncheckedCreateWithoutPostsInput> | Prisma.mentionsCreateWithoutPostsInput[] | Prisma.mentionsUncheckedCreateWithoutPostsInput[]
  connectOrCreate?: Prisma.mentionsCreateOrConnectWithoutPostsInput | Prisma.mentionsCreateOrConnectWithoutPostsInput[]
  upsert?: Prisma.mentionsUpsertWithWhereUniqueWithoutPostsInput | Prisma.mentionsUpsertWithWhereUniqueWithoutPostsInput[]
  createMany?: Prisma.mentionsCreateManyPostsInputEnvelope
  set?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  disconnect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  delete?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  connect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  update?: Prisma.mentionsUpdateWithWhereUniqueWithoutPostsInput | Prisma.mentionsUpdateWithWhereUniqueWithoutPostsInput[]
  updateMany?: Prisma.mentionsUpdateManyWithWhereWithoutPostsInput | Prisma.mentionsUpdateManyWithWhereWithoutPostsInput[]
  deleteMany?: Prisma.mentionsScalarWhereInput | Prisma.mentionsScalarWhereInput[]
}

export type mentionsUncheckedUpdateManyWithoutPostsNestedInput = {
  create?: Prisma.XOR<Prisma.mentionsCreateWithoutPostsInput, Prisma.mentionsUncheckedCreateWithoutPostsInput> | Prisma.mentionsCreateWithoutPostsInput[] | Prisma.mentionsUncheckedCreateWithoutPostsInput[]
  connectOrCreate?: Prisma.mentionsCreateOrConnectWithoutPostsInput | Prisma.mentionsCreateOrConnectWithoutPostsInput[]
  upsert?: Prisma.mentionsUpsertWithWhereUniqueWithoutPostsInput | Prisma.mentionsUpsertWithWhereUniqueWithoutPostsInput[]
  createMany?: Prisma.mentionsCreateManyPostsInputEnvelope
  set?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  disconnect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  delete?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  connect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  update?: Prisma.mentionsUpdateWithWhereUniqueWithoutPostsInput | Prisma.mentionsUpdateWithWhereUniqueWithoutPostsInput[]
  updateMany?: Prisma.mentionsUpdateManyWithWhereWithoutPostsInput | Prisma.mentionsUpdateManyWithWhereWithoutPostsInput[]
  deleteMany?: Prisma.mentionsScalarWhereInput | Prisma.mentionsScalarWhereInput[]
}

export type mentionsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.mentionsCreateWithoutUsersInput, Prisma.mentionsUncheckedCreateWithoutUsersInput> | Prisma.mentionsCreateWithoutUsersInput[] | Prisma.mentionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.mentionsCreateOrConnectWithoutUsersInput | Prisma.mentionsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.mentionsCreateManyUsersInputEnvelope
  connect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
}

export type mentionsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.mentionsCreateWithoutUsersInput, Prisma.mentionsUncheckedCreateWithoutUsersInput> | Prisma.mentionsCreateWithoutUsersInput[] | Prisma.mentionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.mentionsCreateOrConnectWithoutUsersInput | Prisma.mentionsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.mentionsCreateManyUsersInputEnvelope
  connect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
}

export type mentionsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.mentionsCreateWithoutUsersInput, Prisma.mentionsUncheckedCreateWithoutUsersInput> | Prisma.mentionsCreateWithoutUsersInput[] | Prisma.mentionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.mentionsCreateOrConnectWithoutUsersInput | Prisma.mentionsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.mentionsUpsertWithWhereUniqueWithoutUsersInput | Prisma.mentionsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.mentionsCreateManyUsersInputEnvelope
  set?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  disconnect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  delete?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  connect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  update?: Prisma.mentionsUpdateWithWhereUniqueWithoutUsersInput | Prisma.mentionsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.mentionsUpdateManyWithWhereWithoutUsersInput | Prisma.mentionsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.mentionsScalarWhereInput | Prisma.mentionsScalarWhereInput[]
}

export type mentionsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.mentionsCreateWithoutUsersInput, Prisma.mentionsUncheckedCreateWithoutUsersInput> | Prisma.mentionsCreateWithoutUsersInput[] | Prisma.mentionsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.mentionsCreateOrConnectWithoutUsersInput | Prisma.mentionsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.mentionsUpsertWithWhereUniqueWithoutUsersInput | Prisma.mentionsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.mentionsCreateManyUsersInputEnvelope
  set?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  disconnect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  delete?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  connect?: Prisma.mentionsWhereUniqueInput | Prisma.mentionsWhereUniqueInput[]
  update?: Prisma.mentionsUpdateWithWhereUniqueWithoutUsersInput | Prisma.mentionsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.mentionsUpdateManyWithWhereWithoutUsersInput | Prisma.mentionsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.mentionsScalarWhereInput | Prisma.mentionsScalarWhereInput[]
}

export type mentionsCreateWithoutCommentsInput = {
  mention_id?: string
  created_at?: Date | string | null
  users: Prisma.usersCreateNestedOneWithoutMentionsInput
  posts?: Prisma.postsCreateNestedOneWithoutMentionsInput
}

export type mentionsUncheckedCreateWithoutCommentsInput = {
  mention_id?: string
  mentioned_user_id: string
  post_id?: string | null
  created_at?: Date | string | null
}

export type mentionsCreateOrConnectWithoutCommentsInput = {
  where: Prisma.mentionsWhereUniqueInput
  create: Prisma.XOR<Prisma.mentionsCreateWithoutCommentsInput, Prisma.mentionsUncheckedCreateWithoutCommentsInput>
}

export type mentionsCreateManyCommentsInputEnvelope = {
  data: Prisma.mentionsCreateManyCommentsInput | Prisma.mentionsCreateManyCommentsInput[]
  skipDuplicates?: boolean
}

export type mentionsUpsertWithWhereUniqueWithoutCommentsInput = {
  where: Prisma.mentionsWhereUniqueInput
  update: Prisma.XOR<Prisma.mentionsUpdateWithoutCommentsInput, Prisma.mentionsUncheckedUpdateWithoutCommentsInput>
  create: Prisma.XOR<Prisma.mentionsCreateWithoutCommentsInput, Prisma.mentionsUncheckedCreateWithoutCommentsInput>
}

export type mentionsUpdateWithWhereUniqueWithoutCommentsInput = {
  where: Prisma.mentionsWhereUniqueInput
  data: Prisma.XOR<Prisma.mentionsUpdateWithoutCommentsInput, Prisma.mentionsUncheckedUpdateWithoutCommentsInput>
}

export type mentionsUpdateManyWithWhereWithoutCommentsInput = {
  where: Prisma.mentionsScalarWhereInput
  data: Prisma.XOR<Prisma.mentionsUpdateManyMutationInput, Prisma.mentionsUncheckedUpdateManyWithoutCommentsInput>
}

export type mentionsScalarWhereInput = {
  AND?: Prisma.mentionsScalarWhereInput | Prisma.mentionsScalarWhereInput[]
  OR?: Prisma.mentionsScalarWhereInput[]
  NOT?: Prisma.mentionsScalarWhereInput | Prisma.mentionsScalarWhereInput[]
  mention_id?: Prisma.UuidFilter<"mentions"> | string
  mentioned_user_id?: Prisma.UuidFilter<"mentions"> | string
  post_id?: Prisma.UuidNullableFilter<"mentions"> | string | null
  comment_id?: Prisma.UuidNullableFilter<"mentions"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"mentions"> | Date | string | null
}

export type mentionsCreateWithoutPostsInput = {
  mention_id?: string
  created_at?: Date | string | null
  comments?: Prisma.commentsCreateNestedOneWithoutMentionsInput
  users: Prisma.usersCreateNestedOneWithoutMentionsInput
}

export type mentionsUncheckedCreateWithoutPostsInput = {
  mention_id?: string
  mentioned_user_id: string
  comment_id?: string | null
  created_at?: Date | string | null
}

export type mentionsCreateOrConnectWithoutPostsInput = {
  where: Prisma.mentionsWhereUniqueInput
  create: Prisma.XOR<Prisma.mentionsCreateWithoutPostsInput, Prisma.mentionsUncheckedCreateWithoutPostsInput>
}

export type mentionsCreateManyPostsInputEnvelope = {
  data: Prisma.mentionsCreateManyPostsInput | Prisma.mentionsCreateManyPostsInput[]
  skipDuplicates?: boolean
}

export type mentionsUpsertWithWhereUniqueWithoutPostsInput = {
  where: Prisma.mentionsWhereUniqueInput
  update: Prisma.XOR<Prisma.mentionsUpdateWithoutPostsInput, Prisma.mentionsUncheckedUpdateWithoutPostsInput>
  create: Prisma.XOR<Prisma.mentionsCreateWithoutPostsInput, Prisma.mentionsUncheckedCreateWithoutPostsInput>
}

export type mentionsUpdateWithWhereUniqueWithoutPostsInput = {
  where: Prisma.mentionsWhereUniqueInput
  data: Prisma.XOR<Prisma.mentionsUpdateWithoutPostsInput, Prisma.mentionsUncheckedUpdateWithoutPostsInput>
}

export type mentionsUpdateManyWithWhereWithoutPostsInput = {
  where: Prisma.mentionsScalarWhereInput
  data: Prisma.XOR<Prisma.mentionsUpdateManyMutationInput, Prisma.mentionsUncheckedUpdateManyWithoutPostsInput>
}

export type mentionsCreateWithoutUsersInput = {
  mention_id?: string
  created_at?: Date | string | null
  comments?: Prisma.commentsCreateNestedOneWithoutMentionsInput
  posts?: Prisma.postsCreateNestedOneWithoutMentionsInput
}

export type mentionsUncheckedCreateWithoutUsersInput = {
  mention_id?: string
  post_id?: string | null
  comment_id?: string | null
  created_at?: Date | string | null
}

export type mentionsCreateOrConnectWithoutUsersInput = {
  where: Prisma.mentionsWhereUniqueInput
  create: Prisma.XOR<Prisma.mentionsCreateWithoutUsersInput, Prisma.mentionsUncheckedCreateWithoutUsersInput>
}

export type mentionsCreateManyUsersInputEnvelope = {
  data: Prisma.mentionsCreateManyUsersInput | Prisma.mentionsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type mentionsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.mentionsWhereUniqueInput
  update: Prisma.XOR<Prisma.mentionsUpdateWithoutUsersInput, Prisma.mentionsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.mentionsCreateWithoutUsersInput, Prisma.mentionsUncheckedCreateWithoutUsersInput>
}

export type mentionsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.mentionsWhereUniqueInput
  data: Prisma.XOR<Prisma.mentionsUpdateWithoutUsersInput, Prisma.mentionsUncheckedUpdateWithoutUsersInput>
}

export type mentionsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.mentionsScalarWhereInput
  data: Prisma.XOR<Prisma.mentionsUpdateManyMutationInput, Prisma.mentionsUncheckedUpdateManyWithoutUsersInput>
}

export type mentionsCreateManyCommentsInput = {
  mention_id?: string
  mentioned_user_id: string
  post_id?: string | null
  created_at?: Date | string | null
}

export type mentionsUpdateWithoutCommentsInput = {
  mention_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneRequiredWithoutMentionsNestedInput
  posts?: Prisma.postsUpdateOneWithoutMentionsNestedInput
}

export type mentionsUncheckedUpdateWithoutCommentsInput = {
  mention_id?: Prisma.StringFieldUpdateOperationsInput | string
  mentioned_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  post_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type mentionsUncheckedUpdateManyWithoutCommentsInput = {
  mention_id?: Prisma.StringFieldUpdateOperationsInput | string
  mentioned_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  post_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type mentionsCreateManyPostsInput = {
  mention_id?: string
  mentioned_user_id: string
  comment_id?: string | null
  created_at?: Date | string | null
}

export type mentionsUpdateWithoutPostsInput = {
  mention_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  comments?: Prisma.commentsUpdateOneWithoutMentionsNestedInput
  users?: Prisma.usersUpdateOneRequiredWithoutMentionsNestedInput
}

export type mentionsUncheckedUpdateWithoutPostsInput = {
  mention_id?: Prisma.StringFieldUpdateOperationsInput | string
  mentioned_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  comment_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type mentionsUncheckedUpdateManyWithoutPostsInput = {
  mention_id?: Prisma.StringFieldUpdateOperationsInput | string
  mentioned_user_id?: Prisma.StringFieldUpdateOperationsInput | string
  comment_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type mentionsCreateManyUsersInput = {
  mention_id?: string
  post_id?: string | null
  comment_id?: string | null
  created_at?: Date | string | null
}

export type mentionsUpdateWithoutUsersInput = {
  mention_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  comments?: Prisma.commentsUpdateOneWithoutMentionsNestedInput
  posts?: Prisma.postsUpdateOneWithoutMentionsNestedInput
}

export type mentionsUncheckedUpdateWithoutUsersInput = {
  mention_id?: Prisma.StringFieldUpdateOperationsInput | string
  post_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  comment_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type mentionsUncheckedUpdateManyWithoutUsersInput = {
  mention_id?: Prisma.StringFieldUpdateOperationsInput | string
  post_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  comment_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type mentionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  mention_id?: boolean
  mentioned_user_id?: boolean
  post_id?: boolean
  comment_id?: boolean
  created_at?: boolean
  comments?: boolean | Prisma.mentions$commentsArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
  posts?: boolean | Prisma.mentions$postsArgs<ExtArgs>
}, ExtArgs["result"]["mentions"]>

export type mentionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  mention_id?: boolean
  mentioned_user_id?: boolean
  post_id?: boolean
  comment_id?: boolean
  created_at?: boolean
  comments?: boolean | Prisma.mentions$commentsArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
  posts?: boolean | Prisma.mentions$postsArgs<ExtArgs>
}, ExtArgs["result"]["mentions"]>

export type mentionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  mention_id?: boolean
  mentioned_user_id?: boolean
  post_id?: boolean
  comment_id?: boolean
  created_at?: boolean
  comments?: boolean | Prisma.mentions$commentsArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
  posts?: boolean | Prisma.mentions$postsArgs<ExtArgs>
}, ExtArgs["result"]["mentions"]>

export type mentionsSelectScalar = {
  mention_id?: boolean
  mentioned_user_id?: boolean
  post_id?: boolean
  comment_id?: boolean
  created_at?: boolean
}

export type mentionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"mention_id" | "mentioned_user_id" | "post_id" | "comment_id" | "created_at", ExtArgs["result"]["mentions"]>
export type mentionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  comments?: boolean | Prisma.mentions$commentsArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
  posts?: boolean | Prisma.mentions$postsArgs<ExtArgs>
}
export type mentionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  comments?: boolean | Prisma.mentions$commentsArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
  posts?: boolean | Prisma.mentions$postsArgs<ExtArgs>
}
export type mentionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  comments?: boolean | Prisma.mentions$commentsArgs<ExtArgs>
  users?: boolean | Prisma.usersDefaultArgs<ExtArgs>
  posts?: boolean | Prisma.mentions$postsArgs<ExtArgs>
}

export type $mentionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "mentions"
  objects: {
    comments: Prisma.$commentsPayload<ExtArgs> | null
    users: Prisma.$usersPayload<ExtArgs>
    posts: Prisma.$postsPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    mention_id: string
    mentioned_user_id: string
    post_id: string | null
    comment_id: string | null
    created_at: Date | null
  }, ExtArgs["result"]["mentions"]>
  composites: {}
}

export type mentionsGetPayload<S extends boolean | null | undefined | mentionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$mentionsPayload, S>

export type mentionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<mentionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MentionsCountAggregateInputType | true
  }

export interface mentionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['mentions'], meta: { name: 'mentions' } }
  /**
   * Find zero or one Mentions that matches the filter.
   * @param {mentionsFindUniqueArgs} args - Arguments to find a Mentions
   * @example
   * // Get one Mentions
   * const mentions = await prisma.mentions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends mentionsFindUniqueArgs>(args: Prisma.SelectSubset<T, mentionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__mentionsClient<runtime.Types.Result.GetResult<Prisma.$mentionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Mentions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {mentionsFindUniqueOrThrowArgs} args - Arguments to find a Mentions
   * @example
   * // Get one Mentions
   * const mentions = await prisma.mentions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends mentionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, mentionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__mentionsClient<runtime.Types.Result.GetResult<Prisma.$mentionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mentions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {mentionsFindFirstArgs} args - Arguments to find a Mentions
   * @example
   * // Get one Mentions
   * const mentions = await prisma.mentions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends mentionsFindFirstArgs>(args?: Prisma.SelectSubset<T, mentionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__mentionsClient<runtime.Types.Result.GetResult<Prisma.$mentionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Mentions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {mentionsFindFirstOrThrowArgs} args - Arguments to find a Mentions
   * @example
   * // Get one Mentions
   * const mentions = await prisma.mentions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends mentionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, mentionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__mentionsClient<runtime.Types.Result.GetResult<Prisma.$mentionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Mentions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {mentionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Mentions
   * const mentions = await prisma.mentions.findMany()
   * 
   * // Get first 10 Mentions
   * const mentions = await prisma.mentions.findMany({ take: 10 })
   * 
   * // Only select the `mention_id`
   * const mentionsWithMention_idOnly = await prisma.mentions.findMany({ select: { mention_id: true } })
   * 
   */
  findMany<T extends mentionsFindManyArgs>(args?: Prisma.SelectSubset<T, mentionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$mentionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Mentions.
   * @param {mentionsCreateArgs} args - Arguments to create a Mentions.
   * @example
   * // Create one Mentions
   * const Mentions = await prisma.mentions.create({
   *   data: {
   *     // ... data to create a Mentions
   *   }
   * })
   * 
   */
  create<T extends mentionsCreateArgs>(args: Prisma.SelectSubset<T, mentionsCreateArgs<ExtArgs>>): Prisma.Prisma__mentionsClient<runtime.Types.Result.GetResult<Prisma.$mentionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Mentions.
   * @param {mentionsCreateManyArgs} args - Arguments to create many Mentions.
   * @example
   * // Create many Mentions
   * const mentions = await prisma.mentions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends mentionsCreateManyArgs>(args?: Prisma.SelectSubset<T, mentionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Mentions and returns the data saved in the database.
   * @param {mentionsCreateManyAndReturnArgs} args - Arguments to create many Mentions.
   * @example
   * // Create many Mentions
   * const mentions = await prisma.mentions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Mentions and only return the `mention_id`
   * const mentionsWithMention_idOnly = await prisma.mentions.createManyAndReturn({
   *   select: { mention_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends mentionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, mentionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$mentionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Mentions.
   * @param {mentionsDeleteArgs} args - Arguments to delete one Mentions.
   * @example
   * // Delete one Mentions
   * const Mentions = await prisma.mentions.delete({
   *   where: {
   *     // ... filter to delete one Mentions
   *   }
   * })
   * 
   */
  delete<T extends mentionsDeleteArgs>(args: Prisma.SelectSubset<T, mentionsDeleteArgs<ExtArgs>>): Prisma.Prisma__mentionsClient<runtime.Types.Result.GetResult<Prisma.$mentionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Mentions.
   * @param {mentionsUpdateArgs} args - Arguments to update one Mentions.
   * @example
   * // Update one Mentions
   * const mentions = await prisma.mentions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends mentionsUpdateArgs>(args: Prisma.SelectSubset<T, mentionsUpdateArgs<ExtArgs>>): Prisma.Prisma__mentionsClient<runtime.Types.Result.GetResult<Prisma.$mentionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Mentions.
   * @param {mentionsDeleteManyArgs} args - Arguments to filter Mentions to delete.
   * @example
   * // Delete a few Mentions
   * const { count } = await prisma.mentions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends mentionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, mentionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mentions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {mentionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Mentions
   * const mentions = await prisma.mentions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends mentionsUpdateManyArgs>(args: Prisma.SelectSubset<T, mentionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Mentions and returns the data updated in the database.
   * @param {mentionsUpdateManyAndReturnArgs} args - Arguments to update many Mentions.
   * @example
   * // Update many Mentions
   * const mentions = await prisma.mentions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Mentions and only return the `mention_id`
   * const mentionsWithMention_idOnly = await prisma.mentions.updateManyAndReturn({
   *   select: { mention_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends mentionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, mentionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$mentionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Mentions.
   * @param {mentionsUpsertArgs} args - Arguments to update or create a Mentions.
   * @example
   * // Update or create a Mentions
   * const mentions = await prisma.mentions.upsert({
   *   create: {
   *     // ... data to create a Mentions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Mentions we want to update
   *   }
   * })
   */
  upsert<T extends mentionsUpsertArgs>(args: Prisma.SelectSubset<T, mentionsUpsertArgs<ExtArgs>>): Prisma.Prisma__mentionsClient<runtime.Types.Result.GetResult<Prisma.$mentionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Mentions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {mentionsCountArgs} args - Arguments to filter Mentions to count.
   * @example
   * // Count the number of Mentions
   * const count = await prisma.mentions.count({
   *   where: {
   *     // ... the filter for the Mentions we want to count
   *   }
   * })
  **/
  count<T extends mentionsCountArgs>(
    args?: Prisma.Subset<T, mentionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MentionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Mentions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MentionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MentionsAggregateArgs>(args: Prisma.Subset<T, MentionsAggregateArgs>): Prisma.PrismaPromise<GetMentionsAggregateType<T>>

  /**
   * Group by Mentions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {mentionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends mentionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: mentionsGroupByArgs['orderBy'] }
      : { orderBy?: mentionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, mentionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMentionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the mentions model
 */
readonly fields: mentionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for mentions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__mentionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  comments<T extends Prisma.mentions$commentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.mentions$commentsArgs<ExtArgs>>): Prisma.Prisma__commentsClient<runtime.Types.Result.GetResult<Prisma.$commentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.usersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.usersDefaultArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  posts<T extends Prisma.mentions$postsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.mentions$postsArgs<ExtArgs>>): Prisma.Prisma__postsClient<runtime.Types.Result.GetResult<Prisma.$postsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the mentions model
 */
export interface mentionsFieldRefs {
  readonly mention_id: Prisma.FieldRef<"mentions", 'String'>
  readonly mentioned_user_id: Prisma.FieldRef<"mentions", 'String'>
  readonly post_id: Prisma.FieldRef<"mentions", 'String'>
  readonly comment_id: Prisma.FieldRef<"mentions", 'String'>
  readonly created_at: Prisma.FieldRef<"mentions", 'DateTime'>
}
    

// Custom InputTypes
/**
 * mentions findUnique
 */
export type mentionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mentions
   */
  select?: Prisma.mentionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mentions
   */
  omit?: Prisma.mentionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.mentionsInclude<ExtArgs> | null
  /**
   * Filter, which mentions to fetch.
   */
  where: Prisma.mentionsWhereUniqueInput
}

/**
 * mentions findUniqueOrThrow
 */
export type mentionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mentions
   */
  select?: Prisma.mentionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mentions
   */
  omit?: Prisma.mentionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.mentionsInclude<ExtArgs> | null
  /**
   * Filter, which mentions to fetch.
   */
  where: Prisma.mentionsWhereUniqueInput
}

/**
 * mentions findFirst
 */
export type mentionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mentions
   */
  select?: Prisma.mentionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mentions
   */
  omit?: Prisma.mentionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.mentionsInclude<ExtArgs> | null
  /**
   * Filter, which mentions to fetch.
   */
  where?: Prisma.mentionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of mentions to fetch.
   */
  orderBy?: Prisma.mentionsOrderByWithRelationInput | Prisma.mentionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for mentions.
   */
  cursor?: Prisma.mentionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` mentions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` mentions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of mentions.
   */
  distinct?: Prisma.MentionsScalarFieldEnum | Prisma.MentionsScalarFieldEnum[]
}

/**
 * mentions findFirstOrThrow
 */
export type mentionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mentions
   */
  select?: Prisma.mentionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mentions
   */
  omit?: Prisma.mentionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.mentionsInclude<ExtArgs> | null
  /**
   * Filter, which mentions to fetch.
   */
  where?: Prisma.mentionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of mentions to fetch.
   */
  orderBy?: Prisma.mentionsOrderByWithRelationInput | Prisma.mentionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for mentions.
   */
  cursor?: Prisma.mentionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` mentions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` mentions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of mentions.
   */
  distinct?: Prisma.MentionsScalarFieldEnum | Prisma.MentionsScalarFieldEnum[]
}

/**
 * mentions findMany
 */
export type mentionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mentions
   */
  select?: Prisma.mentionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mentions
   */
  omit?: Prisma.mentionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.mentionsInclude<ExtArgs> | null
  /**
   * Filter, which mentions to fetch.
   */
  where?: Prisma.mentionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of mentions to fetch.
   */
  orderBy?: Prisma.mentionsOrderByWithRelationInput | Prisma.mentionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing mentions.
   */
  cursor?: Prisma.mentionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` mentions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` mentions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of mentions.
   */
  distinct?: Prisma.MentionsScalarFieldEnum | Prisma.MentionsScalarFieldEnum[]
}

/**
 * mentions create
 */
export type mentionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mentions
   */
  select?: Prisma.mentionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mentions
   */
  omit?: Prisma.mentionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.mentionsInclude<ExtArgs> | null
  /**
   * The data needed to create a mentions.
   */
  data: Prisma.XOR<Prisma.mentionsCreateInput, Prisma.mentionsUncheckedCreateInput>
}

/**
 * mentions createMany
 */
export type mentionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many mentions.
   */
  data: Prisma.mentionsCreateManyInput | Prisma.mentionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * mentions createManyAndReturn
 */
export type mentionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mentions
   */
  select?: Prisma.mentionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the mentions
   */
  omit?: Prisma.mentionsOmit<ExtArgs> | null
  /**
   * The data used to create many mentions.
   */
  data: Prisma.mentionsCreateManyInput | Prisma.mentionsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.mentionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * mentions update
 */
export type mentionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mentions
   */
  select?: Prisma.mentionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mentions
   */
  omit?: Prisma.mentionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.mentionsInclude<ExtArgs> | null
  /**
   * The data needed to update a mentions.
   */
  data: Prisma.XOR<Prisma.mentionsUpdateInput, Prisma.mentionsUncheckedUpdateInput>
  /**
   * Choose, which mentions to update.
   */
  where: Prisma.mentionsWhereUniqueInput
}

/**
 * mentions updateMany
 */
export type mentionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update mentions.
   */
  data: Prisma.XOR<Prisma.mentionsUpdateManyMutationInput, Prisma.mentionsUncheckedUpdateManyInput>
  /**
   * Filter which mentions to update
   */
  where?: Prisma.mentionsWhereInput
  /**
   * Limit how many mentions to update.
   */
  limit?: number
}

/**
 * mentions updateManyAndReturn
 */
export type mentionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mentions
   */
  select?: Prisma.mentionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the mentions
   */
  omit?: Prisma.mentionsOmit<ExtArgs> | null
  /**
   * The data used to update mentions.
   */
  data: Prisma.XOR<Prisma.mentionsUpdateManyMutationInput, Prisma.mentionsUncheckedUpdateManyInput>
  /**
   * Filter which mentions to update
   */
  where?: Prisma.mentionsWhereInput
  /**
   * Limit how many mentions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.mentionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * mentions upsert
 */
export type mentionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mentions
   */
  select?: Prisma.mentionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mentions
   */
  omit?: Prisma.mentionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.mentionsInclude<ExtArgs> | null
  /**
   * The filter to search for the mentions to update in case it exists.
   */
  where: Prisma.mentionsWhereUniqueInput
  /**
   * In case the mentions found by the `where` argument doesn't exist, create a new mentions with this data.
   */
  create: Prisma.XOR<Prisma.mentionsCreateInput, Prisma.mentionsUncheckedCreateInput>
  /**
   * In case the mentions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.mentionsUpdateInput, Prisma.mentionsUncheckedUpdateInput>
}

/**
 * mentions delete
 */
export type mentionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mentions
   */
  select?: Prisma.mentionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mentions
   */
  omit?: Prisma.mentionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.mentionsInclude<ExtArgs> | null
  /**
   * Filter which mentions to delete.
   */
  where: Prisma.mentionsWhereUniqueInput
}

/**
 * mentions deleteMany
 */
export type mentionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which mentions to delete
   */
  where?: Prisma.mentionsWhereInput
  /**
   * Limit how many mentions to delete.
   */
  limit?: number
}

/**
 * mentions.comments
 */
export type mentions$commentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the comments
   */
  select?: Prisma.commentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the comments
   */
  omit?: Prisma.commentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.commentsInclude<ExtArgs> | null
  where?: Prisma.commentsWhereInput
}

/**
 * mentions.posts
 */
export type mentions$postsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the posts
   */
  select?: Prisma.postsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the posts
   */
  omit?: Prisma.postsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.postsInclude<ExtArgs> | null
  where?: Prisma.postsWhereInput
}

/**
 * mentions without action
 */
export type mentionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the mentions
   */
  select?: Prisma.mentionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the mentions
   */
  omit?: Prisma.mentionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.mentionsInclude<ExtArgs> | null
}
