
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `post_likes` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model post_likes
 * 
 */
export type post_likesModel = runtime.Types.Result.DefaultSelection<Prisma.$post_likesPayload>

export type AggregatePost_likes = {
  _count: Post_likesCountAggregateOutputType | null
  _avg: Post_likesAvgAggregateOutputType | null
  _sum: Post_likesSumAggregateOutputType | null
  _min: Post_likesMinAggregateOutputType | null
  _max: Post_likesMaxAggregateOutputType | null
}

export type Post_likesAvgAggregateOutputType = {
  id: number | null
}

export type Post_likesSumAggregateOutputType = {
  id: bigint | null
}

export type Post_likesMinAggregateOutputType = {
  id: bigint | null
  user_id: string | null
  post_id: string | null
  created_at: Date | null
}

export type Post_likesMaxAggregateOutputType = {
  id: bigint | null
  user_id: string | null
  post_id: string | null
  created_at: Date | null
}

export type Post_likesCountAggregateOutputType = {
  id: number
  user_id: number
  post_id: number
  created_at: number
  _all: number
}


export type Post_likesAvgAggregateInputType = {
  id?: true
}

export type Post_likesSumAggregateInputType = {
  id?: true
}

export type Post_likesMinAggregateInputType = {
  id?: true
  user_id?: true
  post_id?: true
  created_at?: true
}

export type Post_likesMaxAggregateInputType = {
  id?: true
  user_id?: true
  post_id?: true
  created_at?: true
}

export type Post_likesCountAggregateInputType = {
  id?: true
  user_id?: true
  post_id?: true
  created_at?: true
  _all?: true
}

export type Post_likesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which post_likes to aggregate.
   */
  where?: Prisma.post_likesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of post_likes to fetch.
   */
  orderBy?: Prisma.post_likesOrderByWithRelationInput | Prisma.post_likesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.post_likesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` post_likes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` post_likes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned post_likes
  **/
  _count?: true | Post_likesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Post_likesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Post_likesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Post_likesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Post_likesMaxAggregateInputType
}

export type GetPost_likesAggregateType<T extends Post_likesAggregateArgs> = {
      [P in keyof T & keyof AggregatePost_likes]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePost_likes[P]>
    : Prisma.GetScalarType<T[P], AggregatePost_likes[P]>
}




export type post_likesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.post_likesWhereInput
  orderBy?: Prisma.post_likesOrderByWithAggregationInput | Prisma.post_likesOrderByWithAggregationInput[]
  by: Prisma.Post_likesScalarFieldEnum[] | Prisma.Post_likesScalarFieldEnum
  having?: Prisma.post_likesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Post_likesCountAggregateInputType | true
  _avg?: Post_likesAvgAggregateInputType
  _sum?: Post_likesSumAggregateInputType
  _min?: Post_likesMinAggregateInputType
  _max?: Post_likesMaxAggregateInputType
}

export type Post_likesGroupByOutputType = {
  id: bigint
  user_id: string | null
  post_id: string
  created_at: Date
  _count: Post_likesCountAggregateOutputType | null
  _avg: Post_likesAvgAggregateOutputType | null
  _sum: Post_likesSumAggregateOutputType | null
  _min: Post_likesMinAggregateOutputType | null
  _max: Post_likesMaxAggregateOutputType | null
}

export type GetPost_likesGroupByPayload<T extends post_likesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Post_likesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Post_likesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Post_likesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Post_likesGroupByOutputType[P]>
      }
    >
  >



export type post_likesWhereInput = {
  AND?: Prisma.post_likesWhereInput | Prisma.post_likesWhereInput[]
  OR?: Prisma.post_likesWhereInput[]
  NOT?: Prisma.post_likesWhereInput | Prisma.post_likesWhereInput[]
  id?: Prisma.BigIntFilter<"post_likes"> | bigint | number
  user_id?: Prisma.UuidNullableFilter<"post_likes"> | string | null
  post_id?: Prisma.UuidFilter<"post_likes"> | string
  created_at?: Prisma.DateTimeFilter<"post_likes"> | Date | string
  user?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
  post?: Prisma.XOR<Prisma.PostsScalarRelationFilter, Prisma.postsWhereInput>
}

export type post_likesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  post_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  user?: Prisma.usersOrderByWithRelationInput
  post?: Prisma.postsOrderByWithRelationInput
}

export type post_likesWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  user_id_post_id?: Prisma.post_likesUser_idPost_idCompoundUniqueInput
  AND?: Prisma.post_likesWhereInput | Prisma.post_likesWhereInput[]
  OR?: Prisma.post_likesWhereInput[]
  NOT?: Prisma.post_likesWhereInput | Prisma.post_likesWhereInput[]
  user_id?: Prisma.UuidNullableFilter<"post_likes"> | string | null
  post_id?: Prisma.UuidFilter<"post_likes"> | string
  created_at?: Prisma.DateTimeFilter<"post_likes"> | Date | string
  user?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
  post?: Prisma.XOR<Prisma.PostsScalarRelationFilter, Prisma.postsWhereInput>
}, "id" | "user_id_post_id">

export type post_likesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  post_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.post_likesCountOrderByAggregateInput
  _avg?: Prisma.post_likesAvgOrderByAggregateInput
  _max?: Prisma.post_likesMaxOrderByAggregateInput
  _min?: Prisma.post_likesMinOrderByAggregateInput
  _sum?: Prisma.post_likesSumOrderByAggregateInput
}

export type post_likesScalarWhereWithAggregatesInput = {
  AND?: Prisma.post_likesScalarWhereWithAggregatesInput | Prisma.post_likesScalarWhereWithAggregatesInput[]
  OR?: Prisma.post_likesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.post_likesScalarWhereWithAggregatesInput | Prisma.post_likesScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"post_likes"> | bigint | number
  user_id?: Prisma.UuidNullableWithAggregatesFilter<"post_likes"> | string | null
  post_id?: Prisma.UuidWithAggregatesFilter<"post_likes"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"post_likes"> | Date | string
}

export type post_likesCreateInput = {
  id?: bigint | number
  created_at?: Date | string
  user?: Prisma.usersCreateNestedOneWithoutPost_likesInput
  post: Prisma.postsCreateNestedOneWithoutPost_likesInput
}

export type post_likesUncheckedCreateInput = {
  id?: bigint | number
  user_id?: string | null
  post_id: string
  created_at?: Date | string
}

export type post_likesUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.usersUpdateOneWithoutPost_likesNestedInput
  post?: Prisma.postsUpdateOneRequiredWithoutPost_likesNestedInput
}

export type post_likesUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  post_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type post_likesCreateManyInput = {
  id?: bigint | number
  user_id?: string | null
  post_id: string
  created_at?: Date | string
}

export type post_likesUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type post_likesUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  post_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type post_likesUser_idPost_idCompoundUniqueInput = {
  user_id: string
  post_id: string
}

export type post_likesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  post_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type post_likesAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type post_likesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  post_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type post_likesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  post_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type post_likesSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type Post_likesListRelationFilter = {
  every?: Prisma.post_likesWhereInput
  some?: Prisma.post_likesWhereInput
  none?: Prisma.post_likesWhereInput
}

export type post_likesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type post_likesCreateNestedManyWithoutPostInput = {
  create?: Prisma.XOR<Prisma.post_likesCreateWithoutPostInput, Prisma.post_likesUncheckedCreateWithoutPostInput> | Prisma.post_likesCreateWithoutPostInput[] | Prisma.post_likesUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.post_likesCreateOrConnectWithoutPostInput | Prisma.post_likesCreateOrConnectWithoutPostInput[]
  createMany?: Prisma.post_likesCreateManyPostInputEnvelope
  connect?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
}

export type post_likesUncheckedCreateNestedManyWithoutPostInput = {
  create?: Prisma.XOR<Prisma.post_likesCreateWithoutPostInput, Prisma.post_likesUncheckedCreateWithoutPostInput> | Prisma.post_likesCreateWithoutPostInput[] | Prisma.post_likesUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.post_likesCreateOrConnectWithoutPostInput | Prisma.post_likesCreateOrConnectWithoutPostInput[]
  createMany?: Prisma.post_likesCreateManyPostInputEnvelope
  connect?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
}

export type post_likesUpdateManyWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.post_likesCreateWithoutPostInput, Prisma.post_likesUncheckedCreateWithoutPostInput> | Prisma.post_likesCreateWithoutPostInput[] | Prisma.post_likesUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.post_likesCreateOrConnectWithoutPostInput | Prisma.post_likesCreateOrConnectWithoutPostInput[]
  upsert?: Prisma.post_likesUpsertWithWhereUniqueWithoutPostInput | Prisma.post_likesUpsertWithWhereUniqueWithoutPostInput[]
  createMany?: Prisma.post_likesCreateManyPostInputEnvelope
  set?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  disconnect?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  delete?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  connect?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  update?: Prisma.post_likesUpdateWithWhereUniqueWithoutPostInput | Prisma.post_likesUpdateWithWhereUniqueWithoutPostInput[]
  updateMany?: Prisma.post_likesUpdateManyWithWhereWithoutPostInput | Prisma.post_likesUpdateManyWithWhereWithoutPostInput[]
  deleteMany?: Prisma.post_likesScalarWhereInput | Prisma.post_likesScalarWhereInput[]
}

export type post_likesUncheckedUpdateManyWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.post_likesCreateWithoutPostInput, Prisma.post_likesUncheckedCreateWithoutPostInput> | Prisma.post_likesCreateWithoutPostInput[] | Prisma.post_likesUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.post_likesCreateOrConnectWithoutPostInput | Prisma.post_likesCreateOrConnectWithoutPostInput[]
  upsert?: Prisma.post_likesUpsertWithWhereUniqueWithoutPostInput | Prisma.post_likesUpsertWithWhereUniqueWithoutPostInput[]
  createMany?: Prisma.post_likesCreateManyPostInputEnvelope
  set?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  disconnect?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  delete?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  connect?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  update?: Prisma.post_likesUpdateWithWhereUniqueWithoutPostInput | Prisma.post_likesUpdateWithWhereUniqueWithoutPostInput[]
  updateMany?: Prisma.post_likesUpdateManyWithWhereWithoutPostInput | Prisma.post_likesUpdateManyWithWhereWithoutPostInput[]
  deleteMany?: Prisma.post_likesScalarWhereInput | Prisma.post_likesScalarWhereInput[]
}

export type post_likesCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.post_likesCreateWithoutUserInput, Prisma.post_likesUncheckedCreateWithoutUserInput> | Prisma.post_likesCreateWithoutUserInput[] | Prisma.post_likesUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.post_likesCreateOrConnectWithoutUserInput | Prisma.post_likesCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.post_likesCreateManyUserInputEnvelope
  connect?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
}

export type post_likesUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.post_likesCreateWithoutUserInput, Prisma.post_likesUncheckedCreateWithoutUserInput> | Prisma.post_likesCreateWithoutUserInput[] | Prisma.post_likesUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.post_likesCreateOrConnectWithoutUserInput | Prisma.post_likesCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.post_likesCreateManyUserInputEnvelope
  connect?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
}

export type post_likesUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.post_likesCreateWithoutUserInput, Prisma.post_likesUncheckedCreateWithoutUserInput> | Prisma.post_likesCreateWithoutUserInput[] | Prisma.post_likesUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.post_likesCreateOrConnectWithoutUserInput | Prisma.post_likesCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.post_likesUpsertWithWhereUniqueWithoutUserInput | Prisma.post_likesUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.post_likesCreateManyUserInputEnvelope
  set?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  disconnect?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  delete?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  connect?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  update?: Prisma.post_likesUpdateWithWhereUniqueWithoutUserInput | Prisma.post_likesUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.post_likesUpdateManyWithWhereWithoutUserInput | Prisma.post_likesUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.post_likesScalarWhereInput | Prisma.post_likesScalarWhereInput[]
}

export type post_likesUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.post_likesCreateWithoutUserInput, Prisma.post_likesUncheckedCreateWithoutUserInput> | Prisma.post_likesCreateWithoutUserInput[] | Prisma.post_likesUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.post_likesCreateOrConnectWithoutUserInput | Prisma.post_likesCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.post_likesUpsertWithWhereUniqueWithoutUserInput | Prisma.post_likesUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.post_likesCreateManyUserInputEnvelope
  set?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  disconnect?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  delete?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  connect?: Prisma.post_likesWhereUniqueInput | Prisma.post_likesWhereUniqueInput[]
  update?: Prisma.post_likesUpdateWithWhereUniqueWithoutUserInput | Prisma.post_likesUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.post_likesUpdateManyWithWhereWithoutUserInput | Prisma.post_likesUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.post_likesScalarWhereInput | Prisma.post_likesScalarWhereInput[]
}

export type post_likesCreateWithoutPostInput = {
  id?: bigint | number
  created_at?: Date | string
  user?: Prisma.usersCreateNestedOneWithoutPost_likesInput
}

export type post_likesUncheckedCreateWithoutPostInput = {
  id?: bigint | number
  user_id?: string | null
  created_at?: Date | string
}

export type post_likesCreateOrConnectWithoutPostInput = {
  where: Prisma.post_likesWhereUniqueInput
  create: Prisma.XOR<Prisma.post_likesCreateWithoutPostInput, Prisma.post_likesUncheckedCreateWithoutPostInput>
}

export type post_likesCreateManyPostInputEnvelope = {
  data: Prisma.post_likesCreateManyPostInput | Prisma.post_likesCreateManyPostInput[]
  skipDuplicates?: boolean
}

export type post_likesUpsertWithWhereUniqueWithoutPostInput = {
  where: Prisma.post_likesWhereUniqueInput
  update: Prisma.XOR<Prisma.post_likesUpdateWithoutPostInput, Prisma.post_likesUncheckedUpdateWithoutPostInput>
  create: Prisma.XOR<Prisma.post_likesCreateWithoutPostInput, Prisma.post_likesUncheckedCreateWithoutPostInput>
}

export type post_likesUpdateWithWhereUniqueWithoutPostInput = {
  where: Prisma.post_likesWhereUniqueInput
  data: Prisma.XOR<Prisma.post_likesUpdateWithoutPostInput, Prisma.post_likesUncheckedUpdateWithoutPostInput>
}

export type post_likesUpdateManyWithWhereWithoutPostInput = {
  where: Prisma.post_likesScalarWhereInput
  data: Prisma.XOR<Prisma.post_likesUpdateManyMutationInput, Prisma.post_likesUncheckedUpdateManyWithoutPostInput>
}

export type post_likesScalarWhereInput = {
  AND?: Prisma.post_likesScalarWhereInput | Prisma.post_likesScalarWhereInput[]
  OR?: Prisma.post_likesScalarWhereInput[]
  NOT?: Prisma.post_likesScalarWhereInput | Prisma.post_likesScalarWhereInput[]
  id?: Prisma.BigIntFilter<"post_likes"> | bigint | number
  user_id?: Prisma.UuidNullableFilter<"post_likes"> | string | null
  post_id?: Prisma.UuidFilter<"post_likes"> | string
  created_at?: Prisma.DateTimeFilter<"post_likes"> | Date | string
}

export type post_likesCreateWithoutUserInput = {
  id?: bigint | number
  created_at?: Date | string
  post: Prisma.postsCreateNestedOneWithoutPost_likesInput
}

export type post_likesUncheckedCreateWithoutUserInput = {
  id?: bigint | number
  post_id: string
  created_at?: Date | string
}

export type post_likesCreateOrConnectWithoutUserInput = {
  where: Prisma.post_likesWhereUniqueInput
  create: Prisma.XOR<Prisma.post_likesCreateWithoutUserInput, Prisma.post_likesUncheckedCreateWithoutUserInput>
}

export type post_likesCreateManyUserInputEnvelope = {
  data: Prisma.post_likesCreateManyUserInput | Prisma.post_likesCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type post_likesUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.post_likesWhereUniqueInput
  update: Prisma.XOR<Prisma.post_likesUpdateWithoutUserInput, Prisma.post_likesUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.post_likesCreateWithoutUserInput, Prisma.post_likesUncheckedCreateWithoutUserInput>
}

export type post_likesUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.post_likesWhereUniqueInput
  data: Prisma.XOR<Prisma.post_likesUpdateWithoutUserInput, Prisma.post_likesUncheckedUpdateWithoutUserInput>
}

export type post_likesUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.post_likesScalarWhereInput
  data: Prisma.XOR<Prisma.post_likesUpdateManyMutationInput, Prisma.post_likesUncheckedUpdateManyWithoutUserInput>
}

export type post_likesCreateManyPostInput = {
  id?: bigint | number
  user_id?: string | null
  created_at?: Date | string
}

export type post_likesUpdateWithoutPostInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.usersUpdateOneWithoutPost_likesNestedInput
}

export type post_likesUncheckedUpdateWithoutPostInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type post_likesUncheckedUpdateManyWithoutPostInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type post_likesCreateManyUserInput = {
  id?: bigint | number
  post_id: string
  created_at?: Date | string
}

export type post_likesUpdateWithoutUserInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  post?: Prisma.postsUpdateOneRequiredWithoutPost_likesNestedInput
}

export type post_likesUncheckedUpdateWithoutUserInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  post_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type post_likesUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  post_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type post_likesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  post_id?: boolean
  created_at?: boolean
  user?: boolean | Prisma.post_likes$userArgs<ExtArgs>
  post?: boolean | Prisma.postsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["post_likes"]>

export type post_likesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  post_id?: boolean
  created_at?: boolean
  user?: boolean | Prisma.post_likes$userArgs<ExtArgs>
  post?: boolean | Prisma.postsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["post_likes"]>

export type post_likesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  post_id?: boolean
  created_at?: boolean
  user?: boolean | Prisma.post_likes$userArgs<ExtArgs>
  post?: boolean | Prisma.postsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["post_likes"]>

export type post_likesSelectScalar = {
  id?: boolean
  user_id?: boolean
  post_id?: boolean
  created_at?: boolean
}

export type post_likesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "post_id" | "created_at", ExtArgs["result"]["post_likes"]>
export type post_likesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.post_likes$userArgs<ExtArgs>
  post?: boolean | Prisma.postsDefaultArgs<ExtArgs>
}
export type post_likesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.post_likes$userArgs<ExtArgs>
  post?: boolean | Prisma.postsDefaultArgs<ExtArgs>
}
export type post_likesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.post_likes$userArgs<ExtArgs>
  post?: boolean | Prisma.postsDefaultArgs<ExtArgs>
}

export type $post_likesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "post_likes"
  objects: {
    user: Prisma.$usersPayload<ExtArgs> | null
    post: Prisma.$postsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    user_id: string | null
    post_id: string
    created_at: Date
  }, ExtArgs["result"]["post_likes"]>
  composites: {}
}

export type post_likesGetPayload<S extends boolean | null | undefined | post_likesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$post_likesPayload, S>

export type post_likesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<post_likesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Post_likesCountAggregateInputType | true
  }

export interface post_likesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['post_likes'], meta: { name: 'post_likes' } }
  /**
   * Find zero or one Post_likes that matches the filter.
   * @param {post_likesFindUniqueArgs} args - Arguments to find a Post_likes
   * @example
   * // Get one Post_likes
   * const post_likes = await prisma.post_likes.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends post_likesFindUniqueArgs>(args: Prisma.SelectSubset<T, post_likesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__post_likesClient<runtime.Types.Result.GetResult<Prisma.$post_likesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Post_likes that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {post_likesFindUniqueOrThrowArgs} args - Arguments to find a Post_likes
   * @example
   * // Get one Post_likes
   * const post_likes = await prisma.post_likes.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends post_likesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, post_likesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__post_likesClient<runtime.Types.Result.GetResult<Prisma.$post_likesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Post_likes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {post_likesFindFirstArgs} args - Arguments to find a Post_likes
   * @example
   * // Get one Post_likes
   * const post_likes = await prisma.post_likes.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends post_likesFindFirstArgs>(args?: Prisma.SelectSubset<T, post_likesFindFirstArgs<ExtArgs>>): Prisma.Prisma__post_likesClient<runtime.Types.Result.GetResult<Prisma.$post_likesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Post_likes that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {post_likesFindFirstOrThrowArgs} args - Arguments to find a Post_likes
   * @example
   * // Get one Post_likes
   * const post_likes = await prisma.post_likes.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends post_likesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, post_likesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__post_likesClient<runtime.Types.Result.GetResult<Prisma.$post_likesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Post_likes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {post_likesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Post_likes
   * const post_likes = await prisma.post_likes.findMany()
   * 
   * // Get first 10 Post_likes
   * const post_likes = await prisma.post_likes.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const post_likesWithIdOnly = await prisma.post_likes.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends post_likesFindManyArgs>(args?: Prisma.SelectSubset<T, post_likesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$post_likesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Post_likes.
   * @param {post_likesCreateArgs} args - Arguments to create a Post_likes.
   * @example
   * // Create one Post_likes
   * const Post_likes = await prisma.post_likes.create({
   *   data: {
   *     // ... data to create a Post_likes
   *   }
   * })
   * 
   */
  create<T extends post_likesCreateArgs>(args: Prisma.SelectSubset<T, post_likesCreateArgs<ExtArgs>>): Prisma.Prisma__post_likesClient<runtime.Types.Result.GetResult<Prisma.$post_likesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Post_likes.
   * @param {post_likesCreateManyArgs} args - Arguments to create many Post_likes.
   * @example
   * // Create many Post_likes
   * const post_likes = await prisma.post_likes.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends post_likesCreateManyArgs>(args?: Prisma.SelectSubset<T, post_likesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Post_likes and returns the data saved in the database.
   * @param {post_likesCreateManyAndReturnArgs} args - Arguments to create many Post_likes.
   * @example
   * // Create many Post_likes
   * const post_likes = await prisma.post_likes.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Post_likes and only return the `id`
   * const post_likesWithIdOnly = await prisma.post_likes.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends post_likesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, post_likesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$post_likesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Post_likes.
   * @param {post_likesDeleteArgs} args - Arguments to delete one Post_likes.
   * @example
   * // Delete one Post_likes
   * const Post_likes = await prisma.post_likes.delete({
   *   where: {
   *     // ... filter to delete one Post_likes
   *   }
   * })
   * 
   */
  delete<T extends post_likesDeleteArgs>(args: Prisma.SelectSubset<T, post_likesDeleteArgs<ExtArgs>>): Prisma.Prisma__post_likesClient<runtime.Types.Result.GetResult<Prisma.$post_likesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Post_likes.
   * @param {post_likesUpdateArgs} args - Arguments to update one Post_likes.
   * @example
   * // Update one Post_likes
   * const post_likes = await prisma.post_likes.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends post_likesUpdateArgs>(args: Prisma.SelectSubset<T, post_likesUpdateArgs<ExtArgs>>): Prisma.Prisma__post_likesClient<runtime.Types.Result.GetResult<Prisma.$post_likesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Post_likes.
   * @param {post_likesDeleteManyArgs} args - Arguments to filter Post_likes to delete.
   * @example
   * // Delete a few Post_likes
   * const { count } = await prisma.post_likes.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends post_likesDeleteManyArgs>(args?: Prisma.SelectSubset<T, post_likesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Post_likes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {post_likesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Post_likes
   * const post_likes = await prisma.post_likes.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends post_likesUpdateManyArgs>(args: Prisma.SelectSubset<T, post_likesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Post_likes and returns the data updated in the database.
   * @param {post_likesUpdateManyAndReturnArgs} args - Arguments to update many Post_likes.
   * @example
   * // Update many Post_likes
   * const post_likes = await prisma.post_likes.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Post_likes and only return the `id`
   * const post_likesWithIdOnly = await prisma.post_likes.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends post_likesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, post_likesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$post_likesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Post_likes.
   * @param {post_likesUpsertArgs} args - Arguments to update or create a Post_likes.
   * @example
   * // Update or create a Post_likes
   * const post_likes = await prisma.post_likes.upsert({
   *   create: {
   *     // ... data to create a Post_likes
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Post_likes we want to update
   *   }
   * })
   */
  upsert<T extends post_likesUpsertArgs>(args: Prisma.SelectSubset<T, post_likesUpsertArgs<ExtArgs>>): Prisma.Prisma__post_likesClient<runtime.Types.Result.GetResult<Prisma.$post_likesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Post_likes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {post_likesCountArgs} args - Arguments to filter Post_likes to count.
   * @example
   * // Count the number of Post_likes
   * const count = await prisma.post_likes.count({
   *   where: {
   *     // ... the filter for the Post_likes we want to count
   *   }
   * })
  **/
  count<T extends post_likesCountArgs>(
    args?: Prisma.Subset<T, post_likesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Post_likesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Post_likes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Post_likesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Post_likesAggregateArgs>(args: Prisma.Subset<T, Post_likesAggregateArgs>): Prisma.PrismaPromise<GetPost_likesAggregateType<T>>

  /**
   * Group by Post_likes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {post_likesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends post_likesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: post_likesGroupByArgs['orderBy'] }
      : { orderBy?: post_likesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, post_likesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPost_likesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the post_likes model
 */
readonly fields: post_likesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for post_likes.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__post_likesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.post_likes$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.post_likes$userArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  post<T extends Prisma.postsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.postsDefaultArgs<ExtArgs>>): Prisma.Prisma__postsClient<runtime.Types.Result.GetResult<Prisma.$postsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the post_likes model
 */
export interface post_likesFieldRefs {
  readonly id: Prisma.FieldRef<"post_likes", 'BigInt'>
  readonly user_id: Prisma.FieldRef<"post_likes", 'String'>
  readonly post_id: Prisma.FieldRef<"post_likes", 'String'>
  readonly created_at: Prisma.FieldRef<"post_likes", 'DateTime'>
}
    

// Custom InputTypes
/**
 * post_likes findUnique
 */
export type post_likesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post_likes
   */
  select?: Prisma.post_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post_likes
   */
  omit?: Prisma.post_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.post_likesInclude<ExtArgs> | null
  /**
   * Filter, which post_likes to fetch.
   */
  where: Prisma.post_likesWhereUniqueInput
}

/**
 * post_likes findUniqueOrThrow
 */
export type post_likesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post_likes
   */
  select?: Prisma.post_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post_likes
   */
  omit?: Prisma.post_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.post_likesInclude<ExtArgs> | null
  /**
   * Filter, which post_likes to fetch.
   */
  where: Prisma.post_likesWhereUniqueInput
}

/**
 * post_likes findFirst
 */
export type post_likesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post_likes
   */
  select?: Prisma.post_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post_likes
   */
  omit?: Prisma.post_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.post_likesInclude<ExtArgs> | null
  /**
   * Filter, which post_likes to fetch.
   */
  where?: Prisma.post_likesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of post_likes to fetch.
   */
  orderBy?: Prisma.post_likesOrderByWithRelationInput | Prisma.post_likesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for post_likes.
   */
  cursor?: Prisma.post_likesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` post_likes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` post_likes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of post_likes.
   */
  distinct?: Prisma.Post_likesScalarFieldEnum | Prisma.Post_likesScalarFieldEnum[]
}

/**
 * post_likes findFirstOrThrow
 */
export type post_likesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post_likes
   */
  select?: Prisma.post_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post_likes
   */
  omit?: Prisma.post_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.post_likesInclude<ExtArgs> | null
  /**
   * Filter, which post_likes to fetch.
   */
  where?: Prisma.post_likesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of post_likes to fetch.
   */
  orderBy?: Prisma.post_likesOrderByWithRelationInput | Prisma.post_likesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for post_likes.
   */
  cursor?: Prisma.post_likesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` post_likes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` post_likes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of post_likes.
   */
  distinct?: Prisma.Post_likesScalarFieldEnum | Prisma.Post_likesScalarFieldEnum[]
}

/**
 * post_likes findMany
 */
export type post_likesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post_likes
   */
  select?: Prisma.post_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post_likes
   */
  omit?: Prisma.post_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.post_likesInclude<ExtArgs> | null
  /**
   * Filter, which post_likes to fetch.
   */
  where?: Prisma.post_likesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of post_likes to fetch.
   */
  orderBy?: Prisma.post_likesOrderByWithRelationInput | Prisma.post_likesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing post_likes.
   */
  cursor?: Prisma.post_likesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` post_likes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` post_likes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of post_likes.
   */
  distinct?: Prisma.Post_likesScalarFieldEnum | Prisma.Post_likesScalarFieldEnum[]
}

/**
 * post_likes create
 */
export type post_likesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post_likes
   */
  select?: Prisma.post_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post_likes
   */
  omit?: Prisma.post_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.post_likesInclude<ExtArgs> | null
  /**
   * The data needed to create a post_likes.
   */
  data: Prisma.XOR<Prisma.post_likesCreateInput, Prisma.post_likesUncheckedCreateInput>
}

/**
 * post_likes createMany
 */
export type post_likesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many post_likes.
   */
  data: Prisma.post_likesCreateManyInput | Prisma.post_likesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * post_likes createManyAndReturn
 */
export type post_likesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post_likes
   */
  select?: Prisma.post_likesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the post_likes
   */
  omit?: Prisma.post_likesOmit<ExtArgs> | null
  /**
   * The data used to create many post_likes.
   */
  data: Prisma.post_likesCreateManyInput | Prisma.post_likesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.post_likesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * post_likes update
 */
export type post_likesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post_likes
   */
  select?: Prisma.post_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post_likes
   */
  omit?: Prisma.post_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.post_likesInclude<ExtArgs> | null
  /**
   * The data needed to update a post_likes.
   */
  data: Prisma.XOR<Prisma.post_likesUpdateInput, Prisma.post_likesUncheckedUpdateInput>
  /**
   * Choose, which post_likes to update.
   */
  where: Prisma.post_likesWhereUniqueInput
}

/**
 * post_likes updateMany
 */
export type post_likesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update post_likes.
   */
  data: Prisma.XOR<Prisma.post_likesUpdateManyMutationInput, Prisma.post_likesUncheckedUpdateManyInput>
  /**
   * Filter which post_likes to update
   */
  where?: Prisma.post_likesWhereInput
  /**
   * Limit how many post_likes to update.
   */
  limit?: number
}

/**
 * post_likes updateManyAndReturn
 */
export type post_likesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post_likes
   */
  select?: Prisma.post_likesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the post_likes
   */
  omit?: Prisma.post_likesOmit<ExtArgs> | null
  /**
   * The data used to update post_likes.
   */
  data: Prisma.XOR<Prisma.post_likesUpdateManyMutationInput, Prisma.post_likesUncheckedUpdateManyInput>
  /**
   * Filter which post_likes to update
   */
  where?: Prisma.post_likesWhereInput
  /**
   * Limit how many post_likes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.post_likesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * post_likes upsert
 */
export type post_likesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post_likes
   */
  select?: Prisma.post_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post_likes
   */
  omit?: Prisma.post_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.post_likesInclude<ExtArgs> | null
  /**
   * The filter to search for the post_likes to update in case it exists.
   */
  where: Prisma.post_likesWhereUniqueInput
  /**
   * In case the post_likes found by the `where` argument doesn't exist, create a new post_likes with this data.
   */
  create: Prisma.XOR<Prisma.post_likesCreateInput, Prisma.post_likesUncheckedCreateInput>
  /**
   * In case the post_likes was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.post_likesUpdateInput, Prisma.post_likesUncheckedUpdateInput>
}

/**
 * post_likes delete
 */
export type post_likesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post_likes
   */
  select?: Prisma.post_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post_likes
   */
  omit?: Prisma.post_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.post_likesInclude<ExtArgs> | null
  /**
   * Filter which post_likes to delete.
   */
  where: Prisma.post_likesWhereUniqueInput
}

/**
 * post_likes deleteMany
 */
export type post_likesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which post_likes to delete
   */
  where?: Prisma.post_likesWhereInput
  /**
   * Limit how many post_likes to delete.
   */
  limit?: number
}

/**
 * post_likes.user
 */
export type post_likes$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  where?: Prisma.usersWhereInput
}

/**
 * post_likes without action
 */
export type post_likesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the post_likes
   */
  select?: Prisma.post_likesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the post_likes
   */
  omit?: Prisma.post_likesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.post_likesInclude<ExtArgs> | null
}
