
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `refresh_tokens` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model refresh_tokens
 * 
 */
export type refresh_tokensModel = runtime.Types.Result.DefaultSelection<Prisma.$refresh_tokensPayload>

export type AggregateRefresh_tokens = {
  _count: Refresh_tokensCountAggregateOutputType | null
  _min: Refresh_tokensMinAggregateOutputType | null
  _max: Refresh_tokensMaxAggregateOutputType | null
}

export type Refresh_tokensMinAggregateOutputType = {
  token_id: string | null
  user_id: string | null
  token: string | null
  expires_at: Date | null
  created_at: Date | null
}

export type Refresh_tokensMaxAggregateOutputType = {
  token_id: string | null
  user_id: string | null
  token: string | null
  expires_at: Date | null
  created_at: Date | null
}

export type Refresh_tokensCountAggregateOutputType = {
  token_id: number
  user_id: number
  token: number
  expires_at: number
  created_at: number
  _all: number
}


export type Refresh_tokensMinAggregateInputType = {
  token_id?: true
  user_id?: true
  token?: true
  expires_at?: true
  created_at?: true
}

export type Refresh_tokensMaxAggregateInputType = {
  token_id?: true
  user_id?: true
  token?: true
  expires_at?: true
  created_at?: true
}

export type Refresh_tokensCountAggregateInputType = {
  token_id?: true
  user_id?: true
  token?: true
  expires_at?: true
  created_at?: true
  _all?: true
}

export type Refresh_tokensAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which refresh_tokens to aggregate.
   */
  where?: Prisma.refresh_tokensWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of refresh_tokens to fetch.
   */
  orderBy?: Prisma.refresh_tokensOrderByWithRelationInput | Prisma.refresh_tokensOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.refresh_tokensWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` refresh_tokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` refresh_tokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned refresh_tokens
  **/
  _count?: true | Refresh_tokensCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Refresh_tokensMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Refresh_tokensMaxAggregateInputType
}

export type GetRefresh_tokensAggregateType<T extends Refresh_tokensAggregateArgs> = {
      [P in keyof T & keyof AggregateRefresh_tokens]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRefresh_tokens[P]>
    : Prisma.GetScalarType<T[P], AggregateRefresh_tokens[P]>
}




export type refresh_tokensGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.refresh_tokensWhereInput
  orderBy?: Prisma.refresh_tokensOrderByWithAggregationInput | Prisma.refresh_tokensOrderByWithAggregationInput[]
  by: Prisma.Refresh_tokensScalarFieldEnum[] | Prisma.Refresh_tokensScalarFieldEnum
  having?: Prisma.refresh_tokensScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Refresh_tokensCountAggregateInputType | true
  _min?: Refresh_tokensMinAggregateInputType
  _max?: Refresh_tokensMaxAggregateInputType
}

export type Refresh_tokensGroupByOutputType = {
  token_id: string
  user_id: string
  token: string
  expires_at: Date
  created_at: Date
  _count: Refresh_tokensCountAggregateOutputType | null
  _min: Refresh_tokensMinAggregateOutputType | null
  _max: Refresh_tokensMaxAggregateOutputType | null
}

export type GetRefresh_tokensGroupByPayload<T extends refresh_tokensGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Refresh_tokensGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Refresh_tokensGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Refresh_tokensGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Refresh_tokensGroupByOutputType[P]>
      }
    >
  >



export type refresh_tokensWhereInput = {
  AND?: Prisma.refresh_tokensWhereInput | Prisma.refresh_tokensWhereInput[]
  OR?: Prisma.refresh_tokensWhereInput[]
  NOT?: Prisma.refresh_tokensWhereInput | Prisma.refresh_tokensWhereInput[]
  token_id?: Prisma.UuidFilter<"refresh_tokens"> | string
  user_id?: Prisma.UuidFilter<"refresh_tokens"> | string
  token?: Prisma.StringFilter<"refresh_tokens"> | string
  expires_at?: Prisma.DateTimeFilter<"refresh_tokens"> | Date | string
  created_at?: Prisma.DateTimeFilter<"refresh_tokens"> | Date | string
  user?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}

export type refresh_tokensOrderByWithRelationInput = {
  token_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  user?: Prisma.usersOrderByWithRelationInput
}

export type refresh_tokensWhereUniqueInput = Prisma.AtLeast<{
  token_id?: string
  token?: string
  AND?: Prisma.refresh_tokensWhereInput | Prisma.refresh_tokensWhereInput[]
  OR?: Prisma.refresh_tokensWhereInput[]
  NOT?: Prisma.refresh_tokensWhereInput | Prisma.refresh_tokensWhereInput[]
  user_id?: Prisma.UuidFilter<"refresh_tokens"> | string
  expires_at?: Prisma.DateTimeFilter<"refresh_tokens"> | Date | string
  created_at?: Prisma.DateTimeFilter<"refresh_tokens"> | Date | string
  user?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.usersWhereInput>
}, "token_id" | "token">

export type refresh_tokensOrderByWithAggregationInput = {
  token_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.refresh_tokensCountOrderByAggregateInput
  _max?: Prisma.refresh_tokensMaxOrderByAggregateInput
  _min?: Prisma.refresh_tokensMinOrderByAggregateInput
}

export type refresh_tokensScalarWhereWithAggregatesInput = {
  AND?: Prisma.refresh_tokensScalarWhereWithAggregatesInput | Prisma.refresh_tokensScalarWhereWithAggregatesInput[]
  OR?: Prisma.refresh_tokensScalarWhereWithAggregatesInput[]
  NOT?: Prisma.refresh_tokensScalarWhereWithAggregatesInput | Prisma.refresh_tokensScalarWhereWithAggregatesInput[]
  token_id?: Prisma.UuidWithAggregatesFilter<"refresh_tokens"> | string
  user_id?: Prisma.UuidWithAggregatesFilter<"refresh_tokens"> | string
  token?: Prisma.StringWithAggregatesFilter<"refresh_tokens"> | string
  expires_at?: Prisma.DateTimeWithAggregatesFilter<"refresh_tokens"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"refresh_tokens"> | Date | string
}

export type refresh_tokensCreateInput = {
  token_id?: string
  token: string
  expires_at: Date | string
  created_at?: Date | string
  user: Prisma.usersCreateNestedOneWithoutRefreshTokensInput
}

export type refresh_tokensUncheckedCreateInput = {
  token_id?: string
  user_id: string
  token: string
  expires_at: Date | string
  created_at?: Date | string
}

export type refresh_tokensUpdateInput = {
  token_id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.usersUpdateOneRequiredWithoutRefreshTokensNestedInput
}

export type refresh_tokensUncheckedUpdateInput = {
  token_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type refresh_tokensCreateManyInput = {
  token_id?: string
  user_id: string
  token: string
  expires_at: Date | string
  created_at?: Date | string
}

export type refresh_tokensUpdateManyMutationInput = {
  token_id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type refresh_tokensUncheckedUpdateManyInput = {
  token_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Refresh_tokensListRelationFilter = {
  every?: Prisma.refresh_tokensWhereInput
  some?: Prisma.refresh_tokensWhereInput
  none?: Prisma.refresh_tokensWhereInput
}

export type refresh_tokensOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type refresh_tokensCountOrderByAggregateInput = {
  token_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type refresh_tokensMaxOrderByAggregateInput = {
  token_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type refresh_tokensMinOrderByAggregateInput = {
  token_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  token?: Prisma.SortOrder
  expires_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type refresh_tokensCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.refresh_tokensCreateWithoutUserInput, Prisma.refresh_tokensUncheckedCreateWithoutUserInput> | Prisma.refresh_tokensCreateWithoutUserInput[] | Prisma.refresh_tokensUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.refresh_tokensCreateOrConnectWithoutUserInput | Prisma.refresh_tokensCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.refresh_tokensCreateManyUserInputEnvelope
  connect?: Prisma.refresh_tokensWhereUniqueInput | Prisma.refresh_tokensWhereUniqueInput[]
}

export type refresh_tokensUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.refresh_tokensCreateWithoutUserInput, Prisma.refresh_tokensUncheckedCreateWithoutUserInput> | Prisma.refresh_tokensCreateWithoutUserInput[] | Prisma.refresh_tokensUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.refresh_tokensCreateOrConnectWithoutUserInput | Prisma.refresh_tokensCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.refresh_tokensCreateManyUserInputEnvelope
  connect?: Prisma.refresh_tokensWhereUniqueInput | Prisma.refresh_tokensWhereUniqueInput[]
}

export type refresh_tokensUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.refresh_tokensCreateWithoutUserInput, Prisma.refresh_tokensUncheckedCreateWithoutUserInput> | Prisma.refresh_tokensCreateWithoutUserInput[] | Prisma.refresh_tokensUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.refresh_tokensCreateOrConnectWithoutUserInput | Prisma.refresh_tokensCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.refresh_tokensUpsertWithWhereUniqueWithoutUserInput | Prisma.refresh_tokensUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.refresh_tokensCreateManyUserInputEnvelope
  set?: Prisma.refresh_tokensWhereUniqueInput | Prisma.refresh_tokensWhereUniqueInput[]
  disconnect?: Prisma.refresh_tokensWhereUniqueInput | Prisma.refresh_tokensWhereUniqueInput[]
  delete?: Prisma.refresh_tokensWhereUniqueInput | Prisma.refresh_tokensWhereUniqueInput[]
  connect?: Prisma.refresh_tokensWhereUniqueInput | Prisma.refresh_tokensWhereUniqueInput[]
  update?: Prisma.refresh_tokensUpdateWithWhereUniqueWithoutUserInput | Prisma.refresh_tokensUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.refresh_tokensUpdateManyWithWhereWithoutUserInput | Prisma.refresh_tokensUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.refresh_tokensScalarWhereInput | Prisma.refresh_tokensScalarWhereInput[]
}

export type refresh_tokensUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.refresh_tokensCreateWithoutUserInput, Prisma.refresh_tokensUncheckedCreateWithoutUserInput> | Prisma.refresh_tokensCreateWithoutUserInput[] | Prisma.refresh_tokensUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.refresh_tokensCreateOrConnectWithoutUserInput | Prisma.refresh_tokensCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.refresh_tokensUpsertWithWhereUniqueWithoutUserInput | Prisma.refresh_tokensUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.refresh_tokensCreateManyUserInputEnvelope
  set?: Prisma.refresh_tokensWhereUniqueInput | Prisma.refresh_tokensWhereUniqueInput[]
  disconnect?: Prisma.refresh_tokensWhereUniqueInput | Prisma.refresh_tokensWhereUniqueInput[]
  delete?: Prisma.refresh_tokensWhereUniqueInput | Prisma.refresh_tokensWhereUniqueInput[]
  connect?: Prisma.refresh_tokensWhereUniqueInput | Prisma.refresh_tokensWhereUniqueInput[]
  update?: Prisma.refresh_tokensUpdateWithWhereUniqueWithoutUserInput | Prisma.refresh_tokensUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.refresh_tokensUpdateManyWithWhereWithoutUserInput | Prisma.refresh_tokensUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.refresh_tokensScalarWhereInput | Prisma.refresh_tokensScalarWhereInput[]
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type refresh_tokensCreateWithoutUserInput = {
  token_id?: string
  token: string
  expires_at: Date | string
  created_at?: Date | string
}

export type refresh_tokensUncheckedCreateWithoutUserInput = {
  token_id?: string
  token: string
  expires_at: Date | string
  created_at?: Date | string
}

export type refresh_tokensCreateOrConnectWithoutUserInput = {
  where: Prisma.refresh_tokensWhereUniqueInput
  create: Prisma.XOR<Prisma.refresh_tokensCreateWithoutUserInput, Prisma.refresh_tokensUncheckedCreateWithoutUserInput>
}

export type refresh_tokensCreateManyUserInputEnvelope = {
  data: Prisma.refresh_tokensCreateManyUserInput | Prisma.refresh_tokensCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type refresh_tokensUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.refresh_tokensWhereUniqueInput
  update: Prisma.XOR<Prisma.refresh_tokensUpdateWithoutUserInput, Prisma.refresh_tokensUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.refresh_tokensCreateWithoutUserInput, Prisma.refresh_tokensUncheckedCreateWithoutUserInput>
}

export type refresh_tokensUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.refresh_tokensWhereUniqueInput
  data: Prisma.XOR<Prisma.refresh_tokensUpdateWithoutUserInput, Prisma.refresh_tokensUncheckedUpdateWithoutUserInput>
}

export type refresh_tokensUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.refresh_tokensScalarWhereInput
  data: Prisma.XOR<Prisma.refresh_tokensUpdateManyMutationInput, Prisma.refresh_tokensUncheckedUpdateManyWithoutUserInput>
}

export type refresh_tokensScalarWhereInput = {
  AND?: Prisma.refresh_tokensScalarWhereInput | Prisma.refresh_tokensScalarWhereInput[]
  OR?: Prisma.refresh_tokensScalarWhereInput[]
  NOT?: Prisma.refresh_tokensScalarWhereInput | Prisma.refresh_tokensScalarWhereInput[]
  token_id?: Prisma.UuidFilter<"refresh_tokens"> | string
  user_id?: Prisma.UuidFilter<"refresh_tokens"> | string
  token?: Prisma.StringFilter<"refresh_tokens"> | string
  expires_at?: Prisma.DateTimeFilter<"refresh_tokens"> | Date | string
  created_at?: Prisma.DateTimeFilter<"refresh_tokens"> | Date | string
}

export type refresh_tokensCreateManyUserInput = {
  token_id?: string
  token: string
  expires_at: Date | string
  created_at?: Date | string
}

export type refresh_tokensUpdateWithoutUserInput = {
  token_id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type refresh_tokensUncheckedUpdateWithoutUserInput = {
  token_id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type refresh_tokensUncheckedUpdateManyWithoutUserInput = {
  token_id?: Prisma.StringFieldUpdateOperationsInput | string
  token?: Prisma.StringFieldUpdateOperationsInput | string
  expires_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type refresh_tokensSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  token_id?: boolean
  user_id?: boolean
  token?: boolean
  expires_at?: boolean
  created_at?: boolean
  user?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["refresh_tokens"]>

export type refresh_tokensSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  token_id?: boolean
  user_id?: boolean
  token?: boolean
  expires_at?: boolean
  created_at?: boolean
  user?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["refresh_tokens"]>

export type refresh_tokensSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  token_id?: boolean
  user_id?: boolean
  token?: boolean
  expires_at?: boolean
  created_at?: boolean
  user?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["refresh_tokens"]>

export type refresh_tokensSelectScalar = {
  token_id?: boolean
  user_id?: boolean
  token?: boolean
  expires_at?: boolean
  created_at?: boolean
}

export type refresh_tokensOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"token_id" | "user_id" | "token" | "expires_at" | "created_at", ExtArgs["result"]["refresh_tokens"]>
export type refresh_tokensInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type refresh_tokensIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}
export type refresh_tokensIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.usersDefaultArgs<ExtArgs>
}

export type $refresh_tokensPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "refresh_tokens"
  objects: {
    user: Prisma.$usersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    token_id: string
    user_id: string
    token: string
    expires_at: Date
    created_at: Date
  }, ExtArgs["result"]["refresh_tokens"]>
  composites: {}
}

export type refresh_tokensGetPayload<S extends boolean | null | undefined | refresh_tokensDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$refresh_tokensPayload, S>

export type refresh_tokensCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<refresh_tokensFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Refresh_tokensCountAggregateInputType | true
  }

export interface refresh_tokensDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['refresh_tokens'], meta: { name: 'refresh_tokens' } }
  /**
   * Find zero or one Refresh_tokens that matches the filter.
   * @param {refresh_tokensFindUniqueArgs} args - Arguments to find a Refresh_tokens
   * @example
   * // Get one Refresh_tokens
   * const refresh_tokens = await prisma.refresh_tokens.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends refresh_tokensFindUniqueArgs>(args: Prisma.SelectSubset<T, refresh_tokensFindUniqueArgs<ExtArgs>>): Prisma.Prisma__refresh_tokensClient<runtime.Types.Result.GetResult<Prisma.$refresh_tokensPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Refresh_tokens that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {refresh_tokensFindUniqueOrThrowArgs} args - Arguments to find a Refresh_tokens
   * @example
   * // Get one Refresh_tokens
   * const refresh_tokens = await prisma.refresh_tokens.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends refresh_tokensFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, refresh_tokensFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__refresh_tokensClient<runtime.Types.Result.GetResult<Prisma.$refresh_tokensPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Refresh_tokens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {refresh_tokensFindFirstArgs} args - Arguments to find a Refresh_tokens
   * @example
   * // Get one Refresh_tokens
   * const refresh_tokens = await prisma.refresh_tokens.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends refresh_tokensFindFirstArgs>(args?: Prisma.SelectSubset<T, refresh_tokensFindFirstArgs<ExtArgs>>): Prisma.Prisma__refresh_tokensClient<runtime.Types.Result.GetResult<Prisma.$refresh_tokensPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Refresh_tokens that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {refresh_tokensFindFirstOrThrowArgs} args - Arguments to find a Refresh_tokens
   * @example
   * // Get one Refresh_tokens
   * const refresh_tokens = await prisma.refresh_tokens.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends refresh_tokensFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, refresh_tokensFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__refresh_tokensClient<runtime.Types.Result.GetResult<Prisma.$refresh_tokensPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Refresh_tokens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {refresh_tokensFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Refresh_tokens
   * const refresh_tokens = await prisma.refresh_tokens.findMany()
   * 
   * // Get first 10 Refresh_tokens
   * const refresh_tokens = await prisma.refresh_tokens.findMany({ take: 10 })
   * 
   * // Only select the `token_id`
   * const refresh_tokensWithToken_idOnly = await prisma.refresh_tokens.findMany({ select: { token_id: true } })
   * 
   */
  findMany<T extends refresh_tokensFindManyArgs>(args?: Prisma.SelectSubset<T, refresh_tokensFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$refresh_tokensPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Refresh_tokens.
   * @param {refresh_tokensCreateArgs} args - Arguments to create a Refresh_tokens.
   * @example
   * // Create one Refresh_tokens
   * const Refresh_tokens = await prisma.refresh_tokens.create({
   *   data: {
   *     // ... data to create a Refresh_tokens
   *   }
   * })
   * 
   */
  create<T extends refresh_tokensCreateArgs>(args: Prisma.SelectSubset<T, refresh_tokensCreateArgs<ExtArgs>>): Prisma.Prisma__refresh_tokensClient<runtime.Types.Result.GetResult<Prisma.$refresh_tokensPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Refresh_tokens.
   * @param {refresh_tokensCreateManyArgs} args - Arguments to create many Refresh_tokens.
   * @example
   * // Create many Refresh_tokens
   * const refresh_tokens = await prisma.refresh_tokens.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends refresh_tokensCreateManyArgs>(args?: Prisma.SelectSubset<T, refresh_tokensCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Refresh_tokens and returns the data saved in the database.
   * @param {refresh_tokensCreateManyAndReturnArgs} args - Arguments to create many Refresh_tokens.
   * @example
   * // Create many Refresh_tokens
   * const refresh_tokens = await prisma.refresh_tokens.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Refresh_tokens and only return the `token_id`
   * const refresh_tokensWithToken_idOnly = await prisma.refresh_tokens.createManyAndReturn({
   *   select: { token_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends refresh_tokensCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, refresh_tokensCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$refresh_tokensPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Refresh_tokens.
   * @param {refresh_tokensDeleteArgs} args - Arguments to delete one Refresh_tokens.
   * @example
   * // Delete one Refresh_tokens
   * const Refresh_tokens = await prisma.refresh_tokens.delete({
   *   where: {
   *     // ... filter to delete one Refresh_tokens
   *   }
   * })
   * 
   */
  delete<T extends refresh_tokensDeleteArgs>(args: Prisma.SelectSubset<T, refresh_tokensDeleteArgs<ExtArgs>>): Prisma.Prisma__refresh_tokensClient<runtime.Types.Result.GetResult<Prisma.$refresh_tokensPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Refresh_tokens.
   * @param {refresh_tokensUpdateArgs} args - Arguments to update one Refresh_tokens.
   * @example
   * // Update one Refresh_tokens
   * const refresh_tokens = await prisma.refresh_tokens.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends refresh_tokensUpdateArgs>(args: Prisma.SelectSubset<T, refresh_tokensUpdateArgs<ExtArgs>>): Prisma.Prisma__refresh_tokensClient<runtime.Types.Result.GetResult<Prisma.$refresh_tokensPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Refresh_tokens.
   * @param {refresh_tokensDeleteManyArgs} args - Arguments to filter Refresh_tokens to delete.
   * @example
   * // Delete a few Refresh_tokens
   * const { count } = await prisma.refresh_tokens.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends refresh_tokensDeleteManyArgs>(args?: Prisma.SelectSubset<T, refresh_tokensDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Refresh_tokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {refresh_tokensUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Refresh_tokens
   * const refresh_tokens = await prisma.refresh_tokens.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends refresh_tokensUpdateManyArgs>(args: Prisma.SelectSubset<T, refresh_tokensUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Refresh_tokens and returns the data updated in the database.
   * @param {refresh_tokensUpdateManyAndReturnArgs} args - Arguments to update many Refresh_tokens.
   * @example
   * // Update many Refresh_tokens
   * const refresh_tokens = await prisma.refresh_tokens.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Refresh_tokens and only return the `token_id`
   * const refresh_tokensWithToken_idOnly = await prisma.refresh_tokens.updateManyAndReturn({
   *   select: { token_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends refresh_tokensUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, refresh_tokensUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$refresh_tokensPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Refresh_tokens.
   * @param {refresh_tokensUpsertArgs} args - Arguments to update or create a Refresh_tokens.
   * @example
   * // Update or create a Refresh_tokens
   * const refresh_tokens = await prisma.refresh_tokens.upsert({
   *   create: {
   *     // ... data to create a Refresh_tokens
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Refresh_tokens we want to update
   *   }
   * })
   */
  upsert<T extends refresh_tokensUpsertArgs>(args: Prisma.SelectSubset<T, refresh_tokensUpsertArgs<ExtArgs>>): Prisma.Prisma__refresh_tokensClient<runtime.Types.Result.GetResult<Prisma.$refresh_tokensPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Refresh_tokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {refresh_tokensCountArgs} args - Arguments to filter Refresh_tokens to count.
   * @example
   * // Count the number of Refresh_tokens
   * const count = await prisma.refresh_tokens.count({
   *   where: {
   *     // ... the filter for the Refresh_tokens we want to count
   *   }
   * })
  **/
  count<T extends refresh_tokensCountArgs>(
    args?: Prisma.Subset<T, refresh_tokensCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Refresh_tokensCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Refresh_tokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Refresh_tokensAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Refresh_tokensAggregateArgs>(args: Prisma.Subset<T, Refresh_tokensAggregateArgs>): Prisma.PrismaPromise<GetRefresh_tokensAggregateType<T>>

  /**
   * Group by Refresh_tokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {refresh_tokensGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends refresh_tokensGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: refresh_tokensGroupByArgs['orderBy'] }
      : { orderBy?: refresh_tokensGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, refresh_tokensGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRefresh_tokensGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the refresh_tokens model
 */
readonly fields: refresh_tokensFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for refresh_tokens.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__refresh_tokensClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.usersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.usersDefaultArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the refresh_tokens model
 */
export interface refresh_tokensFieldRefs {
  readonly token_id: Prisma.FieldRef<"refresh_tokens", 'String'>
  readonly user_id: Prisma.FieldRef<"refresh_tokens", 'String'>
  readonly token: Prisma.FieldRef<"refresh_tokens", 'String'>
  readonly expires_at: Prisma.FieldRef<"refresh_tokens", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"refresh_tokens", 'DateTime'>
}
    

// Custom InputTypes
/**
 * refresh_tokens findUnique
 */
export type refresh_tokensFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the refresh_tokens
   */
  select?: Prisma.refresh_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the refresh_tokens
   */
  omit?: Prisma.refresh_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.refresh_tokensInclude<ExtArgs> | null
  /**
   * Filter, which refresh_tokens to fetch.
   */
  where: Prisma.refresh_tokensWhereUniqueInput
}

/**
 * refresh_tokens findUniqueOrThrow
 */
export type refresh_tokensFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the refresh_tokens
   */
  select?: Prisma.refresh_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the refresh_tokens
   */
  omit?: Prisma.refresh_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.refresh_tokensInclude<ExtArgs> | null
  /**
   * Filter, which refresh_tokens to fetch.
   */
  where: Prisma.refresh_tokensWhereUniqueInput
}

/**
 * refresh_tokens findFirst
 */
export type refresh_tokensFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the refresh_tokens
   */
  select?: Prisma.refresh_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the refresh_tokens
   */
  omit?: Prisma.refresh_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.refresh_tokensInclude<ExtArgs> | null
  /**
   * Filter, which refresh_tokens to fetch.
   */
  where?: Prisma.refresh_tokensWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of refresh_tokens to fetch.
   */
  orderBy?: Prisma.refresh_tokensOrderByWithRelationInput | Prisma.refresh_tokensOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for refresh_tokens.
   */
  cursor?: Prisma.refresh_tokensWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` refresh_tokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` refresh_tokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of refresh_tokens.
   */
  distinct?: Prisma.Refresh_tokensScalarFieldEnum | Prisma.Refresh_tokensScalarFieldEnum[]
}

/**
 * refresh_tokens findFirstOrThrow
 */
export type refresh_tokensFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the refresh_tokens
   */
  select?: Prisma.refresh_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the refresh_tokens
   */
  omit?: Prisma.refresh_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.refresh_tokensInclude<ExtArgs> | null
  /**
   * Filter, which refresh_tokens to fetch.
   */
  where?: Prisma.refresh_tokensWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of refresh_tokens to fetch.
   */
  orderBy?: Prisma.refresh_tokensOrderByWithRelationInput | Prisma.refresh_tokensOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for refresh_tokens.
   */
  cursor?: Prisma.refresh_tokensWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` refresh_tokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` refresh_tokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of refresh_tokens.
   */
  distinct?: Prisma.Refresh_tokensScalarFieldEnum | Prisma.Refresh_tokensScalarFieldEnum[]
}

/**
 * refresh_tokens findMany
 */
export type refresh_tokensFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the refresh_tokens
   */
  select?: Prisma.refresh_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the refresh_tokens
   */
  omit?: Prisma.refresh_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.refresh_tokensInclude<ExtArgs> | null
  /**
   * Filter, which refresh_tokens to fetch.
   */
  where?: Prisma.refresh_tokensWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of refresh_tokens to fetch.
   */
  orderBy?: Prisma.refresh_tokensOrderByWithRelationInput | Prisma.refresh_tokensOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing refresh_tokens.
   */
  cursor?: Prisma.refresh_tokensWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` refresh_tokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` refresh_tokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of refresh_tokens.
   */
  distinct?: Prisma.Refresh_tokensScalarFieldEnum | Prisma.Refresh_tokensScalarFieldEnum[]
}

/**
 * refresh_tokens create
 */
export type refresh_tokensCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the refresh_tokens
   */
  select?: Prisma.refresh_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the refresh_tokens
   */
  omit?: Prisma.refresh_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.refresh_tokensInclude<ExtArgs> | null
  /**
   * The data needed to create a refresh_tokens.
   */
  data: Prisma.XOR<Prisma.refresh_tokensCreateInput, Prisma.refresh_tokensUncheckedCreateInput>
}

/**
 * refresh_tokens createMany
 */
export type refresh_tokensCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many refresh_tokens.
   */
  data: Prisma.refresh_tokensCreateManyInput | Prisma.refresh_tokensCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * refresh_tokens createManyAndReturn
 */
export type refresh_tokensCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the refresh_tokens
   */
  select?: Prisma.refresh_tokensSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the refresh_tokens
   */
  omit?: Prisma.refresh_tokensOmit<ExtArgs> | null
  /**
   * The data used to create many refresh_tokens.
   */
  data: Prisma.refresh_tokensCreateManyInput | Prisma.refresh_tokensCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.refresh_tokensIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * refresh_tokens update
 */
export type refresh_tokensUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the refresh_tokens
   */
  select?: Prisma.refresh_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the refresh_tokens
   */
  omit?: Prisma.refresh_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.refresh_tokensInclude<ExtArgs> | null
  /**
   * The data needed to update a refresh_tokens.
   */
  data: Prisma.XOR<Prisma.refresh_tokensUpdateInput, Prisma.refresh_tokensUncheckedUpdateInput>
  /**
   * Choose, which refresh_tokens to update.
   */
  where: Prisma.refresh_tokensWhereUniqueInput
}

/**
 * refresh_tokens updateMany
 */
export type refresh_tokensUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update refresh_tokens.
   */
  data: Prisma.XOR<Prisma.refresh_tokensUpdateManyMutationInput, Prisma.refresh_tokensUncheckedUpdateManyInput>
  /**
   * Filter which refresh_tokens to update
   */
  where?: Prisma.refresh_tokensWhereInput
  /**
   * Limit how many refresh_tokens to update.
   */
  limit?: number
}

/**
 * refresh_tokens updateManyAndReturn
 */
export type refresh_tokensUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the refresh_tokens
   */
  select?: Prisma.refresh_tokensSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the refresh_tokens
   */
  omit?: Prisma.refresh_tokensOmit<ExtArgs> | null
  /**
   * The data used to update refresh_tokens.
   */
  data: Prisma.XOR<Prisma.refresh_tokensUpdateManyMutationInput, Prisma.refresh_tokensUncheckedUpdateManyInput>
  /**
   * Filter which refresh_tokens to update
   */
  where?: Prisma.refresh_tokensWhereInput
  /**
   * Limit how many refresh_tokens to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.refresh_tokensIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * refresh_tokens upsert
 */
export type refresh_tokensUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the refresh_tokens
   */
  select?: Prisma.refresh_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the refresh_tokens
   */
  omit?: Prisma.refresh_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.refresh_tokensInclude<ExtArgs> | null
  /**
   * The filter to search for the refresh_tokens to update in case it exists.
   */
  where: Prisma.refresh_tokensWhereUniqueInput
  /**
   * In case the refresh_tokens found by the `where` argument doesn't exist, create a new refresh_tokens with this data.
   */
  create: Prisma.XOR<Prisma.refresh_tokensCreateInput, Prisma.refresh_tokensUncheckedCreateInput>
  /**
   * In case the refresh_tokens was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.refresh_tokensUpdateInput, Prisma.refresh_tokensUncheckedUpdateInput>
}

/**
 * refresh_tokens delete
 */
export type refresh_tokensDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the refresh_tokens
   */
  select?: Prisma.refresh_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the refresh_tokens
   */
  omit?: Prisma.refresh_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.refresh_tokensInclude<ExtArgs> | null
  /**
   * Filter which refresh_tokens to delete.
   */
  where: Prisma.refresh_tokensWhereUniqueInput
}

/**
 * refresh_tokens deleteMany
 */
export type refresh_tokensDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which refresh_tokens to delete
   */
  where?: Prisma.refresh_tokensWhereInput
  /**
   * Limit how many refresh_tokens to delete.
   */
  limit?: number
}

/**
 * refresh_tokens without action
 */
export type refresh_tokensDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the refresh_tokens
   */
  select?: Prisma.refresh_tokensSelect<ExtArgs> | null
  /**
   * Omit specific fields from the refresh_tokens
   */
  omit?: Prisma.refresh_tokensOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.refresh_tokensInclude<ExtArgs> | null
}
