
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `reports` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model reports
 * 
 */
export type reportsModel = runtime.Types.Result.DefaultSelection<Prisma.$reportsPayload>

export type AggregateReports = {
  _count: ReportsCountAggregateOutputType | null
  _min: ReportsMinAggregateOutputType | null
  _max: ReportsMaxAggregateOutputType | null
}

export type ReportsMinAggregateOutputType = {
  report_id: string | null
  reporter_id: string | null
  reported_item_id: string | null
  item_type: string | null
  reason: string | null
  status: string | null
  created_at: Date | null
}

export type ReportsMaxAggregateOutputType = {
  report_id: string | null
  reporter_id: string | null
  reported_item_id: string | null
  item_type: string | null
  reason: string | null
  status: string | null
  created_at: Date | null
}

export type ReportsCountAggregateOutputType = {
  report_id: number
  reporter_id: number
  reported_item_id: number
  item_type: number
  reason: number
  status: number
  created_at: number
  _all: number
}


export type ReportsMinAggregateInputType = {
  report_id?: true
  reporter_id?: true
  reported_item_id?: true
  item_type?: true
  reason?: true
  status?: true
  created_at?: true
}

export type ReportsMaxAggregateInputType = {
  report_id?: true
  reporter_id?: true
  reported_item_id?: true
  item_type?: true
  reason?: true
  status?: true
  created_at?: true
}

export type ReportsCountAggregateInputType = {
  report_id?: true
  reporter_id?: true
  reported_item_id?: true
  item_type?: true
  reason?: true
  status?: true
  created_at?: true
  _all?: true
}

export type ReportsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which reports to aggregate.
   */
  where?: Prisma.reportsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reports to fetch.
   */
  orderBy?: Prisma.reportsOrderByWithRelationInput | Prisma.reportsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.reportsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned reports
  **/
  _count?: true | ReportsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReportsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReportsMaxAggregateInputType
}

export type GetReportsAggregateType<T extends ReportsAggregateArgs> = {
      [P in keyof T & keyof AggregateReports]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReports[P]>
    : Prisma.GetScalarType<T[P], AggregateReports[P]>
}




export type reportsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.reportsWhereInput
  orderBy?: Prisma.reportsOrderByWithAggregationInput | Prisma.reportsOrderByWithAggregationInput[]
  by: Prisma.ReportsScalarFieldEnum[] | Prisma.ReportsScalarFieldEnum
  having?: Prisma.reportsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReportsCountAggregateInputType | true
  _min?: ReportsMinAggregateInputType
  _max?: ReportsMaxAggregateInputType
}

export type ReportsGroupByOutputType = {
  report_id: string
  reporter_id: string | null
  reported_item_id: string
  item_type: string
  reason: string | null
  status: string | null
  created_at: Date | null
  _count: ReportsCountAggregateOutputType | null
  _min: ReportsMinAggregateOutputType | null
  _max: ReportsMaxAggregateOutputType | null
}

export type GetReportsGroupByPayload<T extends reportsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReportsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReportsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReportsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReportsGroupByOutputType[P]>
      }
    >
  >



export type reportsWhereInput = {
  AND?: Prisma.reportsWhereInput | Prisma.reportsWhereInput[]
  OR?: Prisma.reportsWhereInput[]
  NOT?: Prisma.reportsWhereInput | Prisma.reportsWhereInput[]
  report_id?: Prisma.UuidFilter<"reports"> | string
  reporter_id?: Prisma.UuidNullableFilter<"reports"> | string | null
  reported_item_id?: Prisma.UuidFilter<"reports"> | string
  item_type?: Prisma.StringFilter<"reports"> | string
  reason?: Prisma.StringNullableFilter<"reports"> | string | null
  status?: Prisma.StringNullableFilter<"reports"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"reports"> | Date | string | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}

export type reportsOrderByWithRelationInput = {
  report_id?: Prisma.SortOrder
  reporter_id?: Prisma.SortOrderInput | Prisma.SortOrder
  reported_item_id?: Prisma.SortOrder
  item_type?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  users?: Prisma.usersOrderByWithRelationInput
}

export type reportsWhereUniqueInput = Prisma.AtLeast<{
  report_id?: string
  AND?: Prisma.reportsWhereInput | Prisma.reportsWhereInput[]
  OR?: Prisma.reportsWhereInput[]
  NOT?: Prisma.reportsWhereInput | Prisma.reportsWhereInput[]
  reporter_id?: Prisma.UuidNullableFilter<"reports"> | string | null
  reported_item_id?: Prisma.UuidFilter<"reports"> | string
  item_type?: Prisma.StringFilter<"reports"> | string
  reason?: Prisma.StringNullableFilter<"reports"> | string | null
  status?: Prisma.StringNullableFilter<"reports"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"reports"> | Date | string | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}, "report_id">

export type reportsOrderByWithAggregationInput = {
  report_id?: Prisma.SortOrder
  reporter_id?: Prisma.SortOrderInput | Prisma.SortOrder
  reported_item_id?: Prisma.SortOrder
  item_type?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.reportsCountOrderByAggregateInput
  _max?: Prisma.reportsMaxOrderByAggregateInput
  _min?: Prisma.reportsMinOrderByAggregateInput
}

export type reportsScalarWhereWithAggregatesInput = {
  AND?: Prisma.reportsScalarWhereWithAggregatesInput | Prisma.reportsScalarWhereWithAggregatesInput[]
  OR?: Prisma.reportsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.reportsScalarWhereWithAggregatesInput | Prisma.reportsScalarWhereWithAggregatesInput[]
  report_id?: Prisma.UuidWithAggregatesFilter<"reports"> | string
  reporter_id?: Prisma.UuidNullableWithAggregatesFilter<"reports"> | string | null
  reported_item_id?: Prisma.UuidWithAggregatesFilter<"reports"> | string
  item_type?: Prisma.StringWithAggregatesFilter<"reports"> | string
  reason?: Prisma.StringNullableWithAggregatesFilter<"reports"> | string | null
  status?: Prisma.StringNullableWithAggregatesFilter<"reports"> | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"reports"> | Date | string | null
}

export type reportsCreateInput = {
  report_id?: string
  reported_item_id: string
  item_type: string
  reason?: string | null
  status?: string | null
  created_at?: Date | string | null
  users?: Prisma.usersCreateNestedOneWithoutReportsInput
}

export type reportsUncheckedCreateInput = {
  report_id?: string
  reporter_id?: string | null
  reported_item_id: string
  item_type: string
  reason?: string | null
  status?: string | null
  created_at?: Date | string | null
}

export type reportsUpdateInput = {
  report_id?: Prisma.StringFieldUpdateOperationsInput | string
  reported_item_id?: Prisma.StringFieldUpdateOperationsInput | string
  item_type?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneWithoutReportsNestedInput
}

export type reportsUncheckedUpdateInput = {
  report_id?: Prisma.StringFieldUpdateOperationsInput | string
  reporter_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reported_item_id?: Prisma.StringFieldUpdateOperationsInput | string
  item_type?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type reportsCreateManyInput = {
  report_id?: string
  reporter_id?: string | null
  reported_item_id: string
  item_type: string
  reason?: string | null
  status?: string | null
  created_at?: Date | string | null
}

export type reportsUpdateManyMutationInput = {
  report_id?: Prisma.StringFieldUpdateOperationsInput | string
  reported_item_id?: Prisma.StringFieldUpdateOperationsInput | string
  item_type?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type reportsUncheckedUpdateManyInput = {
  report_id?: Prisma.StringFieldUpdateOperationsInput | string
  reporter_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reported_item_id?: Prisma.StringFieldUpdateOperationsInput | string
  item_type?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type reportsCountOrderByAggregateInput = {
  report_id?: Prisma.SortOrder
  reporter_id?: Prisma.SortOrder
  reported_item_id?: Prisma.SortOrder
  item_type?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type reportsMaxOrderByAggregateInput = {
  report_id?: Prisma.SortOrder
  reporter_id?: Prisma.SortOrder
  reported_item_id?: Prisma.SortOrder
  item_type?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type reportsMinOrderByAggregateInput = {
  report_id?: Prisma.SortOrder
  reporter_id?: Prisma.SortOrder
  reported_item_id?: Prisma.SortOrder
  item_type?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type ReportsListRelationFilter = {
  every?: Prisma.reportsWhereInput
  some?: Prisma.reportsWhereInput
  none?: Prisma.reportsWhereInput
}

export type reportsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type reportsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.reportsCreateWithoutUsersInput, Prisma.reportsUncheckedCreateWithoutUsersInput> | Prisma.reportsCreateWithoutUsersInput[] | Prisma.reportsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.reportsCreateOrConnectWithoutUsersInput | Prisma.reportsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.reportsCreateManyUsersInputEnvelope
  connect?: Prisma.reportsWhereUniqueInput | Prisma.reportsWhereUniqueInput[]
}

export type reportsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.reportsCreateWithoutUsersInput, Prisma.reportsUncheckedCreateWithoutUsersInput> | Prisma.reportsCreateWithoutUsersInput[] | Prisma.reportsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.reportsCreateOrConnectWithoutUsersInput | Prisma.reportsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.reportsCreateManyUsersInputEnvelope
  connect?: Prisma.reportsWhereUniqueInput | Prisma.reportsWhereUniqueInput[]
}

export type reportsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.reportsCreateWithoutUsersInput, Prisma.reportsUncheckedCreateWithoutUsersInput> | Prisma.reportsCreateWithoutUsersInput[] | Prisma.reportsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.reportsCreateOrConnectWithoutUsersInput | Prisma.reportsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.reportsUpsertWithWhereUniqueWithoutUsersInput | Prisma.reportsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.reportsCreateManyUsersInputEnvelope
  set?: Prisma.reportsWhereUniqueInput | Prisma.reportsWhereUniqueInput[]
  disconnect?: Prisma.reportsWhereUniqueInput | Prisma.reportsWhereUniqueInput[]
  delete?: Prisma.reportsWhereUniqueInput | Prisma.reportsWhereUniqueInput[]
  connect?: Prisma.reportsWhereUniqueInput | Prisma.reportsWhereUniqueInput[]
  update?: Prisma.reportsUpdateWithWhereUniqueWithoutUsersInput | Prisma.reportsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.reportsUpdateManyWithWhereWithoutUsersInput | Prisma.reportsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.reportsScalarWhereInput | Prisma.reportsScalarWhereInput[]
}

export type reportsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.reportsCreateWithoutUsersInput, Prisma.reportsUncheckedCreateWithoutUsersInput> | Prisma.reportsCreateWithoutUsersInput[] | Prisma.reportsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.reportsCreateOrConnectWithoutUsersInput | Prisma.reportsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.reportsUpsertWithWhereUniqueWithoutUsersInput | Prisma.reportsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.reportsCreateManyUsersInputEnvelope
  set?: Prisma.reportsWhereUniqueInput | Prisma.reportsWhereUniqueInput[]
  disconnect?: Prisma.reportsWhereUniqueInput | Prisma.reportsWhereUniqueInput[]
  delete?: Prisma.reportsWhereUniqueInput | Prisma.reportsWhereUniqueInput[]
  connect?: Prisma.reportsWhereUniqueInput | Prisma.reportsWhereUniqueInput[]
  update?: Prisma.reportsUpdateWithWhereUniqueWithoutUsersInput | Prisma.reportsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.reportsUpdateManyWithWhereWithoutUsersInput | Prisma.reportsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.reportsScalarWhereInput | Prisma.reportsScalarWhereInput[]
}

export type reportsCreateWithoutUsersInput = {
  report_id?: string
  reported_item_id: string
  item_type: string
  reason?: string | null
  status?: string | null
  created_at?: Date | string | null
}

export type reportsUncheckedCreateWithoutUsersInput = {
  report_id?: string
  reported_item_id: string
  item_type: string
  reason?: string | null
  status?: string | null
  created_at?: Date | string | null
}

export type reportsCreateOrConnectWithoutUsersInput = {
  where: Prisma.reportsWhereUniqueInput
  create: Prisma.XOR<Prisma.reportsCreateWithoutUsersInput, Prisma.reportsUncheckedCreateWithoutUsersInput>
}

export type reportsCreateManyUsersInputEnvelope = {
  data: Prisma.reportsCreateManyUsersInput | Prisma.reportsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type reportsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.reportsWhereUniqueInput
  update: Prisma.XOR<Prisma.reportsUpdateWithoutUsersInput, Prisma.reportsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.reportsCreateWithoutUsersInput, Prisma.reportsUncheckedCreateWithoutUsersInput>
}

export type reportsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.reportsWhereUniqueInput
  data: Prisma.XOR<Prisma.reportsUpdateWithoutUsersInput, Prisma.reportsUncheckedUpdateWithoutUsersInput>
}

export type reportsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.reportsScalarWhereInput
  data: Prisma.XOR<Prisma.reportsUpdateManyMutationInput, Prisma.reportsUncheckedUpdateManyWithoutUsersInput>
}

export type reportsScalarWhereInput = {
  AND?: Prisma.reportsScalarWhereInput | Prisma.reportsScalarWhereInput[]
  OR?: Prisma.reportsScalarWhereInput[]
  NOT?: Prisma.reportsScalarWhereInput | Prisma.reportsScalarWhereInput[]
  report_id?: Prisma.UuidFilter<"reports"> | string
  reporter_id?: Prisma.UuidNullableFilter<"reports"> | string | null
  reported_item_id?: Prisma.UuidFilter<"reports"> | string
  item_type?: Prisma.StringFilter<"reports"> | string
  reason?: Prisma.StringNullableFilter<"reports"> | string | null
  status?: Prisma.StringNullableFilter<"reports"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"reports"> | Date | string | null
}

export type reportsCreateManyUsersInput = {
  report_id?: string
  reported_item_id: string
  item_type: string
  reason?: string | null
  status?: string | null
  created_at?: Date | string | null
}

export type reportsUpdateWithoutUsersInput = {
  report_id?: Prisma.StringFieldUpdateOperationsInput | string
  reported_item_id?: Prisma.StringFieldUpdateOperationsInput | string
  item_type?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type reportsUncheckedUpdateWithoutUsersInput = {
  report_id?: Prisma.StringFieldUpdateOperationsInput | string
  reported_item_id?: Prisma.StringFieldUpdateOperationsInput | string
  item_type?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type reportsUncheckedUpdateManyWithoutUsersInput = {
  report_id?: Prisma.StringFieldUpdateOperationsInput | string
  reported_item_id?: Prisma.StringFieldUpdateOperationsInput | string
  item_type?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type reportsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  report_id?: boolean
  reporter_id?: boolean
  reported_item_id?: boolean
  item_type?: boolean
  reason?: boolean
  status?: boolean
  created_at?: boolean
  users?: boolean | Prisma.reports$usersArgs<ExtArgs>
}, ExtArgs["result"]["reports"]>

export type reportsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  report_id?: boolean
  reporter_id?: boolean
  reported_item_id?: boolean
  item_type?: boolean
  reason?: boolean
  status?: boolean
  created_at?: boolean
  users?: boolean | Prisma.reports$usersArgs<ExtArgs>
}, ExtArgs["result"]["reports"]>

export type reportsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  report_id?: boolean
  reporter_id?: boolean
  reported_item_id?: boolean
  item_type?: boolean
  reason?: boolean
  status?: boolean
  created_at?: boolean
  users?: boolean | Prisma.reports$usersArgs<ExtArgs>
}, ExtArgs["result"]["reports"]>

export type reportsSelectScalar = {
  report_id?: boolean
  reporter_id?: boolean
  reported_item_id?: boolean
  item_type?: boolean
  reason?: boolean
  status?: boolean
  created_at?: boolean
}

export type reportsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"report_id" | "reporter_id" | "reported_item_id" | "item_type" | "reason" | "status" | "created_at", ExtArgs["result"]["reports"]>
export type reportsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.reports$usersArgs<ExtArgs>
}
export type reportsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.reports$usersArgs<ExtArgs>
}
export type reportsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.reports$usersArgs<ExtArgs>
}

export type $reportsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "reports"
  objects: {
    users: Prisma.$usersPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    report_id: string
    reporter_id: string | null
    reported_item_id: string
    item_type: string
    reason: string | null
    status: string | null
    created_at: Date | null
  }, ExtArgs["result"]["reports"]>
  composites: {}
}

export type reportsGetPayload<S extends boolean | null | undefined | reportsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$reportsPayload, S>

export type reportsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<reportsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReportsCountAggregateInputType | true
  }

export interface reportsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['reports'], meta: { name: 'reports' } }
  /**
   * Find zero or one Reports that matches the filter.
   * @param {reportsFindUniqueArgs} args - Arguments to find a Reports
   * @example
   * // Get one Reports
   * const reports = await prisma.reports.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends reportsFindUniqueArgs>(args: Prisma.SelectSubset<T, reportsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__reportsClient<runtime.Types.Result.GetResult<Prisma.$reportsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Reports that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {reportsFindUniqueOrThrowArgs} args - Arguments to find a Reports
   * @example
   * // Get one Reports
   * const reports = await prisma.reports.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends reportsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, reportsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__reportsClient<runtime.Types.Result.GetResult<Prisma.$reportsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Reports that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reportsFindFirstArgs} args - Arguments to find a Reports
   * @example
   * // Get one Reports
   * const reports = await prisma.reports.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends reportsFindFirstArgs>(args?: Prisma.SelectSubset<T, reportsFindFirstArgs<ExtArgs>>): Prisma.Prisma__reportsClient<runtime.Types.Result.GetResult<Prisma.$reportsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Reports that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reportsFindFirstOrThrowArgs} args - Arguments to find a Reports
   * @example
   * // Get one Reports
   * const reports = await prisma.reports.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends reportsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, reportsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__reportsClient<runtime.Types.Result.GetResult<Prisma.$reportsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Reports that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reportsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Reports
   * const reports = await prisma.reports.findMany()
   * 
   * // Get first 10 Reports
   * const reports = await prisma.reports.findMany({ take: 10 })
   * 
   * // Only select the `report_id`
   * const reportsWithReport_idOnly = await prisma.reports.findMany({ select: { report_id: true } })
   * 
   */
  findMany<T extends reportsFindManyArgs>(args?: Prisma.SelectSubset<T, reportsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reportsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Reports.
   * @param {reportsCreateArgs} args - Arguments to create a Reports.
   * @example
   * // Create one Reports
   * const Reports = await prisma.reports.create({
   *   data: {
   *     // ... data to create a Reports
   *   }
   * })
   * 
   */
  create<T extends reportsCreateArgs>(args: Prisma.SelectSubset<T, reportsCreateArgs<ExtArgs>>): Prisma.Prisma__reportsClient<runtime.Types.Result.GetResult<Prisma.$reportsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Reports.
   * @param {reportsCreateManyArgs} args - Arguments to create many Reports.
   * @example
   * // Create many Reports
   * const reports = await prisma.reports.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends reportsCreateManyArgs>(args?: Prisma.SelectSubset<T, reportsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Reports and returns the data saved in the database.
   * @param {reportsCreateManyAndReturnArgs} args - Arguments to create many Reports.
   * @example
   * // Create many Reports
   * const reports = await prisma.reports.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Reports and only return the `report_id`
   * const reportsWithReport_idOnly = await prisma.reports.createManyAndReturn({
   *   select: { report_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends reportsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, reportsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reportsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Reports.
   * @param {reportsDeleteArgs} args - Arguments to delete one Reports.
   * @example
   * // Delete one Reports
   * const Reports = await prisma.reports.delete({
   *   where: {
   *     // ... filter to delete one Reports
   *   }
   * })
   * 
   */
  delete<T extends reportsDeleteArgs>(args: Prisma.SelectSubset<T, reportsDeleteArgs<ExtArgs>>): Prisma.Prisma__reportsClient<runtime.Types.Result.GetResult<Prisma.$reportsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Reports.
   * @param {reportsUpdateArgs} args - Arguments to update one Reports.
   * @example
   * // Update one Reports
   * const reports = await prisma.reports.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends reportsUpdateArgs>(args: Prisma.SelectSubset<T, reportsUpdateArgs<ExtArgs>>): Prisma.Prisma__reportsClient<runtime.Types.Result.GetResult<Prisma.$reportsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Reports.
   * @param {reportsDeleteManyArgs} args - Arguments to filter Reports to delete.
   * @example
   * // Delete a few Reports
   * const { count } = await prisma.reports.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends reportsDeleteManyArgs>(args?: Prisma.SelectSubset<T, reportsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Reports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reportsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Reports
   * const reports = await prisma.reports.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends reportsUpdateManyArgs>(args: Prisma.SelectSubset<T, reportsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Reports and returns the data updated in the database.
   * @param {reportsUpdateManyAndReturnArgs} args - Arguments to update many Reports.
   * @example
   * // Update many Reports
   * const reports = await prisma.reports.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Reports and only return the `report_id`
   * const reportsWithReport_idOnly = await prisma.reports.updateManyAndReturn({
   *   select: { report_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends reportsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, reportsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$reportsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Reports.
   * @param {reportsUpsertArgs} args - Arguments to update or create a Reports.
   * @example
   * // Update or create a Reports
   * const reports = await prisma.reports.upsert({
   *   create: {
   *     // ... data to create a Reports
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Reports we want to update
   *   }
   * })
   */
  upsert<T extends reportsUpsertArgs>(args: Prisma.SelectSubset<T, reportsUpsertArgs<ExtArgs>>): Prisma.Prisma__reportsClient<runtime.Types.Result.GetResult<Prisma.$reportsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Reports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reportsCountArgs} args - Arguments to filter Reports to count.
   * @example
   * // Count the number of Reports
   * const count = await prisma.reports.count({
   *   where: {
   *     // ... the filter for the Reports we want to count
   *   }
   * })
  **/
  count<T extends reportsCountArgs>(
    args?: Prisma.Subset<T, reportsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReportsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Reports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReportsAggregateArgs>(args: Prisma.Subset<T, ReportsAggregateArgs>): Prisma.PrismaPromise<GetReportsAggregateType<T>>

  /**
   * Group by Reports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {reportsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends reportsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: reportsGroupByArgs['orderBy'] }
      : { orderBy?: reportsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, reportsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReportsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the reports model
 */
readonly fields: reportsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for reports.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__reportsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.reports$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.reports$usersArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the reports model
 */
export interface reportsFieldRefs {
  readonly report_id: Prisma.FieldRef<"reports", 'String'>
  readonly reporter_id: Prisma.FieldRef<"reports", 'String'>
  readonly reported_item_id: Prisma.FieldRef<"reports", 'String'>
  readonly item_type: Prisma.FieldRef<"reports", 'String'>
  readonly reason: Prisma.FieldRef<"reports", 'String'>
  readonly status: Prisma.FieldRef<"reports", 'String'>
  readonly created_at: Prisma.FieldRef<"reports", 'DateTime'>
}
    

// Custom InputTypes
/**
 * reports findUnique
 */
export type reportsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reports
   */
  select?: Prisma.reportsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reports
   */
  omit?: Prisma.reportsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reportsInclude<ExtArgs> | null
  /**
   * Filter, which reports to fetch.
   */
  where: Prisma.reportsWhereUniqueInput
}

/**
 * reports findUniqueOrThrow
 */
export type reportsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reports
   */
  select?: Prisma.reportsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reports
   */
  omit?: Prisma.reportsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reportsInclude<ExtArgs> | null
  /**
   * Filter, which reports to fetch.
   */
  where: Prisma.reportsWhereUniqueInput
}

/**
 * reports findFirst
 */
export type reportsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reports
   */
  select?: Prisma.reportsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reports
   */
  omit?: Prisma.reportsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reportsInclude<ExtArgs> | null
  /**
   * Filter, which reports to fetch.
   */
  where?: Prisma.reportsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reports to fetch.
   */
  orderBy?: Prisma.reportsOrderByWithRelationInput | Prisma.reportsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for reports.
   */
  cursor?: Prisma.reportsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of reports.
   */
  distinct?: Prisma.ReportsScalarFieldEnum | Prisma.ReportsScalarFieldEnum[]
}

/**
 * reports findFirstOrThrow
 */
export type reportsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reports
   */
  select?: Prisma.reportsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reports
   */
  omit?: Prisma.reportsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reportsInclude<ExtArgs> | null
  /**
   * Filter, which reports to fetch.
   */
  where?: Prisma.reportsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reports to fetch.
   */
  orderBy?: Prisma.reportsOrderByWithRelationInput | Prisma.reportsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for reports.
   */
  cursor?: Prisma.reportsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of reports.
   */
  distinct?: Prisma.ReportsScalarFieldEnum | Prisma.ReportsScalarFieldEnum[]
}

/**
 * reports findMany
 */
export type reportsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reports
   */
  select?: Prisma.reportsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reports
   */
  omit?: Prisma.reportsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reportsInclude<ExtArgs> | null
  /**
   * Filter, which reports to fetch.
   */
  where?: Prisma.reportsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of reports to fetch.
   */
  orderBy?: Prisma.reportsOrderByWithRelationInput | Prisma.reportsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing reports.
   */
  cursor?: Prisma.reportsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` reports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` reports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of reports.
   */
  distinct?: Prisma.ReportsScalarFieldEnum | Prisma.ReportsScalarFieldEnum[]
}

/**
 * reports create
 */
export type reportsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reports
   */
  select?: Prisma.reportsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reports
   */
  omit?: Prisma.reportsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reportsInclude<ExtArgs> | null
  /**
   * The data needed to create a reports.
   */
  data: Prisma.XOR<Prisma.reportsCreateInput, Prisma.reportsUncheckedCreateInput>
}

/**
 * reports createMany
 */
export type reportsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many reports.
   */
  data: Prisma.reportsCreateManyInput | Prisma.reportsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * reports createManyAndReturn
 */
export type reportsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reports
   */
  select?: Prisma.reportsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the reports
   */
  omit?: Prisma.reportsOmit<ExtArgs> | null
  /**
   * The data used to create many reports.
   */
  data: Prisma.reportsCreateManyInput | Prisma.reportsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reportsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * reports update
 */
export type reportsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reports
   */
  select?: Prisma.reportsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reports
   */
  omit?: Prisma.reportsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reportsInclude<ExtArgs> | null
  /**
   * The data needed to update a reports.
   */
  data: Prisma.XOR<Prisma.reportsUpdateInput, Prisma.reportsUncheckedUpdateInput>
  /**
   * Choose, which reports to update.
   */
  where: Prisma.reportsWhereUniqueInput
}

/**
 * reports updateMany
 */
export type reportsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update reports.
   */
  data: Prisma.XOR<Prisma.reportsUpdateManyMutationInput, Prisma.reportsUncheckedUpdateManyInput>
  /**
   * Filter which reports to update
   */
  where?: Prisma.reportsWhereInput
  /**
   * Limit how many reports to update.
   */
  limit?: number
}

/**
 * reports updateManyAndReturn
 */
export type reportsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reports
   */
  select?: Prisma.reportsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the reports
   */
  omit?: Prisma.reportsOmit<ExtArgs> | null
  /**
   * The data used to update reports.
   */
  data: Prisma.XOR<Prisma.reportsUpdateManyMutationInput, Prisma.reportsUncheckedUpdateManyInput>
  /**
   * Filter which reports to update
   */
  where?: Prisma.reportsWhereInput
  /**
   * Limit how many reports to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reportsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * reports upsert
 */
export type reportsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reports
   */
  select?: Prisma.reportsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reports
   */
  omit?: Prisma.reportsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reportsInclude<ExtArgs> | null
  /**
   * The filter to search for the reports to update in case it exists.
   */
  where: Prisma.reportsWhereUniqueInput
  /**
   * In case the reports found by the `where` argument doesn't exist, create a new reports with this data.
   */
  create: Prisma.XOR<Prisma.reportsCreateInput, Prisma.reportsUncheckedCreateInput>
  /**
   * In case the reports was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.reportsUpdateInput, Prisma.reportsUncheckedUpdateInput>
}

/**
 * reports delete
 */
export type reportsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reports
   */
  select?: Prisma.reportsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reports
   */
  omit?: Prisma.reportsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reportsInclude<ExtArgs> | null
  /**
   * Filter which reports to delete.
   */
  where: Prisma.reportsWhereUniqueInput
}

/**
 * reports deleteMany
 */
export type reportsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which reports to delete
   */
  where?: Prisma.reportsWhereInput
  /**
   * Limit how many reports to delete.
   */
  limit?: number
}

/**
 * reports.users
 */
export type reports$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  where?: Prisma.usersWhereInput
}

/**
 * reports without action
 */
export type reportsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the reports
   */
  select?: Prisma.reportsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the reports
   */
  omit?: Prisma.reportsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.reportsInclude<ExtArgs> | null
}
