
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import * as $Class from "./internal/class.js"
import * as Prisma from "./internal/prismaNamespace.js"

export * as $Enums from './enums.js'
export * from "./enums.js"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Blocks
 * const blocks = await prisma.blocks.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model blocks
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type blocks = Prisma.blocksModel
/**
 * Model categories
 * 
 */
export type categories = Prisma.categoriesModel
/**
 * Model chat_participants
 * 
 */
export type chat_participants = Prisma.chat_participantsModel
/**
 * Model chats
 * 
 */
export type chats = Prisma.chatsModel
/**
 * Model comment_likes
 * 
 */
export type comment_likes = Prisma.comment_likesModel
/**
 * Model comments
 * 
 */
export type comments = Prisma.commentsModel
/**
 * Model device_tokens
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type device_tokens = Prisma.device_tokensModel
/**
 * Model follows
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type follows = Prisma.followsModel
/**
 * Model hashtags
 * 
 */
export type hashtags = Prisma.hashtagsModel
/**
 * Model locations
 * 
 */
export type locations = Prisma.locationsModel
/**
 * Model media
 * 
 */
export type media = Prisma.mediaModel
/**
 * Model mentions
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type mentions = Prisma.mentionsModel
/**
 * Model messages
 * 
 */
export type messages = Prisma.messagesModel
/**
 * Model notifications
 * 
 */
export type notifications = Prisma.notificationsModel
/**
 * Model post_blocks
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type post_blocks = Prisma.post_blocksModel
/**
 * Model post_hashtags
 * 
 */
export type post_hashtags = Prisma.post_hashtagsModel
/**
 * Model post_likes
 * 
 */
export type post_likes = Prisma.post_likesModel
/**
 * Model posts
 * 
 */
export type posts = Prisma.postsModel
/**
 * Model profiles
 * 
 */
export type profiles = Prisma.profilesModel
/**
 * Model reports
 * 
 */
export type reports = Prisma.reportsModel
/**
 * Model roles
 * 
 */
export type roles = Prisma.rolesModel
/**
 * Model saved_posts
 * 
 */
export type saved_posts = Prisma.saved_postsModel
/**
 * Model scan_history
 * 
 */
export type scan_history = Prisma.scan_historyModel
/**
 * Model stories
 * 
 */
export type stories = Prisma.storiesModel
/**
 * Model story_views
 * 
 */
export type story_views = Prisma.story_viewsModel
/**
 * Model users
 * 
 */
export type users = Prisma.usersModel
/**
 * Model refresh_tokens
 * 
 */
export type refresh_tokens = Prisma.refresh_tokensModel
/**
 * Model password_resets
 * 
 */
export type password_resets = Prisma.password_resetsModel
